/*
 * Generated by the Pergyra compiler C backend
 * Do not edit manually.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "pgy_runtime.h"
#include "pgy_parallel.h"
#include "pgy_channel.h"
#ifndef PGY_EVENT_MAX_HANDLERS
#define PGY_EVENT_MAX_HANDLERS 16
#endif

int32_t Score(bool flag);

int32_t Score(bool flag);

int32_t Score(bool flag)
{
    if (flag)
    {
        return 7;
    }
    return 3;
}
