/* =================================================================
 * Channel - Int  (LLVM-export twin)
 *
 * The 21 thread-safe channel ops are no longer hand-maintained here: they are
 * generated from the ONE PGY_CHANNEL_DEFINE macro body shared with the C-inline
 * twin (pgy_runtime_channel_inline.h), instantiated below with `extern` storage.
 * The self-contained C output and the linked LLVM runtime now share a single
 * channel implementation, so the two can no longer drift (target #4, dual-backend
 * unified consumption). Only what is genuinely twin-local stays here: the two
 * integer-status-code convenience wrappers (not part of the shared macro) and a
 * one-line deadline-helper name bridge.
 *
 * Destroy is quiescent-only: close/drain/join producers and consumers before
 * freeing the backing buffer and destroying mutex/condvar state.
 * ================================================================= */

#include <pthread.h>
#include "pgy_runtime_channel_status.h"

/* PgyOption_Bool is needed by the macro's try_send_status / send_timeout_status
 * ops. Must match PGY_OPTION_DEFINE(Bool, bool) in pgy_runtime.h. */
typedef struct { int32_t tag; bool value; } PgyOption_Bool;
static inline PgyOption_Bool Some_Bool(bool v) { return (PgyOption_Bool){ 0, v }; }
static inline PgyOption_Bool None_Bool(void)   { return (PgyOption_Bool){ 1, false }; }

/* The shared macro body uses pgy_timespec_after_ns (the C-inline twin's deadline
 * helper, defined in pgy_runtime_panic_checked_inline.h, which is NOT linked into
 * this runtime object). The linked runtime exposes the same computation as
 * pgy_runtime_deadline_after_ns; bridge the name so the macro instantiates here.
 * (Unifying the deadline-helper twin itself is a separate target #4 step.) */
static inline struct timespec pgy_timespec_after_ns(uint64_t timeout_ns)
{
    return pgy_runtime_deadline_after_ns(timeout_ns);
}

/* Reuse the shared PGY_CHANNEL_DEFINE body without the C-inline twin's own
 * static-inline Int instantiation (PGY_CHANNEL_MACRO_ONLY suppresses it), then
 * re-instantiate the same body with extern storage for the linked runtime. */
#define PGY_CHANNEL_MACRO_ONLY
#include "pgy_runtime_channel_inline.h"
#undef PGY_CHANNEL_MACRO_ONLY

PGY_CHANNEL_DEFINE(Int, int32_t, extern)
PGY_CHANNEL_LANE_DEFINE(Int, int32_t, extern)

/* LLVM-only integer-status-code wrappers (not generated by the shared macro):
 * map the PgyOption_Bool status onto an int32 code (-1 = would-block/None,
 * 1 = sent, 0 = closed). They forward to the macro-generated *_status ops. */
int32_t pgy_channel_try_send_status_code_Int(PgyChannel_Int *ch, int32_t v)
{
    PgyOption_Bool status = pgy_channel_try_send_status_Int(ch, v);
    if (status.tag != 0)
        return -1;
    return status.value ? 1 : 0;
}

int32_t pgy_lane_channel_try_send_status_code_Int(int32_t lane,
                                                  PgyChannel_Int *ch,
                                                  int32_t v)
{
    PgyOption_Bool status = pgy_lane_channel_try_send_status_Int(
        (PgyExecutionLane)lane, ch, v);
    if (status.tag != 0)
        return -1;
    return status.value ? 1 : 0;
}

int32_t pgy_channel_send_timeout_status_code_Int(PgyChannel_Int *ch, int32_t v,
                                                 uint64_t timeout_ns)
{
    PgyOption_Bool status =
        pgy_channel_send_timeout_status_Int(ch, v, timeout_ns);
    if (status.tag != 0)
        return -1;
    return status.value ? 1 : 0;
}

int32_t pgy_lane_channel_send_timeout_status_code_Int(int32_t lane,
                                                      PgyChannel_Int *ch,
                                                      int32_t v,
                                                      uint64_t timeout_ns)
{
    PgyOption_Bool status = pgy_lane_channel_send_timeout_status_Int(
        (PgyExecutionLane)lane, ch, v, timeout_ns);
    if (status.tag != 0)
        return -1;
    return status.value ? 1 : 0;
}
