/* =================================================================
 * Channel<String> - LLVM-export twin
 *
 * The String channel ops (the 17 main ops AND the 4 Result adapters) are no
 * longer hand-maintained here: they are generated from the SAME bodies as the
 * C-inline twin by including pgy_runtime_channel_string_inline.h with extern
 * storage (PGY_CH_STR_STORAGE=extern). That header pulls in
 * pgy_runtime_channel_string_result_inline.h at its bottom, so a single include
 * yields the whole extern op set -- one implementation, two storage classes, no
 * drift (target #4). The companion pgy_runtime_lib_channel_string_result_exports.h
 * is therefore no longer included (its ops now come from the shared inline body).
 * Only the two integer-status-code wrappers (not part of the shared op set) and a
 * one-line strdup name bridge remain twin-local.
 *
 * Destroy is quiescent-only: close/drain/join producers and consumers before
 * freeing the backing buffer and destroying mutex/condvar state.
 * ================================================================= */

#include <pthread.h>
#include "pgy_runtime_channel_status.h"

/* The shared String op bodies call pgy_runtime_strdup (the C-inline twin's dup,
 * not linked into this runtime object). The linked runtime exposes the same
 * routine as pgy_runtime_lib_strdup; bridge the name so the shared bodies compile
 * here. (The deadline helper pgy_timespec_after_ns is already bridged TU-wide by
 * the Int export twin compiled earlier in pgy_runtime_lib.c, so it is NOT
 * re-bridged here. Unifying these helper-name twins to one shared name each is a
 * separate target #4 step that removes the bridges.) */
static inline char *pgy_runtime_strdup(const char *src)
{
    return pgy_runtime_lib_strdup(src);
}

/* Reuse the shared String op bodies (main + Result) with extern storage for the
 * linked runtime. PgyOption_Bool / Some_Bool / None_Bool (used by the *_status
 * ops) are already in scope from the Int channel export twin compiled earlier in
 * pgy_runtime_lib.c. */
#define PGY_CH_STR_STORAGE extern
#include "pgy_runtime_channel_string_inline.h"
#undef PGY_CH_STR_STORAGE

/* LLVM-only integer-status-code wrappers (not generated by the shared op set):
 * map the PgyOption_Bool status onto an int32 code (-1 = would-block/None,
 * 1 = sent, 0 = closed). They forward to the shared *_status ops. */
int32_t pgy_channel_try_send_status_code_String(PgyChannel_String *ch, char *v)
{
    PgyOption_Bool status = pgy_channel_try_send_status_String(ch, v);
    if (status.tag != 0)
        return -1;
    return status.value ? 1 : 0;
}

int32_t pgy_channel_send_timeout_status_code_String(PgyChannel_String *ch,
                                                    char *v,
                                                    uint64_t timeout_ns)
{
    PgyOption_Bool status =
        pgy_channel_send_timeout_status_String(ch, v, timeout_ns);
    if (status.tag != 0)
        return -1;
    return status.value ? 1 : 0;
}
