#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
    echo "[security-portability] $*" >&2
    exit 1
}

require_term() {
    local rel="$1"
    local term="$2"

    grep -Fq -- "$term" "$ROOT_DIR/$rel" ||
        fail "$rel missing term: $term"
}

forbid_term() {
    local rel="$1"
    local term="$2"

    if grep -Fq -- "$term" "$ROOT_DIR/$rel"; then
        fail "$rel must not contain term: $term"
    fi
}

require_term "Makefile" "check-security-toolchain:"
require_term "Makefile" "security_windows_bcrypt_preflight.c"
require_term "Makefile" "-lbcrypt"
require_term "Makefile" "security test preflight: checking Windows CNG/BCrypt provider"
require_term "Makefile" "security_openssl_preflight.c"
require_term "Makefile" "-lssl -lcrypto"
require_term "Makefile" "security test preflight: checking OpenSSL EVP/HMAC/RAND provider"

require_term "tests/security_windows_bcrypt_preflight.c" "bcrypt.h"
require_term "tests/security_windows_bcrypt_preflight.c" "BCryptGenRandom"
require_term "tests/security_openssl_preflight.c" "openssl/evp.h"
require_term "tests/security_openssl_preflight.c" "EVP_sha256"

require_term "src/runtime/slot_security_crypto_ops.h" "BCryptGenRandom"
require_term "src/runtime/slot_security_crypto_ops.h" "EVP_DigestInit_ex"
require_term "src/runtime/slot_security_crypto.c" "BCryptOpenAlgorithmProvider"
require_term "src/runtime/slot_security_crypto.c" "EVP_aes_256_ctr"
require_term "src/runtime/slot_security_crypto.c" "SecureHmacSHA256"
require_term "src/runtime/slot_security_crypto.c" "HMAC(EVP_sha256()"
require_term "src/runtime/slot_security.c" "SecureHmacSHA256(context->masterKey"
require_term "src/runtime/slot_security_sealed_payload.c" "AES256Encrypt(context->masterKey"
require_term "src/runtime/slot_security_sealed_payload.c" "AES256Decrypt(context->masterKey"
require_term "src/runtime/slot_security_sealed_payload.c" "SecureHmacSHA256(context->masterKey"
require_term "src/runtime/slot_manager_secure_ops.c" "TokenDecrypt(manager->securityContext"
require_term "src/runtime/slot_manager_secure_ops.c" "TokenCompareSecure(&storedToken, &token->token)"
forbid_term "src/runtime/slot_security.c" "SecurityChecksumBytes"
forbid_term "src/runtime/slot_security_sealed_payload.c" "SecureDeriveMaskBlock"
forbid_term "src/runtime/slot_security_sealed_payload.c" "SecureXorPayload"
forbid_term "src/runtime/slot_security_sealed_payload.c" "SecureHashSHA256(material"
forbid_term "src/runtime/slot_security_crypto.c" "aes_sbox_compute"
forbid_term "src/runtime/slot_security_crypto.c" "gf256_mul"
forbid_term "src/runtime/slot_security_crypto_ops.h" "sha256_transform"
forbid_term "src/runtime/slot_security_crypto_ops.h" "sha256_k"
forbid_term "src/runtime/slot_security_crypto_ops.h" "/dev/urandom"
forbid_term "src/runtime/slot_security_crypto_ops.h" "CryptAcquireContext"
forbid_term "src/runtime/slot_security_crypto_ops.h" "wincrypt.h"

require_term "docs/03_security_mode_design.md" "not a completed third-party cryptographic audit"
require_term "docs/03_security_mode_design.md" "make check-security-toolchain"
require_term "docs/03_security_mode_design.md" "Windows builds"
require_term "docs/03_security_mode_design.md" "CNG/BCrypt"
require_term "docs/03_security_mode_design.md" "non-Windows builds"
require_term "docs/03_security_mode_design.md" "Platform claims must be tied to CI evidence"
require_term "docs/03_security_mode_design.md" "Source-of-truth split"
require_term "docs/03_security_mode_design.md" "generated SecureSlot ABI"
require_term "docs/03_security_mode_design.md" 'The `SlotManager` secure API'
require_term "docs/03_security_mode_design.md" '`SECURITY_LEVEL_*` arguments are parsed and retained'

require_term "docs/security/README.md" "Current Security Source Of Truth"
require_term "docs/security/README.md" "historical/imported"
require_term "docs/security/README.md" "02_red_team_threat_model.md"
require_term "docs/security/README.md" "Windows uses CNG/BCrypt"
require_term "docs/security/README.md" "non-Windows"
require_term "docs/security/README.md" "OpenSSL EVP/HMAC/RAND"
require_term "docs/security/README.md" "do not describe BASIC/HARDWARE/ENCRYPTED as active"

require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Scope Note"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" 'Generated `PgySecureSlot_*` ABI'
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" '`SlotManager` secure runtime API'
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "182/182"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" 'Invalid `SecurityLevel` rejection'
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Capability metadata tamper"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Stored encrypted token tamper"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "../02_red_team_threat_model.md"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Stored authority tamper"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Provider drift"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Sealed payload transplant"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "generation-bound MAC rejection"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "primary provider auth-tag tamper recovery"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "policy tamper rejection"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Token-refresh replay rejection"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "known-answer vectors"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "Windows routes random generation"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "non-Windows routes them through"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "not self-contained AES or SHA implementations"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "standard"
require_term "docs/security/contracts/secure_slot_token_unforgeability.md" "provider APIs"
forbid_term "src/runtime/slot_security_fingerprint.c" "SecureRandomGenerate((uint8_t *)&entropy"

require_term "docs/security/01_audit_targets.md" "Slot id exhaustion availability / tombstone flooding"
require_term "docs/security/01_audit_targets.md" "02_red_team_threat_model.md"
require_term "docs/security/01_audit_targets.md" "Runtime panic DoS boundary policy"
require_term "docs/security/01_audit_targets.md" "Zone-bound handle escape decision and diagnostics"
require_term "docs/security/01_audit_targets.md" "security-portability-contract-test-smoke"
require_term "docs/security/01_audit_targets.md" "make test-security"
require_term "docs/security/01_audit_targets.md" "182/182"
require_term "docs/security/01_audit_targets.md" "Slot / DeviceSlot / SecureSlot"
require_term "docs/security/01_audit_targets.md" "Do not claim a 128-bit Slot handle"
require_term "docs/security/01_audit_targets.md" "Recovery is a boundary"
require_term "docs/security/02_red_team_threat_model.md" "Attacker Tiers"
require_term "docs/security/02_red_team_threat_model.md" "Kill-Chain Families"
require_term "docs/security/02_red_team_threat_model.md" "Defense Matrix"
require_term "docs/security/02_red_team_threat_model.md" "Beta Exit Bar"
require_term "docs/security/02_red_team_threat_model.md" "Generation equality alone is not authority"
require_term "docs/security/02_red_team_threat_model.md" "No self-contained AES/SHA/RNG path may reappear"
require_term "docs/security/02_red_team_threat_model.md" "Do not claim hardware binding is unspoofable"
require_term "docs/security/02_red_team_threat_model.md" "provider AES plus HMAC-bound primary/shadow tests"
require_term "docs/security/02_red_team_threat_model.md" "policy tamper"
require_term "docs/security/02_red_team_threat_model.md" "cross-slot transplant rejection"
require_term "docs/107_beta_stable_subset.md" '`Option<Void>` and `Result<Void>` are not beta-stable'

require_term "src/runtime/slot_manager.h" "typedef struct"
require_term "src/runtime/slot_manager.h" "SlotFailure;"
require_term "src/runtime/slot_manager.h" "const char *SlotErrorName(SlotError err);"
require_term "src/runtime/slot_manager.h" "PgyRuntimeSlotStatus SlotRuntimeStatusFromError(SlotError err);"
require_term "src/runtime/slot_manager.h" "bool SlotErrorBoundaryRecoverable(SlotError err);"
require_term "src/runtime/slot_manager.h" "SlotFailure SlotFailureFromError(SlotError err, const char *operation,"
require_term "src/runtime/slot_manager_core_ops.c" "SlotErrorName(SlotError err)"
require_term "src/runtime/slot_manager_core_ops.c" "SlotRuntimeStatusFromError(SlotError err)"
require_term "src/runtime/slot_manager_core_ops.c" "SlotErrorBoundaryRecoverable(SlotError err)"
require_term "src/runtime/slot_manager_core_ops.c" "SLOT_ERROR_ID_EXHAUSTED"
require_term "src/runtime/slot_manager_core_ops.c" "PGY_RUNTIME_SLOT_STATUS_ID_EXHAUSTED"
require_term "src/runtime/slot_manager_core_ops.c" "SlotFailureFromError(SlotError err, const char *operation,"
require_term "src/runtime/slot_manager_core_ops.c" "SlotErrorName(err)"
require_term "src/runtime/slot_manager_core_ops.c" "failure.runtimeStatus = SlotRuntimeStatusFromError(err)"
require_term "src/runtime/slot_manager_core_ops.c" "failure.recoverable = SlotErrorBoundaryRecoverable(err)"
require_term "src/runtime/slot_manager_core_ops.c" "SlotFailure failure = SlotFailureFromError(err, op, handle)"
require_term "src/runtime/slot_manager_core_ops.c" "manager->nextSlotId == 0 || manager->nextSlotId == UINT32_MAX"
require_term "src/runtime/slot_manager_core_ops.c" "sawGenerationExhausted ? SLOT_ERROR_ID_EXHAUSTED"
require_term "src/runtime/slot_manager_core_ops.c" "recycledGeneration + 1u"
require_term "src/runtime/slot_manager_core_ops.c" "entry->slotId = manager->nextSlotId++"
require_term "src/runtime/slot_manager_core_ops.c" "entry->generation = 1"
require_term "src/runtime/slot_manager.c" "generation = entry->generation"
require_term "src/runtime/slot_manager.h" "uint32_t slotId;"
require_term "src/runtime/slot_manager.h" "uint32_t generation;"
require_term "src/jvm_bridge/jni_bridge.h" "slot_error_to_jni(SlotError error)"
require_term "src/jvm_bridge/jni_bridge.h" "SlotRuntimeStatusFromError(error)"
require_term "docs/74_slot_pinning_caching.md" "hard-fails"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "plainManager->nextSlotId = 0;"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "SLOT_ERROR_ID_EXHAUSTED"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "Zero slot id sentinel is tombstoned before claim"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "plainManager->nextSlotId = UINT32_MAX;"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "Slot id wrap is tombstoned before reuse"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "Released slot id is recycled with advanced generation"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "Recycled stale generation handle cannot read"
require_term "src/tests/security/test_security_slot_pin_lease.cases.h" "Generation-exhausted recycled slot is not OOM"
require_term "src/runtime/pgy_runtime_slot_status.h" "typedef enum"
require_term "src/runtime/pgy_runtime_slot_status.h" "PgyRuntimeSlotStatus;"
require_term "src/runtime/pgy_runtime_slot_status.h" "PgyRuntimeSlotFailure;"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_RESULT_DEFINE"
require_term "src/runtime/pgy_runtime_slot_status.h" "PgyRuntimeSlotResultTag"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_RESULT_ERR"
require_term "src/runtime/pgy_runtime_slot_status.h" "pgy_runtime_slot_status_name(PgyRuntimeSlotStatus status)"
require_term "src/runtime/pgy_runtime_slot_status.h" "pgy_runtime_slot_failure_from_status(PgyRuntimeSlotStatus status,"
require_term "src/runtime/pgy_runtime_slot_status.h" "pgy_runtime_slot_status_boundary_recoverable(PgyRuntimeSlotStatus status)"
require_term "src/runtime/pgy_runtime_slot_status.h" "failure.recoverable = pgy_runtime_slot_status_boundary_recoverable(status)"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_STATUS_INVALID_TOKEN"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_STATUS_TOKEN_DENIES_READ"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_STATUS_TOKEN_DENIES_WRITE"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_STATUS_SLOT_NOT_FOUND"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_STATUS_PERMISSION_DENIED"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_STATUS_PINNED"
require_term "src/runtime/pgy_runtime_slot_status.h" "PGY_RUNTIME_SLOT_STATUS_ID_EXHAUSTED"
require_term "src/runtime/pgy_runtime_io_status.h" "PgyRuntimeIoFailure"
require_term "src/runtime/pgy_runtime_io_status.h" "PgyRuntimeIoStringResult"
require_term "src/runtime/pgy_runtime_io_status.h" "PgyRuntimeIoVoidResult"
require_term "src/runtime/pgy_runtime_io_status.h" "pgy_runtime_io_failure_from_status"
require_term "src/runtime/pgy_runtime_io_status.h" "PGY_RUNTIME_IO_STATUS_INVALID_HANDLE"
require_term "src/runtime/pgy_runtime_channel_status.h" "PgyRuntimeChannelFailure"
require_term "src/runtime/pgy_runtime_channel_status.h" "PgyRuntimeChannelIntResult"
require_term "src/runtime/pgy_runtime_channel_status.h" "PgyRuntimeChannelStringResult"
require_term "src/runtime/pgy_runtime_channel_status.h" "PGY_RUNTIME_CHANNEL_STATUS_CLOSED_EMPTY"
require_term "src/codegen/codegen_channel_runtime_abi.c" "Channel<Int> and Channel<String>"
require_term "src/codegen/transpiler_channel_type_query.c" "pgy_channel_runtime_payload_has_abi"
require_term "src/codegen/llvm_runtime_channels.c" "pgy_channel_runtime_payload_abi_count"
require_term "src/codegen/llvm_runtime_channels.c" "recv_timeout_result"
require_term "src/codegen/llvm_runtime_channels.c" "try_send_status"
require_term "src/codegen/llvm_runtime_channels.c" "send_timeout_status"
require_term "src/codegen/llvm_expr_task_channel_calls.c" "pgy_channel_try_recv_result"
require_term "src/codegen/llvm_expr_task_channel_calls.c" "pgy_channel_try_send_status"
require_term "src/runtime/pgy_runtime_lib_channel_int_exports.h" "Some_Bool(bool v) { return (PgyOption_Bool){ 0, v }; }"
require_term "src/runtime/pgy_runtime_lib_channel_int_exports.h" "pgy_channel_try_send_status_Int"
require_term "src/runtime/pgy_runtime_lib_channel_int_exports.h" "pgy_channel_send_timeout_status_Int"
require_term "src/runtime/pgy_runtime_lib_channel_string_exports.h" "pgy_channel_try_send_status_String"
require_term "src/runtime/pgy_runtime_lib_channel_string_exports.h" "pgy_channel_send_timeout_status_String"
require_term "src/runtime/pgy_runtime_plain_slot_inline.h" "pgy_try_read_##SuffixName"
require_term "src/runtime/pgy_runtime_plain_slot_inline.h" "pgy_try_read_result_##SuffixName"
require_term "src/runtime/pgy_runtime_plain_slot_inline.h" '"slot-boundary", "read"'
require_term "src/runtime/pgy_runtime_slot_macros.h" "pgy_try_device_read_##SuffixName"
require_term "src/runtime/pgy_runtime_slot_macros.h" "pgy_try_device_read_result_##SuffixName"
require_term "src/runtime/pgy_runtime_slot_macros.h" "pgy_try_device_read_result_##SuffixName(arg->slot)"
require_term "src/runtime/pgy_runtime_slot_macros.h" "pgy_try_secure_read_##SuffixName"
require_term "src/runtime/pgy_runtime_slot_macros.h" "pgy_try_secure_read_result_##SuffixName"
require_term "src/runtime/pgy_runtime_lib_intent_slot_core_exports.h" "PGY_SLOT_TRY_EXPORT_DEFINE"
require_term "src/runtime/pgy_runtime_lib_intent_slot_core_exports.h" "pgy_try_read_result_##SuffixName"
require_term "src/runtime/pgy_runtime_lib_device_slot_exports.h" "pgy_try_device_read_##Suffix"
require_term "src/runtime/pgy_runtime_lib_device_slot_exports.h" "pgy_try_device_read_result_##Suffix"
require_term "src/runtime/pgy_runtime_lib_device_slot_exports.h" "pgy_try_device_read_result_##Suffix(arg->slot)"
require_term "src/runtime/pgy_runtime_lib_secure_slot_exports.h" "pgy_try_secure_read_##Suffix"
require_term "src/runtime/pgy_runtime_lib_secure_slot_exports.h" "pgy_try_secure_read_result_##Suffix"
require_term "src/runtime/pgy_runtime_io_qubit_inline.h" "pgy_try_file_open_result"
require_term "src/runtime/pgy_runtime_io_qubit_inline.h" "pgy_try_file_exists_result"
require_term "src/runtime/pgy_runtime_io_qubit_inline.h" "pgy_try_file_read_result"
require_term "src/runtime/pgy_runtime_io_qubit_inline.h" "pgy_try_file_write_result"
require_term "src/runtime/pgy_runtime_io_qubit_inline.h" "pgy_try_read_file_result"
require_term "src/runtime/pgy_runtime_io_qubit_inline.h" "pgy_try_write_file_result"
require_term "src/runtime/pgy_runtime_io_qubit_inline.h" "pgy_try_input_result"
require_term "src/runtime/pgy_runtime_lib_io_string_exports.h" "pgy_try_file_open_result"
require_term "src/runtime/pgy_runtime_lib_io_string_exports.h" "pgy_try_file_exists_result"
require_term "src/runtime/pgy_runtime_lib_io_string_exports.h" "pgy_try_file_read_result"
require_term "src/runtime/pgy_runtime_lib_io_string_exports.h" "pgy_try_file_write_result"
require_term "src/runtime/pgy_runtime_lib_io_string_exports.h" "pgy_try_read_file_result"
require_term "src/runtime/pgy_runtime_lib_io_string_exports.h" "pgy_try_write_file_result"
require_term "src/runtime/pgy_runtime_lib_io_string_exports.h" "pgy_try_input_result"
require_term "src/runtime/pgy_runtime_channel_inline.h" "pgy_channel_recv_result_##SuffixName"
require_term "src/runtime/pgy_runtime_channel_inline.h" "pgy_channel_try_recv_result_##SuffixName"
require_term "src/runtime/pgy_runtime_channel_string_result_inline.h" "pgy_channel_recv_result_String"
require_term "src/runtime/pgy_runtime_lib_channel_int_exports.h" "pgy_channel_recv_result_Int"
require_term "src/runtime/pgy_runtime_lib_channel_string_result_exports.h" "pgy_channel_recv_result_String"
require_term "src/codegen/llvm_expr_await_task.c" "await.remote.err"
require_term "src/codegen/llvm_expr_await_task.c" "remote operation failed"
require_term "src/codegen/llvm_expr_await_task.c" "LLVMBuildICmp(ctx->builder, LLVMIntEQ, raw"
require_term "src/codegen/llvm_expr_await_task.c" "await.local.null"
require_term "src/codegen/llvm_expr_await_task.c" "LLVMConstNull(inner_ty)"
require_term "src/semantic/type_checker_expr.c" "RemoteFuture<Void> await is not in the stable"
require_term "src/semantic/type_checker_resolution_metadata_constructed.c" "semantic_type_resolution_reject_unsupported_stable_constructed_args"
require_term "src/semantic/type_checker_resolution_metadata_diagnostics.c" "Result<Void> is not in the stable subset"
require_term "src/semantic/type_checker_resolution_metadata_diagnostics.c" "Option<Void> is not in the stable subset"
require_term "src/codegen/transpiler_expr_dispatch_emit.c" "does not lower RemoteFuture<Void>"
require_term "src/codegen/transpiler_type_mapping.c" "type_arg_name_is_void"
require_term "src/codegen/transpiler_specialization_registry.c" "Option<Void> does not lower"
require_term "src/codegen/transpiler_specialization_registry.c" "Result<Void, %s> does not lower"
require_term "src/codegen/llvm_stmt_type_infer_await.c" "does not infer RemoteFuture<Void>"
require_term "src/codegen/llvm_expr_await_task.c" "does not lower RemoteFuture<Void>"
require_term "src/codegen/llvm_backend_type_map.c" "Option<Void> does not lower"
require_term "src/codegen/llvm_backend_type_map.c" "Result<Void> does not lower"
require_term "src/codegen/llvm_type.c" "Result<Void, %s> does not lower"
require_term "tests/runtime_panic_abi_smoke.sh" "inline_try_slot_status"
require_term "tests/runtime_panic_abi_smoke.sh" "pgy_try_read_result_Int"
require_term "tests/runtime_panic_abi_smoke.sh" "inline_try_device_slot_status"
require_term "tests/runtime_panic_abi_smoke.sh" "pgy_try_device_read_result_Int"
require_term "tests/runtime_panic_abi_smoke.sh" "inline_remote_released_device_result"
require_term "tests/runtime_panic_abi_smoke.sh" "inline_try_secure_slot_status"
require_term "tests/runtime_panic_abi_smoke.sh" "pgy_try_secure_read_result_Int"
require_term "tests/runtime_panic_abi_smoke.sh" "inline_try_io_result"
require_term "tests/runtime_panic_abi_smoke.sh" "TOKEN_DENIES_READ"
require_term "tests/runtime_panic_abi_smoke.sh" "TOKEN_DENIES_WRITE"
require_term "tests/runtime_panic_abi_smoke.sh" "exported_try_slot_status"
require_term "tests/runtime_panic_abi_smoke.sh" "exported_try_device_slot_status"
require_term "tests/runtime_panic_abi_smoke.sh" "exported_remote_released_device_result"
require_term "tests/runtime_panic_abi_smoke.sh" "exported_try_secure_slot_status"
require_term "tests/runtime_panic_abi_smoke.sh" "exported_try_io_result"

require_term "TODO.md" "Security/runtime portability needs narrower claims"
require_term "TODO.md" "check-security-toolchain"
require_term "TODO.md" "Red-team security closure target"
require_term "TODO.md" "Slot ID/generation exhaustion"

echo "[security-portability] security dependency and claim-scope contract is gated"
