#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
    echo "[self-host-preparation] $*" >&2
    exit 1
}

require_file() {
    local rel="$1"
    [[ -f "$ROOT_DIR/$rel" ]] || fail "missing $rel"
}

require_text() {
    local rel="$1"
    local term="$2"
    grep -Fq -- "$term" "$ROOT_DIR/$rel" ||
        fail "$rel missing term: $term"
}

forbid_text() {
    local rel="$1"
    local term="$2"
    if grep -Fq -- "$term" "$ROOT_DIR/$rel"; then
        fail "$rel contains forbidden term: $term"
    fi
}

source "$ROOT_DIR/tests/self_hosted/compiler_world_manifest.sh"

required_files=(
    "docs/self_hosted/README.md"
    "docs/self_hosted/00_agent_entry.md"
    "docs/self_hosted/01_staged_roadmap.md"
    "docs/self_hosted/02_required_language_surface.md"
    "docs/self_hosted/03_tool_candidates.md"
    "docs/self_hosted/04_beta_exit_handoff.md"
    "docs/self_hosted/05_compiler_core_gap_analysis.md"
    "docs/self_hosted/10_hard_self_host_contract.md"
    "docs/self_hosted/11_compiler_world_architecture.md"
    "docs/self_hosted/12_intent_zone_self_host_architecture.md"
    "docs/self_hosted/13_compiler_substrate_architecture.md"
    "docs/125_source_of_truth_spine.md"
    "docs/INDEX.md"
    "TODO.md"
    "src/self_hosted/README.md"
    "src/self_hosted/PROGRESS.md"
    "src/self_hosted/compiler/README.md"
    "src/self_hosted/compiler/world.pgy"
    "src/self_hosted/compiler/path_manifest_owner.pgy"
    "src/self_hosted/compiler/stage_intents.pgy"
    "tests/self_hosted/compiler_world_manifest.sh"
    "src/self_hosted/tools/diagnostic_catalog_checker/intent.md"
    "src/self_hosted/tools/diagnostic_catalog_checker/main.pgy"
    "src/self_hosted/tools/diagnostic_catalog_checker/scan_owner.pgy"
    "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy"
    "src/self_hosted/tools/diagnostic_catalog_checker/run_owner.pgy"
    "src/self_hosted/tools/diagnostic_catalog_checker/expected/clean.json"
    "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_code.json"
    "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_input.json"
    "src/self_hosted/tools/air_graph_json_validator/main.pgy"
    "src/self_hosted/tools/air_graph_json_validator/scan_owner.pgy"
    "src/self_hosted/tools/air_graph_json_validator/report_owner.pgy"
    "src/self_hosted/tools/air_graph_json_validator/run_owner.pgy"
    "tests/self_hosted/parity/README.md"
    "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh"
    "src/self_hosted/lexer/intent.md"
    "src/self_hosted/lexer/main.pgy"
    "src/self_hosted/lexer/char_owner.pgy"
    "src/self_hosted/lexer/token_owner.pgy"
    "src/self_hosted/lexer/scan_owner.pgy"
    "tests/self_hosted/parity/lexer_parity.sh"
    "src/self_hosted/parser/intent.md"
    "src/self_hosted/parser/main.pgy"
    "src/self_hosted/parser/error_owner.pgy"
    "src/self_hosted/parser/cursor_owner.pgy"
    "src/self_hosted/parser/tree_text_owner.pgy"
    "src/self_hosted/parser/type_name_owner.pgy"
    "src/self_hosted/parser/expr_string_owner.pgy"
    "src/self_hosted/parser/expr_primary_owner.pgy"
    "src/self_hosted/parser/expr_precedence_owner.pgy"
    "src/self_hosted/parser/stmt_if_owner.pgy"
    "src/self_hosted/parser/stmt_parallel_owner.pgy"
    "src/self_hosted/parser/stmt_match_owner.pgy"
    "src/self_hosted/parser/stmt_owner.pgy"
    "src/self_hosted/parser/function_decl_owner.pgy"
    "src/self_hosted/parser/decl_type_owner.pgy"
    "src/self_hosted/parser/decl_ability_owner.pgy"
    "src/self_hosted/parser/decl_event_owner.pgy"
    "src/self_hosted/parser/decl_enum_owner.pgy"
    "src/self_hosted/parser/decl_zone_owner.pgy"
    "src/self_hosted/parser/decl_effect_relation_owner.pgy"
    "src/self_hosted/parser/decl_role_owner.pgy"
    "src/self_hosted/parser/decl_intent_owner.pgy"
    "src/self_hosted/parser/decl_nominal_owner.pgy"
    "src/self_hosted/parser/decl_dispatch_owner.pgy"
    "tests/self_hosted/parity/parser_parity.sh"
    "src/self_hosted/semantic/intent.md"
    "src/self_hosted/semantic/main.pgy"
    "src/self_hosted/semantic/text_scan_owner.pgy"
    "src/self_hosted/semantic/source_bundle_owner.pgy"
    "src/self_hosted/semantic/diagnostic_code_owner.pgy"
    "src/self_hosted/semantic/diagnostic_owner.pgy"
    "src/self_hosted/semantic/env_owner.pgy"
    "src/self_hosted/semantic/expr_type_owner.pgy"
    "src/self_hosted/semantic/expr_validation_owner.pgy"
    "src/self_hosted/semantic/call_check_owner.pgy"
    "src/self_hosted/semantic/body_check_owner.pgy"
    "src/self_hosted/semantic/program_check_owner.pgy"
    "src/self_hosted/semantic/semantic_run_owner.pgy"
    "tests/self_hosted/parity/semantic_parity.sh"
    "tests/self_hosted/parity/selfcheck_sources.sh"
    "tests/self_host_substrate_contract_smoke.sh"
)

for rel in "${required_files[@]}"; do
    require_file "$rel"
done

pgy_compiler_world_require_manifest_paths "$ROOT_DIR" ||
    fail "compiler world path manifest is incomplete"

while IFS= read -r parser_owner; do
    owner_lines="$(wc -l < "$parser_owner")"
    [[ "$owner_lines" -le 600 ]] ||
        fail "${parser_owner#$ROOT_DIR/} exceeds parser owner LOC cap: $owner_lines > 600"
done < <(find "$ROOT_DIR/src/self_hosted/parser" -maxdepth 1 -name '*.pgy' -type f | sort)

core_gap_terms=(
    "The beta stable subset is intentionally narrow."
    "This is enough for compiler-adjacent tools."
    "It is not yet enough for a"
    "compiler core rewrite"
    "Non-Negotiable Pre-Hard-Self-Host Capabilities"
    "What Can Be Self-Hosted First"
    "What Must Not Be Done First"
    "compiler.lex"
    "compiler.codegen.llvm"
    "Hard self-host may be considered only when all are true"
)
for term in "${core_gap_terms[@]}"; do
    require_text "docs/self_hosted/05_compiler_core_gap_analysis.md" "$term"
done

substrate_terms=(
    "Stable graph-heavy compiler data structures"
    "Stable collection ergonomics"
    "Stable arbitrary data tree representation"
    "Arena-backed scratch/result/persistent allocation lanes"
    "Stable scoped unsafe/raw escape policy"
    "Runtime-none/minimal-runtime policy"
)
for term in "${substrate_terms[@]}"; do
    require_text "docs/self_hosted/02_required_language_surface.md" "$term"
done

handoff_terms=(
    "hard-self-host gap analysis"
    "graph-heavy collections"
    "scoped unsafe/raw escape"
    "debug-info strategy"
    "The first self-host work package should be the **Diagnostic Catalog Checker**."
    "The second self-host work package should be the **AIR Graph JSON Validator**."
    "Self-hosted code must not copy the C-era helper-file pattern."
)
for term in "${handoff_terms[@]}"; do
    require_text "docs/self_hosted/04_beta_exit_handoff.md" "$term"
done

agent_terms=(
    "Do not start a full compiler rewrite before beta closure."
    "Keep the C compiler as the oracle during soft, partial, and hard substitution work."
    "Every self-hosted component must have an intent-verification pair"
    "The smallest acceptable unit is:"
    "one parity check against the C implementation."
)
for term in "${agent_terms[@]}"; do
    require_text "docs/self_hosted/00_agent_entry.md" "$term"
done

roadmap_terms=(
    "Soft Self-Host"
    "Partial Self-Host"
    "Hard self-host"
    "metadata dead-end"
    "SoT closure is a pass condition"
)
for term in "${roadmap_terms[@]}"; do
    require_text "docs/self_hosted/01_staged_roadmap.md" "$term"
done

tool_terms=(
    "## 1. Diagnostic Catalog Checker"
    "## 2. AIR Graph JSON Validator"
    "stable JSON or diagnostics output"
    "\"schema\": \"pgy.selfhost.diagnostic-catalog.v1\""
    "\"schema\": \"pgy.selfhost.air-graph-validator.v1\""
    "\"input_schema\": \"pgy.air.graph.v1\""
    "\"findings\": []"
    "Why first:"
    "Why:"
)
for term in "${tool_terms[@]}"; do
    require_text "docs/self_hosted/03_tool_candidates.md" "$term"
done

require_text "docs/self_hosted/README.md" "05_compiler_core_gap_analysis.md"
require_text "docs/self_hosted/README.md" "10_hard_self_host_contract.md"
require_text "docs/self_hosted/README.md" "11_compiler_world_architecture.md"
require_text "docs/self_hosted/README.md" "12_intent_zone_self_host_architecture.md"
require_text "docs/self_hosted/README.md" "13_compiler_substrate_architecture.md"
require_text "docs/self_hosted/README.md" "self-host-preparation-contract-test-smoke"
require_text "docs/self_hosted/README.md" "self-host-preparation-test-smoke"
require_text "docs/self_hosted/README.md" "src/self_hosted/"
require_text "docs/INDEX.md" "self_hosted/05_compiler_core_gap_analysis.md"
require_text "docs/INDEX.md" "self_hosted/10_hard_self_host_contract.md"
require_text "docs/INDEX.md" "self_hosted/11_compiler_world_architecture.md"
require_text "docs/INDEX.md" "self_hosted/12_intent_zone_self_host_architecture.md"
require_text "docs/INDEX.md" "self_hosted/13_compiler_substrate_architecture.md"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "self-host-substrate-architecture-contract"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "The self-hosted compiler has one visible compiler flow and many fact owners."
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "StagePathManifest"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "import graph"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "deterministic collections"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "diagnostic rendering"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "MIR fact graph"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "ABI/layout facts"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "AbiLayoutZone"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "EmissionZone"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "ParityZone"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "no-hidden-runtime"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "Good cache keys:"
require_text "docs/self_hosted/13_compiler_substrate_architecture.md" "Bad cache keys:"
require_text "docs/125_source_of_truth_spine.md" "docs/self_hosted/05_compiler_core_gap_analysis.md"
require_text "TODO.md" "Self-host preparation guard"

require_text "src/self_hosted/README.md" "This directory is not the compiler core."
require_text "src/self_hosted/README.md" "compiler/world.pgy"
require_text "src/self_hosted/README.md" "compiler/path_manifest_owner.pgy"
require_text "src/self_hosted/README.md" "A tool that does not yet pass this contract is a *scaffold*"
require_text "src/self_hosted/compiler/README.md" "Compiler World"
require_text "src/self_hosted/compiler/README.md" "PgyCompilerWorld"
require_text "src/self_hosted/compiler/world.pgy" "world PgyCompilerWorld"
require_text "src/self_hosted/compiler/world.pgy" "zone AbiLayoutZone"
require_text "src/self_hosted/compiler/world.pgy" "object AbiLayoutFacts"
require_text "src/self_hosted/compiler/world.pgy" 'import "path_manifest_owner.pgy"'
require_text "src/self_hosted/compiler/path_manifest_owner.pgy" "func CompilerWorldManifestPathAt"
require_text "src/self_hosted/compiler/world.pgy" "intent CompilePergyraProgram"
require_text "src/self_hosted/compiler/world.pgy" "intent ProveSelfHostedParity"
require_text "src/self_hosted/compiler/stage_intents.pgy" "intent FrontendPipeline"
require_text "src/self_hosted/compiler/stage_intents.pgy" "intent BackendPipeline"
require_text "tests/self_hosted/compiler_world_manifest.sh" "PGY_SELFHOST_COMPILER_WORLD_PATH"
require_text "tests/self_hosted/compiler_world_manifest.sh" "PGY_SELFHOST_COMPILER_PATH_MANIFEST_PATH"
require_text "tests/self_hosted/compiler_world_manifest.sh" "PGY_SELFHOST_COMPILER_STAGE_INTENTS_PATH"
require_text "src/self_hosted/PROGRESS.md" "Implementation inventory is live-measured"
require_text "src/self_hosted/PROGRESS.md" "Released/native replacement remains 0%"
require_text "src/self_hosted/PROGRESS.md" "self-host-progress-metric-test-smoke"
require_text "src/self_hosted/PROGRESS.md" "Hard self-host contract"
require_text "src/self_hosted/PROGRESS.md" "Peripheral Audit Tools (Not Counted In Coverage)"
require_text "src/self_hosted/PROGRESS.md" "Do **not** add peripheral audit tools to the substitution percentage."
require_text "src/self_hosted/PROGRESS.md" "not yet a self-hosted compiler AST model"
require_text "src/self_hosted/PROGRESS.md" "FFI remains intentionally absent from the compiler-pass path"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/intent.md" "pgy.selfhost.diagnostic-catalog.v1"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/intent.md" "tests/diagnostic_registry_smoke.sh"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/intent.md" "Status:** *rung-2 complete*"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/main.pgy" "import \"scan_owner.pgy\""
require_text "src/self_hosted/tools/diagnostic_catalog_checker/main.pgy" "import \"report_owner.pgy\""
require_text "src/self_hosted/tools/diagnostic_catalog_checker/main.pgy" "import \"run_owner.pgy\""
require_text "src/self_hosted/tools/diagnostic_catalog_checker/main.pgy" "RunDiagnosticCatalogCheck"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/scan_owner.pgy" "CountMissingCodes"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/scan_owner.pgy" "BuildDiagnosticFindingFacts"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/scan_owner.pgy" "StringIndexOf"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/scan_owner.pgy" "CountDuplicateLiterals"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/scan_owner.pgy" "CountOrphanDocs"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy" "FindingsJsonFromFacts"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy" "\\\"kind\\\":\\\"input_error\\\""
require_text "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy" "\\\"documented\\\":"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy" "\\\"missing\\\":"
forbid_text "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy" "BuildMissingFindings"
forbid_text "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy" "BuildDuplicateFindings"
forbid_text "src/self_hosted/tools/diagnostic_catalog_checker/report_owner.pgy" "BuildOrphanFindings"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/run_owner.pgy" "FileExists(header_path)"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/run_owner.pgy" "ReadFile(header_path)"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/run_owner.pgy" "ReadFile(docs_path)"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/run_owner.pgy" "Exit(1)"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/clean.json" "\"codes\":"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/clean.json" "\"documented\":"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/clean.json" "\"missing\":0"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/clean.json" "\"duplicates\":0"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/clean.json" "\"orphans\":0"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_code.json" "\"ok\":false"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_code.json" "\"codes\":"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_code.json" "\"missing\":1"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_code.json" "\"kind\":\"missing\""
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_code.json" "PGY_FAKE_DRIFT_FOR_SELFHOST"
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_input.json" "\"kind\":\"input_error\""
require_text "src/self_hosted/tools/diagnostic_catalog_checker/expected/missing_input.json" "src/semantic/diag_codes.h"
require_text "src/self_hosted/tools/air_graph_json_validator/intent.md" "Args -> ENV -> 0x20"
require_text "src/self_hosted/tools/air_graph_json_validator/main.pgy" "import \"scan_owner.pgy\""
require_text "src/self_hosted/tools/air_graph_json_validator/main.pgy" "import \"report_owner.pgy\""
require_text "src/self_hosted/tools/air_graph_json_validator/main.pgy" "import \"run_owner.pgy\""
require_text "src/self_hosted/tools/air_graph_json_validator/main.pgy" "RunAirGraphJsonValidation"
forbid_text "src/self_hosted/tools/air_graph_json_validator/main.pgy" "ReadFile("
forbid_text "src/self_hosted/tools/air_graph_json_validator/main.pgy" "CountMissingKeys"
require_text "src/self_hosted/tools/air_graph_json_validator/scan_owner.pgy" "BuildAirGraphFindingFacts"
require_text "src/self_hosted/tools/air_graph_json_validator/scan_owner.pgy" "CountEnvEffectSites"
require_text "src/self_hosted/tools/air_graph_json_validator/scan_owner.pgy" "CountMissingGraphFeatureKeys"
require_text "src/self_hosted/tools/air_graph_json_validator/scan_owner.pgy" 'JsonObjectFactHasField(root, key)'
require_text "src/self_hosted/tools/air_graph_json_validator/scan_owner.pgy" '"execution_lane"'
require_text "src/self_hosted/tools/air_graph_json_validator/scan_owner.pgy" '"boundary_capture"'
require_text "src/self_hosted/tools/air_graph_json_validator/run_owner.pgy" 'import "../../compiler/air_evidence_owner.pgy";'
require_text "src/self_hosted/tools/air_graph_json_validator/run_owner.pgy" "CompilerAirEvidenceEnvelopeReady()"
require_text "src/self_hosted/tools/air_graph_json_validator/report_owner.pgy" "AirGraphValidatorJson"
require_text "src/self_hosted/tools/air_graph_json_validator/report_owner.pgy" "FindingsJsonFromFacts"
require_text "src/self_hosted/tools/air_graph_json_validator/run_owner.pgy" "ReadFile(fixture_path)"
require_text "src/self_hosted/tools/air_graph_json_validator/run_owner.pgy" "env_effect_sites"
require_text "src/self_hosted/tools/air_graph_json_validator/fixture/cap_env.json" "\"op\":\"Args\",\"effect\":\"ENV\",\"capability_mask\":\"0x20\""
require_text "src/self_hosted/tools/air_graph_json_validator/expected/clean.json" "\"env_effect_sites\":1"
require_text "tests/self_hosted/parity/README.md" "Compiler-core self-host migration from this folder is allowed only as a verified"
require_text "tests/self_hosted/parity/air_graph_json_validator_parity.sh" "counts.env_effect_sites parity"
require_text "tests/self_hosted/parity/air_graph_json_validator_parity.sh" "compare_clean_json_with_owner"
require_text "tests/self_hosted/parity/air_graph_json_validator_parity.sh" "cap_env fixture drifted"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "Rung 2 parity"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "tests/diagnostic_registry_smoke.sh"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "pgy.selfhost.diagnostic-catalog.v1"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "counts.documented parity"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "counts.missing parity"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "counts.orphans parity"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "pgy_selfhost_compare_expected_text_artifact_with_owner"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" '"run_output"'
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "missing-code fixture"
require_text "tests/self_hosted/parity/diagnostic_catalog_checker_parity.sh" "missing-input fixture"
require_text "Makefile" "tests/self_hosted/parity/fuzz_backend_parity_generator_parity.sh"
require_text "tests/self_hosted/parity/fuzz_backend_parity_generator_parity.sh" "Pergyra-origin backend parity fuzz smoke"
require_text "tests/self_hosted/parity/fuzz_backend_parity_generator_parity.sh" "generator parity ok"
require_text "src/self_hosted/lexer/main.pgy" "import \"run_owner.pgy\""
require_text "src/self_hosted/lexer/run_owner.pgy" "import \"scan_owner.pgy\""
require_text "src/self_hosted/lexer/run_owner.pgy" "import \"source_input_owner.pgy\""
require_text "src/self_hosted/lexer/run_owner.pgy" "import \"fixture_manifest_owner.pgy\""
forbid_text "src/self_hosted/lexer/main.pgy" "import \"char_owner.pgy\""
forbid_text "src/self_hosted/lexer/main.pgy" "import \"token_owner.pgy\""
require_text "src/self_hosted/lexer/scan_owner.pgy" "import \"char_owner.pgy\""
require_text "src/self_hosted/lexer/scan_owner.pgy" "import \"token_owner.pgy\""
require_text "src/self_hosted/lexer/char_owner.pgy" "func IsAlphaCode"
require_text "src/self_hosted/lexer/token_owner.pgy" "func KeywordType"
require_text "src/self_hosted/lexer/token_owner.pgy" "func TokenLine"
require_text "src/self_hosted/lexer/scan_owner.pgy" "func LexContent"
require_text "src/self_hosted/parser/main.pgy" "import \"run_owner.pgy\""
require_text "src/self_hosted/parser/run_owner.pgy" "import \"source_path_owner.pgy\""
require_text "src/self_hosted/parser/run_owner.pgy" "import \"program_parse_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"error_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"cursor_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"tree_text_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"type_name_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"expr_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"expr_string_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"expr_primary_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"expr_postfix_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"expr_precedence_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"stmt_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"stmt_if_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"stmt_loop_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"stmt_parallel_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"stmt_match_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"function_decl_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_type_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_ability_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_event_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_enum_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_zone_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_effect_relation_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_role_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_intent_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_nominal_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "import \"decl_dispatch_owner.pgy\""
forbid_text "src/self_hosted/parser/main.pgy" "func ParseDecls"
require_text "src/self_hosted/parser/error_owner.pgy" "func Fail"
require_text "src/self_hosted/parser/cursor_owner.pgy" 'import "../lib/source_scan_owner.pgy";'
require_text "src/self_hosted/lib/source_scan_owner.pgy" "func SkipWhitespaceAndComments"
forbid_text "src/self_hosted/parser/cursor_owner.pgy" "func SkipWhitespaceAndComments("
require_text "src/self_hosted/parser/cursor_owner.pgy" "func ReadIdent"
require_text "src/self_hosted/parser/cursor_owner.pgy" "func MatchKeyword"
require_text "src/self_hosted/parser/cursor_owner.pgy" "func ReadNumber"
require_text "src/self_hosted/parser/cursor_owner.pgy" "func Expect"
require_text "src/self_hosted/parser/source_path_owner.pgy" "func ParserImportGraphSeen"
require_text "src/self_hosted/parser/tree_text_owner.pgy" "func IndentStr"
require_text "src/self_hosted/parser/tree_text_owner.pgy" "func AppendLine"
require_text "src/self_hosted/parser/tree_text_owner.pgy" "func AppendImplicitMain"
require_text "src/self_hosted/parser/type_name_owner.pgy" "func IsPrimitiveType"
require_text "src/self_hosted/parser/type_name_owner.pgy" "func ReadType"
require_text "src/self_hosted/parser/type_name_owner.pgy" "import \"cursor_owner.pgy\""
require_text "src/self_hosted/parser/expr_owner.pgy" "import \"expr_string_owner.pgy\""
require_text "src/self_hosted/parser/expr_owner.pgy" "import \"expr_postfix_owner.pgy\""
require_text "src/self_hosted/parser/expr_owner.pgy" "import \"expr_primary_owner.pgy\""
require_text "src/self_hosted/parser/expr_owner.pgy" "import \"expr_precedence_owner.pgy\""
require_text "src/self_hosted/parser/expr_string_owner.pgy" "func ParseStringInterpolationFact"
require_text "src/self_hosted/parser/expr_string_owner.pgy" "func ParseDollarStringInterpolationFact"
require_text "src/self_hosted/parser/expr_string_owner.pgy" "func ParserExpressionInterpolationGraphContractReady"
require_text "src/self_hosted/parser/expr_string_owner.pgy" "ParseExprFact(value_source, 0, value_cursor)"
require_text "src/self_hosted/parser/expr_string_owner.pgy" "ParserExpressionDirectCallCalleeName(value)"
forbid_text "src/self_hosted/parser/expr_string_owner.pgy" "ParserExpressionInterpolationValue(ParserExpressionLeaf("
forbid_text "src/self_hosted/parser/expr_string_owner.pgy" "ParserExpressionLeaf(value_source)"
forbid_text "src/self_hosted/parser/expr_string_owner.pgy" "func DesugarStringInterpolation"
forbid_text "src/self_hosted/parser/expr_string_owner.pgy" "func DesugarDollarStringInterpolation"
require_text "src/self_hosted/parser/expr_primary_owner.pgy" "func ParsePrimary"
require_text "src/self_hosted/parser/expr_precedence_owner.pgy" "func ParseUnary"
require_text "src/self_hosted/parser/expr_precedence_owner.pgy" "func ParseExpr"
require_text "src/self_hosted/parser/stmt_if_owner.pgy" "func ParseIfStmt"
require_text "src/self_hosted/parser/stmt_parallel_owner.pgy" "func ParseParallelStmt"
require_text "src/self_hosted/parser/stmt_match_owner.pgy" "func ParseMatchStmt"
require_text "src/self_hosted/parser/stmt_owner.pgy" "func ParseOneStmt"
require_text "src/self_hosted/parser/stmt_owner.pgy" "func ParseBlock"
require_text "src/self_hosted/parser/stmt_owner.pgy" "import \"error_owner.pgy\""
require_text "src/self_hosted/parser/stmt_owner.pgy" "import \"stmt_if_owner.pgy\""
require_text "src/self_hosted/parser/stmt_owner.pgy" "import \"stmt_loop_owner.pgy\""
require_text "src/self_hosted/parser/stmt_owner.pgy" "import \"stmt_parallel_owner.pgy\""
require_text "src/self_hosted/parser/stmt_owner.pgy" "import \"stmt_match_owner.pgy\""
require_text "src/self_hosted/parser/function_decl_owner.pgy" "func ParseFunction"
require_text "src/self_hosted/parser/function_decl_owner.pgy" "import \"cursor_owner.pgy\""
require_text "src/self_hosted/parser/function_decl_owner.pgy" "import \"tree_text_owner.pgy\""
require_text "src/self_hosted/parser/function_decl_owner.pgy" "import \"type_name_owner.pgy\""
require_text "src/self_hosted/parser/function_decl_owner.pgy" "import \"expr_owner.pgy\""
require_text "src/self_hosted/parser/function_decl_owner.pgy" "import \"stmt_owner.pgy\""
require_text "src/self_hosted/parser/decl_type_owner.pgy" "func ParseTypeDecl"
require_text "src/self_hosted/parser/decl_type_owner.pgy" "import \"cursor_owner.pgy\""
require_text "src/self_hosted/parser/decl_type_owner.pgy" "import \"tree_text_owner.pgy\""
require_text "src/self_hosted/parser/decl_type_owner.pgy" "import \"type_name_owner.pgy\""
require_text "src/self_hosted/parser/decl_ability_owner.pgy" "func ParseAbilityDecl"
require_text "src/self_hosted/parser/decl_ability_owner.pgy" "import \"function_decl_owner.pgy\""
require_text "src/self_hosted/parser/decl_event_owner.pgy" "func ParseEventDecl"
require_text "src/self_hosted/parser/decl_event_owner.pgy" "import \"cursor_owner.pgy\""
require_text "src/self_hosted/parser/decl_event_owner.pgy" "import \"tree_text_owner.pgy\""
require_text "src/self_hosted/parser/decl_event_owner.pgy" "import \"type_name_owner.pgy\""
require_text "src/self_hosted/parser/decl_enum_owner.pgy" "func ParseEnumDecl"
require_text "src/self_hosted/parser/decl_enum_owner.pgy" "import \"cursor_owner.pgy\""
require_text "src/self_hosted/parser/decl_zone_owner.pgy" "func ParseZoneDecl"
require_text "src/self_hosted/parser/decl_zone_owner.pgy" "import \"expr_owner.pgy\""
require_text "src/self_hosted/parser/decl_zone_owner.pgy" "import \"function_decl_owner.pgy\""
require_text "src/self_hosted/parser/decl_effect_relation_owner.pgy" "func ParseEffectDecl"
require_text "src/self_hosted/parser/decl_effect_relation_owner.pgy" "func ParseRelationDecl"
require_text "src/self_hosted/parser/decl_effect_relation_owner.pgy" "import \"cursor_owner.pgy\""
require_text "src/self_hosted/parser/decl_effect_relation_owner.pgy" "import \"tree_text_owner.pgy\""
require_text "src/self_hosted/parser/decl_effect_relation_owner.pgy" "import \"type_name_owner.pgy\""
require_text "src/self_hosted/parser/decl_role_owner.pgy" "func ParseRoleDecl"
require_text "src/self_hosted/parser/decl_role_owner.pgy" "import \"function_decl_owner.pgy\""
require_text "src/self_hosted/parser/decl_intent_owner.pgy" "func ParseIntentDecl"
require_text "src/self_hosted/parser/decl_intent_owner.pgy" "import \"expr_owner.pgy\""
require_text "src/self_hosted/parser/decl_nominal_owner.pgy" "func ParseNominalDecl"
require_text "src/self_hosted/parser/decl_nominal_owner.pgy" "import \"function_decl_owner.pgy\""
require_text "src/self_hosted/parser/decl_dispatch_owner.pgy" "func ParseDecls"
require_text "src/self_hosted/parser/decl_dispatch_owner.pgy" "ParserImportGraphSeen(import_paths, imp_path)"
require_text "src/self_hosted/parser/decl_dispatch_owner.pgy" "import \"function_decl_owner.pgy\""
require_text "src/self_hosted/parser/decl_dispatch_owner.pgy" "import \"decl_ability_owner.pgy\""
require_text "src/self_hosted/parser/program_parse_owner.pgy" "import \"decl_dispatch_owner.pgy\""
require_file "src/self_hosted/parser/fixture/import_dedup_graph.pgy"
require_file "src/self_hosted/parser/fixture/import_dedup_graph_ast.txt"
require_text "src/self_hosted/parser/fixture_manifest_owner.pgy" "DirWalk(ParserFixtureDir())"
require_text "src/self_hosted/semantic/intent.md" "function return types"
require_text "src/self_hosted/semantic/intent.md" "C compiler accept/reject oracle"
require_text "src/self_hosted/lib/diagnostic.pgy" "namespace SelfHostDiagnostic"
require_text "src/self_hosted/lib/diagnostic.pgy" "RenderError"
require_text "src/self_hosted/lib/diagnostic.pgy" "Diagnostic: "
require_text "src/self_hosted/lib/path.pgy" "namespace SelfHostPath"
require_text "src/self_hosted/lib/path.pgy" "NormalizeImportRelative"
forbid_text "src/self_hosted/parser/main.pgy" "import \"../lib/path.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"../lib/path.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"text_scan_owner.pgy\""
require_text "src/self_hosted/semantic/source_bundle_owner.pgy" "import \"../lib/path.pgy\""
require_text "src/self_hosted/semantic/source_bundle_owner.pgy" "import \"text_scan_owner.pgy\""
require_text "src/self_hosted/semantic/main.pgy" "import \"semantic_run_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"source_bundle_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"env_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"expr_type_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"expr_validation_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"call_check_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"body_check_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"program_check_owner.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"../lib/diagnostic.pgy\""
forbid_text "src/self_hosted/semantic/main.pgy" "import \"diagnostic_code_owner.pgy\""
require_text "src/self_hosted/semantic/diagnostic_owner.pgy" "import \"../lib/diagnostic.pgy\""
require_text "src/self_hosted/semantic/diagnostic_owner.pgy" "import \"diagnostic_code_owner.pgy\""
require_text "src/self_hosted/semantic/main.pgy" "Status: rung-2"
require_text "src/self_hosted/semantic/semantic_run_owner.pgy" "import \"source_bundle_owner.pgy\""
require_text "src/self_hosted/semantic/semantic_run_owner.pgy" "import \"diagnostic_owner.pgy\""
require_text "src/self_hosted/semantic/semantic_run_owner.pgy" "import \"program_check_owner.pgy\""
require_text "src/self_hosted/semantic/program_check_owner.pgy" "import \"text_scan_owner.pgy\""
require_text "src/self_hosted/semantic/program_check_owner.pgy" "import \"expr_type_owner.pgy\""
require_text "src/self_hosted/semantic/program_check_owner.pgy" "import \"body_check_owner.pgy\""
require_text "src/self_hosted/semantic/body_check_owner.pgy" "import \"call_check_owner.pgy\""
require_text "src/self_hosted/semantic/body_check_owner.pgy" "import \"expr_validation_owner.pgy\""
require_text "src/self_hosted/semantic/call_check_owner.pgy" "import \"expr_validation_owner.pgy\""
require_text "src/self_hosted/semantic/expr_validation_owner.pgy" "import \"expr_type_owner.pgy\""
require_text "src/self_hosted/semantic/expr_type_owner.pgy" "import \"env_owner.pgy\""
require_text "src/self_hosted/semantic/diagnostic_owner.pgy" "pgy.selfhost.semantic.v1"
require_text "src/self_hosted/semantic/diagnostic_owner.pgy" "SelfHostDiagnostic_RenderError"
require_text "src/self_hosted/semantic/diagnostic_owner.pgy" "let_type_mismatch"
require_text "src/self_hosted/semantic/diagnostic_owner.pgy" "return_type_mismatch"
require_text "src/self_hosted/semantic/expr_type_owner.pgy" "func ExprType"
require_text "src/self_hosted/semantic/call_check_owner.pgy" "func CheckCall"
require_text "src/self_hosted/semantic/body_check_owner.pgy" "func CheckBody"
require_text "src/self_hosted/semantic/program_check_owner.pgy" "func CheckProgram"
require_text "tests/self_hosted/parity/semantic_parity.sh" "Rung 2 parity"
require_text "tests/self_hosted/parity/semantic_parity.sh" "C compiler"
require_text "tests/self_hosted/parity/semantic_parity.sh" "PGY_SELFHOST_SEMANTIC_BACKENDS"
require_text "tests/self_hosted/parity/semantic_parity.sh" '"semantic-parity-paths"'
require_text "tests/self_hosted/parity/semantic_parity.sh" 'SEMANTIC_SOURCE_DIR="$ROOT_DIR/${harness_paths[6]}"'
forbid_text "tests/self_hosted/parity/semantic_parity.sh" 'cp "$SEMANTIC_SOURCE_DIR/"*.pgy "$PERGYRA_TOOL_BUILD_DIR/"'
require_text "tests/self_hosted/parity/semantic_parity.sh" "raw semantic text leaked"
require_text "tests/self_hosted/parity/semantic_parity.sh" "JSON semantic output leaked"
require_text "Makefile" 'SELFHOST_CODEGEN_BACKENDS ?= $(if $(filter 0,$(LLVM_ENABLED)),c,c llvm)'
require_text "Makefile" 'PGY_SELFHOST_CODEGEN_BACKENDS="$${PGY_SELFHOST_CODEGEN_BACKENDS:-$(SELFHOST_CODEGEN_BACKENDS)}"'

forbid_text "docs/self_hosted/05_compiler_core_gap_analysis.md" "hard self-host can start from the compiler core"
forbid_text "TODO.md" "hard self-host can start from the compiler core"

echo "[self-host-preparation] hard self-host guard and soft-entry criteria ok"
