#!/usr/bin/env bash
#
# site_generator_smoke.sh — the Pergyra homepage generator must keep compiling
# and emitting a well-formed page. This is both a dogfood gate (the language
# builds its own site) and a real-program regression test for the compiler.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$ROOT_DIR/tests/pgy_binary_path_helpers.sh"
pgy_prepend_windows_runtime_paths

PGY="${PGY_BIN:-$ROOT_DIR/bin/pgy}"
PGY="$(pgy_select_optional_exe_binary "$PGY")"
SRC="$ROOT_DIR/site/pergyra_home.pgy"

fail() { echo "[site-generator] FAIL: $*" >&2; exit 1; }

if { [ ! -x "$PGY" ] && [ ! -f "$PGY" ]; } || ! pgy_binary_is_runnable_here "$PGY"; then
    echo "[site-generator] SKIP: compiler binary not runnable"
    exit 0
fi
[ -f "$SRC" ] || fail "missing generator: $SRC"

WORK="$(mktemp -d)"
gen="$WORK/home"
html="$WORK/index.html"

"$PGY" "$(pgy_path_for_compiler "$PGY" "$SRC")" --backend=c -o "$gen" \
    >"$WORK/compile.out" 2>"$WORK/compile.err" || { cat "$WORK/compile.err" >&2; fail "generator did not compile"; }
"$gen" > "$html" 2>/dev/null || fail "generator did not run"

grep -q '<!DOCTYPE html>' "$html" || fail "output missing DOCTYPE"
grep -q '</html>'        "$html" || fail "output missing closing </html>"
grep -q '@keyframes reveal' "$html" || fail "output missing the sequential-reveal animation"
grep -q "class='panel'"  "$html" || fail "output missing webtoon panels"

echo "[site-generator] PASS ($(wc -l < "$html" | tr -d ' ') lines of HTML, generated by Pergyra)"
