#!/usr/bin/env bash
#
# Build the official Pergyra homepage. The page is generated BY a Pergyra
# program (pergyra_home.pgy): compile it, run it, capture its stdout into
# dist/index.html. Open site/dist/index.html in a browser to view.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PGY="${PGY_BIN:-$ROOT/bin/pgy}"
BACKEND="${PGY_BACKEND:-c}"

[ -x "$PGY" ] || PGY="$PGY.exe"
[ -x "$PGY" ] || { echo "build: compiler not found at $PGY (build pgy first)" >&2; exit 1; }

mkdir -p "$ROOT/site/dist"
gen="$(mktemp -d)/pergyra_home"

"$PGY" "$ROOT/site/pergyra_home.pgy" --backend="$BACKEND" -o "$gen"
"$gen" > "$ROOT/site/dist/index.html"

echo "wrote site/dist/index.html ($(wc -l < "$ROOT/site/dist/index.html" | tr -d ' ') lines)"
