/*
 * Copyright (c) 2025 Pergyra Language Project
 * Public AST construction, manipulation, and utility API.
 */

#ifndef PERGYRA_AST_API_H
#define PERGYRA_AST_API_H

#include "ast_types.h"

/* AST creation functions */
ASTNode* ast_create_program(void);
size_t ast_program_statement_count(const ASTNode* node);
ASTNode** ast_program_statements(const ASTNode* node, size_t* count_out);
ASTNode* ast_program_statement(const ASTNode* node, size_t index);
bool ast_program_append_statement(ASTNode* node, ASTNode* statement);
ASTNode* ast_program_detach_statement(ASTNode* node, size_t index);
bool ast_program_replace_statements(ASTNode* node,
                                    ASTNode** statements,
                                    size_t count,
                                    size_t capacity);
const char* ast_declaration_name(const ASTNode* node);
bool ast_replace_declaration_name_copy(ASTNode* node, const char* name);
ASTNode* ast_create_function(const char* name);
size_t ast_func_param_count(const ASTNode* node);
FuncParam** ast_func_params(const ASTNode* node, size_t* count_out);
FuncParam* ast_func_param(const ASTNode* node, size_t index);
GenericParams* ast_func_generic_params(const ASTNode* node);
WhereClause* ast_func_where_clause(const ASTNode* node);
ASTNode* ast_func_return_type(const ASTNode* node);
ASTNode* ast_func_body(const ASTNode* node);
bool ast_func_attach_body(ASTNode* node, ASTNode* body);
ASTNode* ast_func_detach_body(ASTNode* node);
bool ast_func_is_action(const ASTNode* node);
AccessModifier ast_func_access(const ASTNode* node);
bool ast_func_has_explicit_access(const ASTNode* node);
bool ast_func_has_effects_clause(const ASTNode* node);
uint32_t ast_func_declared_effects(const ASTNode* node);
StructuredComment* ast_func_doc_comment(const ASTNode* node);
size_t ast_func_required_ability_count(const ASTNode* node);
ASTNode** ast_func_required_abilities(const ASTNode* node, size_t* count_out);
ASTNode* ast_func_required_ability(const ASTNode* node, size_t index);
const char* ast_func_within_zone(const ASTNode* node);
bool ast_func_set_within_zone_copy(ASTNode* node, const char* within_zone);
const char* ast_func_causes_effect(const ASTNode* node);
size_t ast_func_authorized_by_count(const ASTNode* node);
const char* ast_func_authorized_by(const ASTNode* node, size_t index);
ASTNode* ast_create_class(const char* name);
const char* ast_class_name(const ASTNode* node);
NominalDeclKind ast_class_nominal_kind(const ASTNode* node);
bool ast_class_is_struct(const ASTNode* node);
GenericParams* ast_class_generic_params(const ASTNode* node);
WhereClause* ast_class_where_clause(const ASTNode* node);
ClassField** ast_class_fields(const ASTNode* node, size_t* count_out);
ASTNode** ast_class_methods(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_subject(const char* name);
ASTNode* ast_create_vessel(const char* name);
ASTNode* ast_create_struct(const char* name);
ASTNode* ast_create_object(const char* name);
ASTNode* ast_create_tobject(const char* name);
const char* ast_enum_name(const ASTNode* node);
char** ast_enum_variants(const ASTNode* node, size_t* count_out);
size_t ast_enum_variant_param_count(const ASTNode* node, size_t index);
ASTNode* ast_enum_variant_param(const ASTNode* node, size_t variant_index,
                                size_t param_index);
ASTNode** ast_enum_methods(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_extern_block(const char* abi);
const char* ast_extern_block_abi(const ASTNode* node);
ASTNode** ast_extern_block_declarations(const ASTNode* node, size_t* count_out);
ASTNode* ast_extern_block_declaration(const ASTNode* node, size_t index);
const char* ast_use_module_name(const ASTNode* node);
ASTNode* ast_create_let_declaration(const char* name);
const char* ast_let_name(const ASTNode* node);
ASTNode* ast_let_type(const ASTNode* node);
ASTNode* ast_let_initializer(const ASTNode* node);
bool ast_let_is_mutable(const ASTNode* node);
bool ast_let_is_alias(const ASTNode* node);
size_t ast_let_destructure_name_count(const ASTNode* node);
const char* ast_let_destructure_name(const ASTNode* node, size_t index);
ASTNode* ast_let_destructure_initializer(const ASTNode* node);
ASTNode* ast_create_type_alias(const char* name, ASTNode* target_type);
const char* ast_type_alias_name(const ASTNode* node);
ASTNode* ast_type_alias_target_type(const ASTNode* node);
ASTNode* ast_create_with_statement(void);
ASTNode* ast_create_parallel_block(void);
ASTNode* ast_create_block(void);
ASTNode** ast_block_statements(const ASTNode* node, size_t* count_out);
size_t ast_block_statement_count(const ASTNode* node);
ASTNode* ast_block_statement(const ASTNode* node, size_t index);
ASTNode** ast_block_detach_statements(ASTNode* node, size_t* count_out);
bool ast_block_is_pin_block(const ASTNode* node);
bool ast_block_pin_view_is_write(const ASTNode* node);
const char* ast_block_pin_source_name(const ASTNode* node);
const char* ast_block_pin_view_name(const ASTNode* node);
ASTNode* ast_create_for_loop(void);
const char* ast_for_label(const ASTNode* node);
const char* ast_for_variable(const ASTNode* node);
ASTNode* ast_for_range_start(const ASTNode* node);
ASTNode* ast_for_range_end(const ASTNode* node);
ASTNode* ast_for_iterable(const ASTNode* node);
ASTNode* ast_for_body(const ASTNode* node);
ASTNode* ast_create_while_loop(void);
ASTNode* ast_create_match_statement(void);
ASTNode* ast_create_match_case(void);
ASTNode* ast_match_subject(const ASTNode* node);
ASTNode** ast_match_cases(const ASTNode* node, size_t* count_out);
size_t ast_match_case_count(const ASTNode* node);
ASTNode* ast_match_case_at(const ASTNode* node, size_t index);
ASTNode* ast_match_default_body(const ASTNode* node);
ASTNode* ast_match_case_pattern(const ASTNode* node);
ASTNode** ast_match_case_patterns(const ASTNode* node, size_t* count_out);
size_t ast_match_case_pattern_count(const ASTNode* node);
ASTNode* ast_match_case_pattern_at(const ASTNode* node, size_t index);
ASTNode* ast_match_case_guard(const ASTNode* node);
ASTNode* ast_match_case_body(const ASTNode* node);
ASTNode* ast_create_if_statement(void);
ASTNode* ast_create_return_statement(void);
ASTNode* ast_create_binary(ASTNode* left, Token op, ASTNode* right);
ASTNode* ast_create_unary(Token op, ASTNode* operand);
ASTNode* ast_create_call(ASTNode* callee);
ASTNode* ast_create_member_access(ASTNode* object, const char* member);
ASTNode* ast_member_object(const ASTNode* node);
const char* ast_member_name(const ASTNode* node);
ASTNode* ast_create_array_access(ASTNode* array, ASTNode* index);
ASTNode* ast_array_access_array(const ASTNode* node);
ASTNode* ast_array_access_index(const ASTNode* node);
ASTNode* ast_create_assignment(ASTNode* target, ASTNode* value);
ASTNode* ast_assignment_target(const ASTNode* node);
ASTNode* ast_assignment_value(const ASTNode* node);
double ast_number_value(const ASTNode* node);
bool ast_number_is_long(const ASTNode* node);
const char* ast_string_value(const ASTNode* node);
bool ast_boolean_value(const ASTNode* node);
ASTNode* ast_await_expression(const ASTNode* node);
ASTNode* ast_channel_send_channel(const ASTNode* node);
ASTNode* ast_channel_send_value(const ASTNode* node);
ASTNode* ast_channel_recv_channel(const ASTNode* node);
ASTNode* ast_unary_operand(const ASTNode* node);
Token ast_unary_operator(const ASTNode* node);
ASTNode* ast_binary_left(const ASTNode* node);
ASTNode* ast_binary_right(const ASTNode* node);
Token ast_binary_operator(const ASTNode* node);
size_t ast_array_literal_count(const ASTNode* node);
ASTNode* ast_array_literal_element(const ASTNode* node, size_t index);
size_t ast_tuple_literal_count(const ASTNode* node);
ASTNode* ast_tuple_literal_element(const ASTNode* node, size_t index);
const char* ast_break_label(const ASTNode* node);
const char* ast_continue_label(const ASTNode* node);
ASTNode* ast_if_condition(const ASTNode* node);
ASTNode* ast_if_then_branch(const ASTNode* node);
ASTNode* ast_if_else_branch(const ASTNode* node);
const char* ast_while_label(const ASTNode* node);
ASTNode* ast_while_condition(const ASTNode* node);
ASTNode* ast_while_body(const ASTNode* node);
ASTNode* ast_unsafe_block_body(const ASTNode* node);
ASTNode* ast_defer_body(const ASTNode* node);
ASTNode* ast_return_value(const ASTNode* node);
ASTNode* ast_create_number(const char* value);
ASTNode* ast_create_string(const char* value);
ASTNode* ast_create_boolean(bool value);
ASTNode* ast_create_identifier(const char* name);
const char* ast_identifier_name(const ASTNode* node);
bool ast_replace_identifier_name_copy(ASTNode* node, const char* name);
ASTNode* ast_create_type(const char* name);
const char* ast_type_name(const ASTNode* node);
GenericParams* ast_type_generic_args(const ASTNode* node);
size_t ast_generic_param_count(const GenericParams* params);
GenericParam* ast_generic_param_at(const GenericParams* params, size_t index);
const char* ast_generic_param_name(const GenericParam* param);
ASTNode* ast_generic_param_constraint(const GenericParam* param);
ASTNode* ast_generic_param_default_type(const GenericParam* param);
size_t ast_type_tuple_element_count(const ASTNode* node);
ASTNode* ast_type_tuple_element(const ASTNode* node, size_t index);
bool ast_replace_type_name_copy(ASTNode* node, const char* type_name);
GenericParams* ast_call_generic_args(const ASTNode* node);
size_t ast_call_generic_arg_count(const ASTNode* node);
GenericParam* ast_call_generic_arg(const ASTNode* node, size_t index);
ASTNode* ast_call_callee(const ASTNode* node);
size_t ast_call_arg_count(const ASTNode* node);
ASTNode** ast_call_arguments(const ASTNode* node, size_t* count_out);
ASTNode* ast_call_argument(const ASTNode* node, size_t index);
const char* ast_call_argument_name(const ASTNode* node, size_t index);
void ast_init_call_borrowed_view(ASTNode* node, ASTNode* callee,
                                 ASTNode** arguments, size_t arg_count);

/* Async AST creation functions */
ASTNode* ast_create_async_function(const char* name, bool is_async);
const char* ast_async_func_name(const ASTNode* node);
size_t ast_async_func_param_count(const ASTNode* node);
FuncParam** ast_async_func_params(const ASTNode* node, size_t* count_out);
FuncParam* ast_async_func_param(const ASTNode* node, size_t index);
ASTNode* ast_async_func_body(const ASTNode* node);
ASTNode* ast_create_await_expression(ASTNode* expression);
ASTNode* ast_create_channel_send(ASTNode* channel, ASTNode* value);
ASTNode* ast_create_channel_recv(ASTNode* channel);
ASTNode* ast_create_select_statement(void);
ASTNode* ast_create_async_block(void);
ASTNode** ast_async_block_statements(const ASTNode* node, size_t* count_out);
size_t ast_async_block_statement_count(const ASTNode* node);
ASTNode* ast_async_block_statement(const ASTNode* node, size_t index);
ASTNode** ast_parallel_tasks(const ASTNode* node, size_t* count_out);
size_t ast_parallel_task_count(const ASTNode* node);
ASTNode* ast_parallel_task(const ASTNode* node, size_t index);
ASTNode* ast_with_slot_type(const ASTNode* node);
const char* ast_with_alias(const ASTNode* node);
ASTNode* ast_with_body(const ASTNode* node);
bool ast_with_is_secure(const ASTNode* node);
const char* ast_with_security_level(const ASTNode* node);
ASTNode* ast_create_spawn_expression(ASTNode* function);
ASTNode* ast_spawn_function(const ASTNode* node);
ASTNode** ast_spawn_arguments(const ASTNode* node, size_t* count_out);
size_t ast_spawn_arg_count(const ASTNode* node);
ASTNode* ast_spawn_argument(const ASTNode* node, size_t index);
bool ast_spawn_is_blocking(const ASTNode* node);
ASTNode* ast_create_channel_type(ASTNode* element_type);
ASTNode* ast_channel_type_element_type(const ASTNode* node);
ASTNode* ast_channel_type_capacity(const ASTNode* node);
ASTNode* ast_create_future_type(ASTNode* value_type);
ASTNode* ast_future_type_value_type(const ASTNode* node);
ASTNode* ast_create_task_group(bool wait_all);
ASTNode** ast_task_group_tasks(const ASTNode* node, size_t* count_out);
size_t ast_task_group_task_count(const ASTNode* node);
ASTNode* ast_task_group_task(const ASTNode* node, size_t index);
bool ast_task_group_wait_all(const ASTNode* node);
ASTNode** ast_select_cases(const ASTNode* node, size_t* count_out);
size_t ast_select_case_count(const ASTNode* node);
ASTNode* ast_select_case(const ASTNode* node, size_t index);
ASTNode* ast_select_default_case(const ASTNode* node);

/* AST manipulation functions */
void ast_add_statement(ASTNode* parent, ASTNode* statement);
void ast_add_parallel_task(ASTNode* parallel, ASTNode* task);
void ast_add_argument(ASTNode* call, ASTNode* arg);

/* AST utility functions */
void ast_destroy(ASTNode* node);
void ast_destroy_structured_comment(StructuredComment* comment);
void ast_print(ASTNode* node, int indent);
const char* token_type_to_string(PgyTokenType type);

/* Role/Ability system AST creation functions */
ASTNode* ast_create_ability_declaration(const char* name);
const char* ast_ability_name(const ASTNode* node);
AccessModifier ast_ability_access(const ASTNode* node);
bool ast_ability_has_explicit_access(const ASTNode* node);
bool ast_ability_is_innate(const ASTNode* node);
GenericParams* ast_ability_generic_params(const ASTNode* node);
WhereClause* ast_ability_where_clause(const ASTNode* node);
size_t ast_ability_require_field_count(const ASTNode* node);
ASTNode* ast_ability_require_field(const ASTNode* node, size_t index);
size_t ast_ability_method_count(const ASTNode* node);
ASTNode* ast_ability_method(const ASTNode* node, size_t index);
ASTNode* ast_create_role_declaration(const char* name);
const char* ast_role_name(const ASTNode* node);
ASTNode* ast_create_include_statement(const char* role_name);
ASTNode* ast_role_for_type(const ASTNode* node);
GenericParams* ast_role_generic_params(const ASTNode* node);
WhereClause* ast_role_where_clause(const ASTNode* node);
ASTNode* ast_role_parallel_block(const ASTNode* node);
size_t ast_role_include_count(const ASTNode* node);
ASTNode* ast_role_include(const ASTNode* node, size_t index);
size_t ast_role_impl_count(const ASTNode* node);
ASTNode* ast_role_impl(const ASTNode* node, size_t index);
bool ast_role_impl_method_total_count(const ASTNode* node, size_t* count_out);
const char* ast_include_role_name(const ASTNode* node);
GenericParams* ast_include_type_args(const ASTNode* node);
ASTNode* ast_create_require_field(const char* name);
const char* ast_require_field_name(const ASTNode* node);
ASTNode* ast_require_field_type(const ASTNode* node);
ASTNode* ast_create_impl_ability(ASTNode* ability_ref);
ASTNode* ast_impl_ability_ref(const ASTNode* node);
const char* ast_impl_ability_name(const ASTNode* node);
size_t ast_impl_ability_method_count(const ASTNode* node);
ASTNode* ast_impl_ability_method(const ASTNode* node, size_t index);
ASTNode* ast_create_override_func(ASTNode* func_decl);
ASTNode* ast_override_func_decl(const ASTNode* node);
bool ast_override_calls_super(const ASTNode* node);

/* Roster/World system AST creation functions */
ASTNode* ast_create_roster_declaration(const char* name);
const char* ast_roster_name(const ASTNode* node);
GenericParams* ast_roster_generic_params(const ASTNode* node);
size_t ast_roster_party_count(const ASTNode* node);
ASTNode* ast_roster_party(const ASTNode* node, size_t index);
size_t ast_roster_shared_count(const ASTNode* node);
ASTNode* ast_roster_shared(const ASTNode* node, size_t index);
ASTNode** ast_roster_shared_fields(const ASTNode* node, size_t* count_out);
size_t ast_roster_method_count(const ASTNode* node);
ASTNode* ast_roster_method(const ASTNode* node, size_t index);
ASTNode** ast_roster_methods(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_roster_slot(const char* slot_name, const char* party_type);
const char* ast_roster_slot_name(const ASTNode* node);
const char* ast_roster_slot_party_type(const ASTNode* node);
bool ast_roster_slot_replace_party_type(ASTNode* node, const char* party_type);
ASTNode* ast_create_world_declaration(const char* name);
const char* ast_world_name(const ASTNode* node);
ASTNode** ast_world_rosters(const ASTNode* node, size_t* count_out);
ASTNode** ast_world_zones(const ASTNode* node, size_t* count_out);
const char* ast_world_roster_slot_name(const ASTNode* node);
const char* ast_world_roster_type_name(const ASTNode* node);
ASTNode* ast_world_roster_initializer(const ASTNode* node);
bool ast_world_roster_replace_type_name(ASTNode* node, const char* type_name);
const char* ast_world_zone_slot_name(const ASTNode* node);
const char* ast_world_zone_type_name(const ASTNode* node);
ASTNode* ast_world_zone_initializer(const ASTNode* node);
ASTNode** ast_world_shared_fields(const ASTNode* node, size_t* count_out);
ASTNode** ast_world_states(const ASTNode* node, size_t* count_out);
ASTNode** ast_world_activations(const ASTNode* node, size_t* count_out);
ASTNode** ast_world_deactivations(const ASTNode* node, size_t* count_out);
ASTNode** ast_world_maintained_zones(const ASTNode* node, size_t* count_out);
ASTNode** ast_world_methods(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_world_roster(const char* slot_name, const char* roster_type);
ASTNode* ast_create_world_zone(const char* slot_name, const char* zone_type);
ASTNode* ast_create_world_activate(const char* zone_slot_name);
ASTNode* ast_create_world_deactivate(const char* zone_slot_name);
ASTNode* ast_create_world_maintain(const char* zone_slot_name);
const char* ast_world_directive_zone_slot_name(const ASTNode* node);
const char* ast_world_directive_state_name(const ASTNode* node);
ASTNode* ast_create_world_state(const char* state_name, const char* zone_slot_name,
                                WorldStateSourceKind source_kind,
                                const char* detail_name);
ASTNode* ast_create_world_state_compose(const char* state_name,
                                        WorldStateSourceKind source_kind,
                                        const char** input_names,
                                        size_t input_count);
const char* ast_world_state_name(const ASTNode* node);
const char* ast_world_state_zone_slot_name(const ASTNode* node);
WorldStateSourceKind ast_world_state_source_kind(const ASTNode* node);
const char* ast_world_state_detail_name(const ASTNode* node);
size_t ast_world_state_input_count(const ASTNode* node);
const char* ast_world_state_input_name(const ASTNode* node, size_t index);
ASTNode* ast_create_intent_declaration(const char* name);
ASTNode* ast_create_intent_involves(const char* alias);
ASTNode* ast_create_intent_value(const char* alias);
ASTNode* ast_create_intent_step(const char* name);
const char* ast_intent_decl_name(const ASTNode* node);
ASTNode** ast_intent_decl_involves(const ASTNode* node, size_t* count_out);
size_t ast_intent_decl_involve_count(const ASTNode* node);
ASTNode** ast_intent_decl_values(const ASTNode* node, size_t* count_out);
size_t ast_intent_decl_value_count(const ASTNode* node);
ASTNode** ast_intent_decl_bindings(const ASTNode* node, size_t* count_out);
size_t ast_intent_decl_binding_count(const ASTNode* node);
ASTNode** ast_intent_decl_steps(const ASTNode* node, size_t* count_out);
size_t ast_intent_decl_step_count(const ASTNode* node);
bool ast_intent_decl_is_concurrent(const ASTNode* node);
IntentRollbackPolicy ast_intent_decl_rollback_policy(const ASTNode* node);
ASTNode* ast_intent_decl_priority_expr(const ASTNode* node);
ASTNode* ast_intent_decl_success_expr(const ASTNode* node);
ASTNode* ast_intent_decl_failure_expr(const ASTNode* node);
char** ast_intent_decl_default_who_names(const ASTNode* node, size_t* count_out);
size_t ast_intent_decl_default_who_count(const ASTNode* node);
ASTNode* ast_intent_decl_default_where_type(const ASTNode* node);
const char* ast_intent_involves_alias(const ASTNode* node);
ASTNode* ast_intent_involves_subject_type(const ASTNode* node);
const char* ast_intent_value_alias(const ASTNode* node);
ASTNode* ast_intent_value_type(const ASTNode* node);
const char* ast_intent_step_name(const ASTNode* node);
ASTNode* ast_intent_step_where_type(const ASTNode* node);
ASTNode* ast_intent_step_using_expr(const ASTNode* node);
ASTNode* ast_intent_step_intent_expr(const ASTNode* node);
const char* ast_intent_step_transfer_from_alias(const ASTNode* node);
const char* ast_intent_step_transfer_to_alias(const ASTNode* node);
bool ast_intent_step_replace_transfer_to_alias_copy(ASTNode* node, const char* alias);
char** ast_intent_step_who_names(const ASTNode* node, size_t* count_out);
size_t ast_intent_step_who_count(const ASTNode* node);
ASTNode** ast_intent_step_on_exprs(const ASTNode* node, size_t* count_out);
size_t ast_intent_step_on_expr_count(const ASTNode* node);
ASTNode** ast_intent_step_compensate_exprs(const ASTNode* node, size_t* count_out);
size_t ast_intent_step_compensate_expr_count(const ASTNode* node);
ASTNode* ast_intent_step_pre_expr(const ASTNode* node);
ASTNode* ast_intent_step_guard_expr(const ASTNode* node);
ASTNode* ast_intent_step_post_expr(const ASTNode* node);
ASTNode* ast_intent_step_invariant_expr(const ASTNode* node);
ASTNode** ast_intent_step_required_abilities(const ASTNode* node, size_t* count_out);
size_t ast_intent_step_required_ability_count(const ASTNode* node);
const char* ast_intent_step_causes_effect(const ASTNode* node);
char** ast_intent_step_authorized_by(const ASTNode* node, size_t* count_out);
size_t ast_intent_step_authorized_by_count(const ASTNode* node);
ASTNode* ast_intent_step_expect_expr(const ASTNode* node);
bool ast_intent_step_inherited_who_from_intent(const ASTNode* node);
bool ast_intent_step_derived_who_from_on_receiver(const ASTNode* node);
bool ast_intent_step_derived_who_from_single_participant(const ASTNode* node);
bool ast_intent_step_inherited_where_from_intent(const ASTNode* node);
bool ast_intent_step_inherited_who_from_action(const ASTNode* node);
bool ast_intent_step_inherited_where_from_action(const ASTNode* node);
bool ast_intent_step_inherited_requires_from_action(const ASTNode* node);
bool ast_intent_step_inherited_causes_from_action(const ASTNode* node);
bool ast_intent_step_inherited_authorized_by_from_action(const ASTNode* node);
bool ast_intent_step_derived_authorized_by_from_zone(const ASTNode* node);
bool ast_intent_step_derived_where_from_using(const ASTNode* node);
bool ast_intent_step_derived_where_from_transfer(const ASTNode* node);
bool ast_intent_step_derived_using_from_transfer(const ASTNode* node);
bool ast_intent_step_derived_using_from_where(const ASTNode* node);
bool ast_intent_step_set_where_type(ASTNode* node, ASTNode* where_type);
bool ast_intent_step_set_using_expr(ASTNode* node, ASTNode* using_expr);
bool ast_intent_step_set_causes_effect_copy(ASTNode* node, const char* causes_effect);
bool ast_intent_step_append_who_name_copy(ASTNode* node, const char* alias);
bool ast_intent_step_append_authorized_by_copy(ASTNode* node, const char* alias);
bool ast_intent_step_append_required_ability_clone(ASTNode* node, ASTNode* ability);
void ast_intent_step_clear_authorized_by(ASTNode* node);
void ast_intent_step_mark_inherited_who_from_action(ASTNode* node);
void ast_intent_step_mark_derived_who_from_on_receiver(ASTNode* node);
void ast_intent_step_mark_derived_who_from_single_participant(ASTNode* node);
void ast_intent_step_mark_inherited_where_from_action(ASTNode* node);
void ast_intent_step_mark_inherited_requires_from_action(ASTNode* node);
void ast_intent_step_mark_inherited_causes_from_action(ASTNode* node);
void ast_intent_step_mark_inherited_authorized_by_from_action(ASTNode* node);
void ast_intent_step_mark_derived_authorized_by_from_zone(ASTNode* node);
void ast_intent_step_mark_derived_where_from_using(ASTNode* node);
void ast_intent_step_mark_derived_where_from_transfer(ASTNode* node);
void ast_intent_step_mark_derived_using_from_transfer(ASTNode* node);
void ast_intent_step_mark_derived_using_from_where(ASTNode* node);
ASTNode* ast_create_relation_declaration(const char* name);
const char* ast_relation_name(const ASTNode* node);
RelationEndpointKind ast_relation_between_left_kind(const ASTNode* node);
RelationEndpointKind ast_relation_between_right_kind(const ASTNode* node);
ASTNode* ast_relation_between_left_type(const ASTNode* node);
ASTNode* ast_relation_between_right_type(const ASTNode* node);
ASTNode** ast_relation_slots(const ASTNode* node, size_t* count_out);
ASTNode** ast_relation_refreshes(const ASTNode* node, size_t* count_out);
ASTNode** ast_relation_shared_fields(const ASTNode* node, size_t* count_out);
ASTNode** ast_relation_methods(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_effect_declaration(const char* name);
const char* ast_effect_name(const ASTNode* node);
ASTNode** ast_effect_slots(const ASTNode* node, size_t* count_out);
ASTNode** ast_effect_refreshes(const ASTNode* node, size_t* count_out);
ASTNode** ast_effect_shared_fields(const ASTNode* node, size_t* count_out);
ASTNode** ast_effect_methods(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_zone_declaration(const char* name);
const char* ast_zone_name(const ASTNode* node);
ASTNode** ast_zone_slots(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_layer_slots(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_shared_fields(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_authorities(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_methods(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_refreshes(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_states(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_applies(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_links(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_detaches(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_unlinks(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_maintained_effects(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_maintained_relations(const ASTNode* node, size_t* count_out);
ASTNode** ast_zone_maintained_states(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_domain_slot(const char* slot_name, bool is_subject);
const char* ast_domain_slot_name(const ASTNode* node);
ASTNode* ast_domain_slot_type(const ASTNode* node);
bool ast_domain_slot_is_subject(const ASTNode* node);
bool ast_domain_slot_is_vessel(const ASTNode* node);
bool ast_domain_slot_is_tobject(const ASTNode* node);
bool ast_domain_slot_is_binding(const ASTNode* node);
ASTNode* ast_domain_slot_initializer(const ASTNode* node);
ASTNode* ast_create_zone_layer_slot(const char* slot_name, const char* layer_type, bool is_relation);
const char* ast_zone_layer_slot_name(const ASTNode* node);
const char* ast_zone_layer_slot_layer_type(const ASTNode* node);
bool ast_zone_layer_slot_is_relation(const ASTNode* node);
bool ast_zone_layer_slot_is_pool(const ASTNode* node);
int ast_zone_layer_slot_pool_capacity(const ASTNode* node);
ASTNode* ast_create_zone_apply(const char* effect_slot_name, const char* target_slot_name);
ASTNode* ast_create_zone_link(const char* relation_slot_name, const char* left_slot_name, const char* right_slot_name);
ASTNode* ast_create_zone_detach(const char* effect_slot_name, const char* target_slot_name);
ASTNode* ast_create_zone_unlink(const char* relation_slot_name, const char* left_slot_name, const char* right_slot_name);
ASTNode* ast_create_zone_refresh(const char* object_slot_name, const char* source_slot_name);
const char* ast_zone_refresh_object_slot_name(const ASTNode* node);
const char* ast_zone_refresh_source_slot_name(const ASTNode* node);
const char* ast_zone_refresh_participant_slot_name(const ASTNode* node);
bool ast_zone_refresh_requires_dto(const ASTNode* node);
bool ast_zone_refresh_derives_target_kind(const ASTNode* node);
size_t ast_zone_refresh_field_map_count(const ASTNode* node);
const char* ast_zone_refresh_mapped_target_field(const ASTNode* node,
                                                 size_t index);
const char* ast_zone_refresh_mapped_source_field(const ASTNode* node,
                                                 size_t index);
ASTNode* ast_create_zone_maintain_effect(const char* effect_slot_name, const char* target_slot_name);
ASTNode* ast_create_zone_maintain_relation(const char* relation_slot_name, const char* left_slot_name, const char* right_slot_name);
ASTNode* ast_create_zone_maintain_state(const char* state_name);
const char* ast_zone_effect_slot_name(const ASTNode* node);
const char* ast_zone_effect_target_slot_name(const ASTNode* node);
const char* ast_zone_relation_slot_name(const ASTNode* node);
const char* ast_zone_relation_left_slot_name(const ASTNode* node);
const char* ast_zone_relation_right_slot_name(const ASTNode* node);
const char* ast_zone_directive_state_name(const ASTNode* node);
const char* ast_zone_directive_participant_slot_name(const ASTNode* node);
ASTNode* ast_create_zone_authority(const char* subject_slot_name);
const char* ast_zone_authority_subject_slot_name(const ASTNode* node);
size_t ast_zone_authority_ability_count(const ASTNode* node);
ASTNode** ast_zone_authority_required_abilities(const ASTNode* node,
                                                size_t* count_out);
ASTNode* ast_zone_authority_required_ability(const ASTNode* node,
                                             size_t index);
ASTNode* ast_create_zone_state(const char* state_name, bool is_relation,
                               const char* layer_slot_name,
                               const char* left_or_target_slot_name,
                               const char* right_slot_name);
const char* ast_zone_state_name(const ASTNode* node);
bool ast_zone_state_is_relation(const ASTNode* node);
const char* ast_zone_state_layer_slot_name(const ASTNode* node);
const char* ast_zone_state_left_or_target_slot_name(const ASTNode* node);
const char* ast_zone_state_right_slot_name(const ASTNode* node);

/* Party system AST creation functions */
ASTNode* ast_create_party_declaration(const char* name);
const char* ast_party_name(const ASTNode* node);
GenericParams* ast_party_generic_params(const ASTNode* node);
ASTNode* ast_party_extends(const ASTNode* node);
size_t ast_party_role_count(const ASTNode* node);
ASTNode* ast_party_role(const ASTNode* node, size_t index);
size_t ast_party_shared_count(const ASTNode* node);
ASTNode* ast_party_shared(const ASTNode* node, size_t index);
ASTNode** ast_party_shared_fields(const ASTNode* node, size_t* count_out);
size_t ast_party_method_count(const ASTNode* node);
ASTNode* ast_party_method(const ASTNode* node, size_t index);
ASTNode** ast_party_methods(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_role_slot(const char* slot_name);
const char* ast_role_slot_name(const ASTNode* node);
bool ast_role_slot_is_dynamic(const ASTNode* node);
size_t ast_role_slot_required_ability_count(const ASTNode* node);
ASTNode* ast_role_slot_required_ability(const ASTNode* node, size_t index);
ASTNode** ast_role_slot_required_abilities(const ASTNode* node, size_t* count_out);
ASTNode* ast_create_party_shared(const char* name);
const char* ast_party_shared_name(const ASTNode* node);
ASTNode* ast_party_shared_type(const ASTNode* node);
ASTNode* ast_party_shared_initializer(const ASTNode* node);
ASTNode* ast_create_context_access(const char* method_name, const char* slot_name);
const char* ast_context_access_method_name(const ASTNode* node);
const char* ast_context_access_role_slot_name(const ASTNode* node);
ASTNode* ast_context_access_ability_type(const ASTNode* node);
ASTNode* ast_create_party_instance(const char* party_type);
const char* ast_party_instance_party_type(const ASTNode* node);
size_t ast_party_instance_assignment_count(const ASTNode* node);
const char* ast_party_instance_assignment_slot_name(const ASTNode* node,
                                                   size_t index);
ASTNode* ast_party_instance_assignment_value(const ASTNode* node, size_t index);

/* Event system AST creation functions */
ASTNode* ast_create_event_declaration(const char* name);
const char* ast_event_name(const ASTNode* node);
size_t ast_event_param_count(const ASTNode* node);
ASTNode* ast_event_param(const ASTNode* node, size_t index);
ASTNode* ast_event_return_type(const ASTNode* node);
ASTNode* ast_create_event_subscribe(ASTNode* event, ASTNode* handler);
ASTNode* ast_create_event_unsubscribe(ASTNode* event, ASTNode* handler);
ASTNode* ast_create_event_invoke(ASTNode* event);
ASTNode* ast_event_op_event(const ASTNode* node);
ASTNode* ast_event_op_handler(const ASTNode* node);
ASTNode* ast_event_invoke_event(const ASTNode* node);
ASTNode** ast_event_invoke_arguments(const ASTNode* node, size_t* count_out);
size_t ast_event_invoke_arg_count(const ASTNode* node);
ASTNode* ast_event_invoke_argument(const ASTNode* node, size_t index);
ASTNode* ast_create_event_handler_type(void);
size_t ast_event_handler_param_count(const ASTNode* node);
ASTNode** ast_event_handler_param_types(const ASTNode* node,
                                        size_t* count_out);
ASTNode* ast_event_handler_param_type(const ASTNode* node, size_t index);
ASTNode* ast_event_handler_return_type(const ASTNode* node);
ASTNode* ast_clone(ASTNode* node);
ASTNode* ast_create_lambda_expression(void);
ASTNode** ast_lambda_params(const ASTNode* node, size_t* count_out);
size_t ast_lambda_param_count(const ASTNode* node);
ASTNode* ast_lambda_param(const ASTNode* node, size_t index);
ASTNode* ast_lambda_body(const ASTNode* node);
ASTNode* ast_lambda_return_type(const ASTNode* node);
bool ast_lambda_is_async(const ASTNode* node);

/* Module system AST creation */
ASTNode* ast_create_import_declaration(const char* path);
const char* ast_import_path(const ASTNode* node);
ASTNode* ast_create_namespace_declaration(const char* name);
const char* ast_namespace_name(const ASTNode* node);
ASTNode** ast_namespace_statements(const ASTNode* node, size_t* count_out);
size_t ast_namespace_statement_count(const ASTNode* node);
ASTNode* ast_namespace_statement(const ASTNode* node, size_t index);
void ast_destroy_namespace_shell_only(ASTNode* node);
ASTNode* ast_create_unsafe_block(ASTNode* body);
ASTNode* ast_create_defer_statement(ASTNode* body);
ASTNode* ast_create_bind_statement(const char* party_var, const char* slot_name, const char* role_name);
const char* ast_bind_statement_party_var(const ASTNode* node);
const char* ast_bind_statement_slot_name(const ASTNode* node);
const char* ast_bind_statement_role_name(const ASTNode* node);

#endif /* PERGYRA_AST_API_H */
