#ifndef PERGYRA_TYPE_CHECKER_BUILTINS_STDLIB_COLLECTIONS_INTERNAL_H
#define PERGYRA_TYPE_CHECKER_BUILTINS_STDLIB_COLLECTIONS_INTERNAL_H

#include "../parser/ast.h"
#include "type_system.h"

typedef struct SemanticContext SemanticContext;

typedef enum StdlibCollectionBuiltinKind {
    STDLIB_COLLECTION_UNKNOWN = 0,
    STDLIB_COLLECTION_LIST_NEW,
    STDLIB_COLLECTION_LIST_PUSH,
    STDLIB_COLLECTION_LIST_GET,
    STDLIB_COLLECTION_LIST_SET,
    STDLIB_COLLECTION_LIST_SIZE,
    STDLIB_COLLECTION_LIST_REMOVE,
    STDLIB_COLLECTION_SET_NEW,
    STDLIB_COLLECTION_SET_ADD,
    STDLIB_COLLECTION_SET_REMOVE,
    STDLIB_COLLECTION_SET_HAS,
    STDLIB_COLLECTION_SET_SIZE,
    STDLIB_COLLECTION_SET_VALUES,
    STDLIB_COLLECTION_QUEUE_NEW,
    STDLIB_COLLECTION_QUEUE_PUSH,
    STDLIB_COLLECTION_QUEUE_POP,
    STDLIB_COLLECTION_QUEUE_SIZE,
    STDLIB_COLLECTION_QUEUE_EMPTY,
    STDLIB_COLLECTION_ARRAY_LENGTH,
    STDLIB_COLLECTION_ARRAY_DROP_OWNED_STRINGS,
    STDLIB_COLLECTION_ARRAY_PUSH,
    STDLIB_COLLECTION_ARRAY_PUSH_OWNED_STRING,
    STDLIB_COLLECTION_ARRAY_SET,
    STDLIB_COLLECTION_ARRAY_POP,
    STDLIB_COLLECTION_ARRAY_SORT,
    STDLIB_COLLECTION_ARRAY_REVERSE,
    STDLIB_COLLECTION_ARRAY_MAP,
    STDLIB_COLLECTION_ARRAY_FILTER,
    STDLIB_COLLECTION_SLICE_COPY
} StdlibCollectionBuiltinKind;

Type *type_check_stdlib_array_call(ASTNode *expr,
                                   const char *name,
                                   StdlibCollectionBuiltinKind kind,
                                   SemanticContext *ctx);

#endif
