/*
 * Generated by the Pergyra compiler C backend
 * Do not edit manually.
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "pgy_runtime.h"
#include "pgy_parallel.h"
#include "pgy_channel.h"
#ifndef PGY_EVENT_MAX_HANDLERS
#define PGY_EVENT_MAX_HANDLERS 16
#endif


/* Ability: Routable */
typedef struct
{
    char* (*RouteMark)(void *self);
} Routable_vtable;

/* Ability: Approvable */
typedef struct
{
    char* (*ApprovalMark)(void *self);
} Approvable_vtable;

/* Ability: BatchReady */
typedef struct
{
    char* (*BatchMark)(void *self, void* value);
} BatchReady_vtable;

typedef struct CargoState
{
    int32_t claimed;
    int32_t delivered;
    char* lane;
} CargoState;

/* Auto-generated container types for CargoState */
PGY_SLOT_DEFINE(CargoState, CargoState)
PGY_SECURE_SLOT_DEFINE(CargoState, CargoState)
PGY_BOX_DEFINE(CargoState, CargoState)

int32_t
CargoState_Claim(CargoState *self, int32_t qty, char* laneName);

int32_t
CargoState_Deliver(CargoState *self, int32_t bonus);

int32_t
CargoState_Reset(CargoState *self);

int32_t
CargoState_Claim(CargoState *self, int32_t qty, char* laneName)
{
    self->claimed = qty;
    self->lane = laneName;
    return self->claimed;
}

int32_t
CargoState_Deliver(CargoState *self, int32_t bonus)
{
    self->delivered = (self->claimed + bonus);
    return self->delivered;
}

int32_t
CargoState_Reset(CargoState *self)
{
    self->claimed = 0;
    self->delivered = 0;
    self->lane = "";
    return self->claimed;
}

typedef struct DispatchLedger
{
    int32_t approved;
    int32_t shipped;
    int32_t rolledBack;
} DispatchLedger;

/* Auto-generated container types for DispatchLedger */
PGY_SLOT_DEFINE(DispatchLedger, DispatchLedger)
PGY_SECURE_SLOT_DEFINE(DispatchLedger, DispatchLedger)
PGY_BOX_DEFINE(DispatchLedger, DispatchLedger)

int32_t
DispatchLedger_Approve(DispatchLedger *self, int32_t qty);

int32_t
DispatchLedger_Ship(DispatchLedger *self, int32_t qty);

int32_t
DispatchLedger_Rollback(DispatchLedger *self);

int32_t
DispatchLedger_Approve(DispatchLedger *self, int32_t qty)
{
    self->approved = qty;
    return self->approved;
}

int32_t
DispatchLedger_Ship(DispatchLedger *self, int32_t qty)
{
    self->shipped = qty;
    return self->shipped;
}

int32_t
DispatchLedger_Rollback(DispatchLedger *self)
{
    self->rolledBack = (self->rolledBack + 1);
    self->approved = 0;
    self->shipped = 0;
    return self->rolledBack;
}

typedef struct Courier
{
    char* name;
    char* badge;
    CargoState cargo;
    int32_t prepared;
    int32_t delivered;
    char* lastPhase;
} Courier;

/* Auto-generated container types for Courier */
PGY_SLOT_DEFINE(Courier, Courier)
PGY_SECURE_SLOT_DEFINE(Courier, Courier)
PGY_BOX_DEFINE(Courier, Courier)

int32_t
Courier_Prepare(Courier *self, int32_t qty);

int32_t
Courier_Deliver(Courier *self, int32_t bonus);

int32_t
Courier_RollbackPrepare(Courier *self);

int32_t
Courier_RollbackDelivery(Courier *self);

char*
Courier_Summary(Courier *self);

int32_t
Courier_Prepare(Courier *self, int32_t qty)
{
    int32_t staged = CargoState_Claim(&self->cargo, qty, "bay-a");
    self->prepared = staged;
    self->lastPhase = "prepared";
    return staged;
}

int32_t
Courier_Deliver(Courier *self, int32_t bonus)
{
    int32_t shipped = CargoState_Deliver(&self->cargo, bonus);
    self->delivered = shipped;
    self->lastPhase = "delivered";
    return shipped;
}

int32_t
Courier_RollbackPrepare(Courier *self)
{
    CargoState_Reset(&self->cargo);
    self->prepared = 0;
    self->delivered = 0;
    self->lastPhase = "rollback-prepare";
    return self->prepared;
}

int32_t
Courier_RollbackDelivery(Courier *self)
{
    self->delivered = 0;
    self->cargo.delivered = 0;
    self->lastPhase = "rollback-delivery";
    return self->delivered;
}

char*
Courier_Summary(Courier *self)
{
    return StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(self->name, " badge="), self->badge), " prepared="), pgy_int_to_string(self->prepared)), " delivered="), pgy_int_to_string(self->delivered)), " phase="), self->lastPhase);
}

typedef struct Dispatcher
{
    char* name;
    DispatchLedger ledger;
    char* lane;
    char* lastPhase;
} Dispatcher;

/* Auto-generated container types for Dispatcher */
PGY_SLOT_DEFINE(Dispatcher, Dispatcher)
PGY_SECURE_SLOT_DEFINE(Dispatcher, Dispatcher)
PGY_BOX_DEFINE(Dispatcher, Dispatcher)

int32_t
Dispatcher_ApproveDispatch(Dispatcher *self, int32_t qty);

int32_t
Dispatcher_ConfirmDelivery(Dispatcher *self, int32_t qty);

int32_t
Dispatcher_RollbackDispatch(Dispatcher *self);

char*
Dispatcher_Summary(Dispatcher *self);

int32_t
Dispatcher_ApproveDispatch(Dispatcher *self, int32_t qty)
{
    int32_t approved = DispatchLedger_Approve(&self->ledger, qty);
    self->lastPhase = "approved";
    return approved;
}

int32_t
Dispatcher_ConfirmDelivery(Dispatcher *self, int32_t qty)
{
    int32_t shipped = DispatchLedger_Ship(&self->ledger, qty);
    self->lastPhase = "shipped";
    return shipped;
}

int32_t
Dispatcher_RollbackDispatch(Dispatcher *self)
{
    int32_t rolled = DispatchLedger_Rollback(&self->ledger);
    self->lastPhase = "rollback";
    return rolled;
}

char*
Dispatcher_Summary(Dispatcher *self)
{
    return StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(self->name, " lane="), self->lane), " approved="), pgy_int_to_string(self->ledger.approved)), " shipped="), pgy_int_to_string(self->ledger.shipped)), " rolled="), pgy_int_to_string(self->ledger.rolledBack)), " phase="), self->lastPhase);
}

typedef struct CourierView
{
    char* name;
    int32_t prepared;
    int32_t delivered;
    char* lastPhase;
} CourierView;

/* Auto-generated container types for CourierView */
PGY_SLOT_DEFINE(CourierView, CourierView)
PGY_SECURE_SLOT_DEFINE(CourierView, CourierView)
PGY_BOX_DEFINE(CourierView, CourierView)

typedef struct DispatchPacket
{
    char* name;
    char* lane;
    int32_t approved;
    int32_t shipped;
} DispatchPacket;

/* Auto-generated container types for DispatchPacket */
PGY_SLOT_DEFINE(DispatchPacket, DispatchPacket)
PGY_SECURE_SLOT_DEFINE(DispatchPacket, DispatchPacket)
PGY_BOX_DEFINE(DispatchPacket, DispatchPacket)
char* ProbeHeader(void);
char* ProbeSubtitle(void);
int32_t MergeRouteScore(bool flag, int32_t base);
void Main(void);

/* Role: CourierRoute */

static char*
CourierRoute_RouteMark(void *_raw_self)
{
    Courier *self = (Courier *)_raw_self;
    (void)self;
    return "route-ready";
}

static const Routable_vtable CourierRoute_Routable_vtable_instance __attribute__((unused)) = {
    .RouteMark = CourierRoute_RouteMark,
};

static char*
CourierRoute_BatchMark(void *_raw_self, int32_t value)
{
    Courier *self = (Courier *)_raw_self;
    (void)self;
    return StringConcat("batch-", pgy_int_to_string(value));
}

static const BatchReady_Int_vtable CourierRoute_BatchReady_Int_vtable_instance __attribute__((unused)) = {
    .BatchMark = CourierRoute_BatchMark,
};

/* Role: DispatcherApprove */

static char*
DispatcherApprove_ApprovalMark(void *_raw_self)
{
    Dispatcher *self = (Dispatcher *)_raw_self;
    (void)self;
    return "approval-ready";
}

static const Approvable_vtable DispatcherApprove_Approvable_vtable_instance __attribute__((unused)) = {
    .ApprovalMark = DispatcherApprove_ApprovalMark,
};

/* Relation: RouteLink */
typedef struct RouteLink
{
    Courier source;
    Dispatcher target;
    char* lane;
} RouteLink;

static inline void
RouteLink_sync(RouteLink *self)
{
}

char*
RouteLink_Label(RouteLink *self);

char*
RouteLink_Label(RouteLink *self)
{
    RouteLink_sync(self);
    return StringConcat(StringConcat(StringConcat(StringConcat(self->source.name, " -> "), self->target.name), " lane="), self->lane);
    RouteLink_sync(self);
}

/* Effect: CargoSeal */
typedef struct CargoSeal
{
    Courier bearer;
    int32_t qty;
} CargoSeal;

static inline void
CargoSeal_sync(CargoSeal *self)
{
}

char*
CargoSeal_Label(CargoSeal *self);

char*
CargoSeal_Label(CargoSeal *self)
{
    CargoSeal_sync(self);
    return StringConcat(StringConcat(self->bearer.name, " seal qty="), pgy_int_to_string(self->qty));
    CargoSeal_sync(self);
}

/* Zone: LoadingZone */
typedef struct LoadingZone
{
    Courier courier;
    Dispatcher dispatcher;
    CourierView courierView;
    bool __projection_ready_courierView;
    bool __projection_dirty_courierView;
    DispatchPacket dispatchPacket;
    bool __projection_ready_dispatchPacket;
    bool __projection_dirty_dispatchPacket;
    CargoSeal seal;
    bool __layer_active_seal;
    RouteLink route;
    bool __layer_active_route;
    char* stage;
    int32_t staged;
    int32_t routeScore;
    bool __state_sealed;
    bool __state_linked;
    PGY_ZONE_LOCK_FIELD
    PGY_ZONE_GENERATION_FIELD
} LoadingZone;

static inline bool
LoadingZone_has_layer_seal(LoadingZone *self, uint32_t expected_gen)
{
    bool result;
    PGY_ZONE_RDLOCK(self);
    PGY_ZONE_GENERATION_WARN_IF_STALE(self, expected_gen, "LoadingZone.seal");
    result = self->__layer_active_seal;
    PGY_ZONE_UNLOCK(self);
    return result;
}

static inline bool
LoadingZone_has_layer_route(LoadingZone *self, uint32_t expected_gen)
{
    bool result;
    PGY_ZONE_RDLOCK(self);
    PGY_ZONE_GENERATION_WARN_IF_STALE(self, expected_gen, "LoadingZone.route");
    result = self->__layer_active_route;
    PGY_ZONE_UNLOCK(self);
    return result;
}

static inline void
LoadingZone_sync(LoadingZone *self)
{
    PGY_ZONE_WRLOCK(self);
    PGY_ZONE_GENERATION_INC(self);
    self->__state_sealed = false;
    self->__state_linked = false;
    self->__layer_active_seal = false;
    self->__layer_active_route = false;
    if (self->__projection_dirty_courierView) {
        self->__projection_ready_courierView = false;
        self->courierView = (CourierView){ .name = self->courier.name, .prepared = self->courier.prepared, .delivered = self->courier.delivered, .lastPhase = self->courier.lastPhase };
        self->__projection_ready_courierView = true;
        self->__projection_dirty_courierView = false;
    }
    if (self->__projection_dirty_dispatchPacket) {
        self->__projection_ready_dispatchPacket = false;
        self->dispatchPacket = (DispatchPacket){ .name = self->dispatcher.name, .lane = self->dispatcher.lane, .approved = self->dispatcher.ledger.approved, .shipped = self->dispatcher.ledger.shipped };
        self->__projection_ready_dispatchPacket = true;
        self->__projection_dirty_dispatchPacket = false;
    }
    self->__layer_active_seal = true;
    self->seal.bearer = self->courier;
    CargoSeal_sync(&self->seal);
    self->__state_sealed = true;
    self->__layer_active_route = true;
    self->route.source = self->courier;
    self->route.target = self->dispatcher;
    RouteLink_sync(&self->route);
    self->__state_linked = true;
    PGY_ZONE_UNLOCK(self);
}

int32_t
LoadingZone_Stage(LoadingZone *self, int32_t qty);

char*
LoadingZone_Snapshot(LoadingZone *self);

int32_t
LoadingZone_Stage(LoadingZone *self, int32_t qty)
{
    PGY_ZONE_AUTHORITY_CHECK(self, &self->courier, "LoadingZone", "courier");
    LoadingZone_sync(self);
    uint32_t __attribute__((unused)) __pgy_zone_gen = self->__sync_generation;
    int32_t prepared = ({ int32_t _pgy_call_1 = Courier_Prepare(&self->courier, qty); self->__projection_dirty_courierView = true; self->__projection_ready_courierView = false; self->__projection_dirty_courierView = true; self->__projection_ready_courierView = false; _pgy_call_1; });
    Dispatcher_ApproveDispatch(&self->dispatcher, prepared);
    self->seal.qty = prepared;
    self->route.lane = "loading-bay";
    self->staged = prepared;
    self->routeScore = MergeRouteScore(true, qty);
    self->stage = "staged";
    return self->staged;
    LoadingZone_sync(self);
}

char*
LoadingZone_Snapshot(LoadingZone *self)
{
    PGY_ZONE_AUTHORITY_CHECK(self, &self->courier, "LoadingZone", "courier");
    LoadingZone_sync(self);
    uint32_t __attribute__((unused)) __pgy_zone_gen = self->__sync_generation;
    return StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(self->stage, " staged="), pgy_int_to_string(self->staged)), " score="), pgy_int_to_string(self->routeScore)), " sealed="), pgy_int_to_string(self->seal.qty));
    LoadingZone_sync(self);
}

/* Zone: DeliveryZone */
typedef struct DeliveryZone
{
    Courier courier;
    Dispatcher dispatcher;
    CourierView courierView;
    bool __projection_ready_courierView;
    bool __projection_dirty_courierView;
    DispatchPacket dispatchPacket;
    bool __projection_ready_dispatchPacket;
    bool __projection_dirty_dispatchPacket;
    CargoSeal seal;
    bool __layer_active_seal;
    RouteLink route;
    bool __layer_active_route;
    char* stage;
    int32_t received;
    int32_t routeScore;
    bool __state_sealed;
    bool __state_linked;
    PGY_ZONE_LOCK_FIELD
    PGY_ZONE_GENERATION_FIELD
} DeliveryZone;

static inline bool
DeliveryZone_has_layer_seal(DeliveryZone *self, uint32_t expected_gen)
{
    bool result;
    PGY_ZONE_RDLOCK(self);
    PGY_ZONE_GENERATION_WARN_IF_STALE(self, expected_gen, "DeliveryZone.seal");
    result = self->__layer_active_seal;
    PGY_ZONE_UNLOCK(self);
    return result;
}

static inline bool
DeliveryZone_has_layer_route(DeliveryZone *self, uint32_t expected_gen)
{
    bool result;
    PGY_ZONE_RDLOCK(self);
    PGY_ZONE_GENERATION_WARN_IF_STALE(self, expected_gen, "DeliveryZone.route");
    result = self->__layer_active_route;
    PGY_ZONE_UNLOCK(self);
    return result;
}

static inline void
DeliveryZone_sync(DeliveryZone *self)
{
    PGY_ZONE_WRLOCK(self);
    PGY_ZONE_GENERATION_INC(self);
    self->__state_sealed = false;
    self->__state_linked = false;
    self->__layer_active_seal = false;
    self->__layer_active_route = false;
    if (self->__projection_dirty_courierView) {
        self->__projection_ready_courierView = false;
        self->courierView = (CourierView){ .name = self->courier.name, .prepared = self->courier.prepared, .delivered = self->courier.delivered, .lastPhase = self->courier.lastPhase };
        self->__projection_ready_courierView = true;
        self->__projection_dirty_courierView = false;
    }
    if (self->__projection_dirty_dispatchPacket) {
        self->__projection_ready_dispatchPacket = false;
        self->dispatchPacket = (DispatchPacket){ .name = self->dispatcher.name, .lane = self->dispatcher.lane, .approved = self->dispatcher.ledger.approved, .shipped = self->dispatcher.ledger.shipped };
        self->__projection_ready_dispatchPacket = true;
        self->__projection_dirty_dispatchPacket = false;
    }
    self->__layer_active_seal = true;
    self->seal.bearer = self->courier;
    CargoSeal_sync(&self->seal);
    self->__state_sealed = true;
    self->__layer_active_route = true;
    self->route.source = self->courier;
    self->route.target = self->dispatcher;
    RouteLink_sync(&self->route);
    self->__state_linked = true;
    PGY_ZONE_UNLOCK(self);
}

int32_t
DeliveryZone_Receive(DeliveryZone *self, int32_t bonus);

char*
DeliveryZone_Snapshot(DeliveryZone *self);

int32_t
DeliveryZone_Receive(DeliveryZone *self, int32_t bonus)
{
    PGY_ZONE_AUTHORITY_CHECK(self, &self->courier, "DeliveryZone", "courier");
    DeliveryZone_sync(self);
    uint32_t __attribute__((unused)) __pgy_zone_gen = self->__sync_generation;
    int32_t shipped = ({ int32_t _pgy_call_2 = Courier_Deliver(&self->courier, bonus); self->__projection_dirty_courierView = true; self->__projection_ready_courierView = false; self->__projection_dirty_courierView = true; self->__projection_ready_courierView = false; _pgy_call_2; });
    Dispatcher_ConfirmDelivery(&self->dispatcher, shipped);
    self->seal.qty = shipped;
    self->route.lane = "city-gate";
    self->received = shipped;
    self->routeScore = MergeRouteScore(false, shipped);
    self->stage = "received";
    return self->received;
    DeliveryZone_sync(self);
}

char*
DeliveryZone_Snapshot(DeliveryZone *self)
{
    PGY_ZONE_AUTHORITY_CHECK(self, &self->courier, "DeliveryZone", "courier");
    DeliveryZone_sync(self);
    uint32_t __attribute__((unused)) __pgy_zone_gen = self->__sync_generation;
    return StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(self->stage, " received="), pgy_int_to_string(self->received)), " score="), pgy_int_to_string(self->routeScore)), " sealed="), pgy_int_to_string(self->seal.qty));
    DeliveryZone_sync(self);
}

bool
RouteCargo(LoadingZone *loading, DeliveryZone *delivery, Courier *courier, Dispatcher *dispatcher);
LoadingZone BuildLoadingZone(void);
DeliveryZone BuildDeliveryZone(void);

/* World: LogisticsWorld */
typedef struct LogisticsWorld
{
    LoadingZone loading;
    bool __zone_active_loading;
    bool __zone_dirty_loading;
    DeliveryZone delivery;
    bool __zone_active_delivery;
    bool __zone_dirty_delivery;
    char* transcript;
    int32_t completed;
    bool __world_derived_dirty;
} LogisticsWorld;

static inline void
LogisticsWorld_sync(LogisticsWorld *self)
{
    /* world command pass: reset */
    bool _pgy_prev_active_loading = self->__zone_active_loading;
    self->__zone_active_loading = false;
    bool _pgy_prev_active_delivery = self->__zone_active_delivery;
    self->__zone_active_delivery = false;
    bool _pgy_world_needs_derived = self->__world_derived_dirty;
    /* world command pass: directives */
    self->__zone_active_loading = true;
    self->__zone_active_delivery = true;
    if (self->__zone_active_loading != _pgy_prev_active_loading) {
        self->__zone_dirty_loading = true;
        _pgy_world_needs_derived = true;
    }
    if (self->__zone_active_delivery != _pgy_prev_active_delivery) {
        self->__zone_dirty_delivery = true;
        _pgy_world_needs_derived = true;
    }
    /* world zone sync pass */
    if (self->__zone_dirty_loading) {
        LoadingZone_sync(&self->loading);
        self->__zone_dirty_loading = false;
        _pgy_world_needs_derived = true;
    }
    if (self->__zone_dirty_delivery) {
        DeliveryZone_sync(&self->delivery);
        self->__zone_dirty_delivery = false;
        _pgy_world_needs_derived = true;
    }
    /* world derived pass */
    if (_pgy_world_needs_derived) {
        self->__world_derived_dirty = false;
    }
}

void
LogisticsWorld_Record(LogisticsWorld *self, char* line);

void
LogisticsWorld_Broadcast(LogisticsWorld *self, char* line);

void
LogisticsWorld_Blank(LogisticsWorld *self);

void
LogisticsWorld_FinalSnapshot(LogisticsWorld *self);

void
LogisticsWorld_Record(LogisticsWorld *self, char* line)
{
    LogisticsWorld_sync(self);
    if ((((int32_t)strlen(self->transcript)) == 0))
    {
        self->transcript = line;
    }
    else
    {
        self->transcript = StringConcat(StringConcat(self->transcript, "\n"), line);
    }
    self->__zone_dirty_loading = true;
    self->__zone_dirty_delivery = true;
    self->__world_derived_dirty = true;
    LogisticsWorld_sync(self);
}

void
LogisticsWorld_Broadcast(LogisticsWorld *self, char* line)
{
    LogisticsWorld_sync(self);
    pgy_log(line);
    LogisticsWorld_Record(self, line);
    self->__zone_dirty_loading = true;
    self->__zone_dirty_delivery = true;
    self->__world_derived_dirty = true;
    LogisticsWorld_sync(self);
}

void
LogisticsWorld_Blank(LogisticsWorld *self)
{
    LogisticsWorld_sync(self);
    pgy_log("");
    LogisticsWorld_Record(self, "");
    self->__zone_dirty_loading = true;
    self->__zone_dirty_delivery = true;
    self->__world_derived_dirty = true;
    LogisticsWorld_sync(self);
}

void
LogisticsWorld_FinalSnapshot(LogisticsWorld *self)
{
    LogisticsWorld_sync(self);
    LogisticsWorld_Broadcast(self, StringConcat("loading=", LoadingZone_Snapshot(&self->loading)));
    LogisticsWorld_Broadcast(self, StringConcat("delivery=", DeliveryZone_Snapshot(&self->delivery)));
    LogisticsWorld_Broadcast(self, StringConcat("courier=", Courier_Summary(&self->loading.courier)));
    LogisticsWorld_Broadcast(self, StringConcat("dispatcher=", Dispatcher_Summary(&self->loading.dispatcher)));
    LogisticsWorld_Broadcast(self, StringConcat("route=", RouteLink_Label(&self->delivery.route)));
    LogisticsWorld_Broadcast(self, StringConcat("seal=", CargoSeal_Label(&self->delivery.seal)));
    self->__zone_dirty_loading = true;
    self->__zone_dirty_delivery = true;
    self->__world_derived_dirty = true;
    LogisticsWorld_sync(self);
}


typedef struct
{
    char* (*BatchMark)(void *self, int32_t value);
} BatchReady_Int_vtable;
char* ProbeHeader(void);
char* ProbeSubtitle(void);
int32_t MergeRouteScore(bool flag, int32_t base);
LoadingZone BuildLoadingZone(void);
DeliveryZone BuildDeliveryZone(void);
LogisticsWorld OpenLogisticsWorld(void);
char* AuditHandles(LogisticsWorld *world, LoadingZone *loading, RouteLink *route, CargoSeal *seal);
void Main(void);

bool
RouteCargo(LoadingZone *loading, DeliveryZone *delivery, Courier *courier, Dispatcher *dispatcher);

char* ProbeHeader(void)
{
    /* emitted-from-mir */
    goto _pgy_mir_bb_ProbeHeader_0;
    /* mir block=0 hir=0 (ProbeHeader) src=0:0 ast=0x60848ac851d0 */
    _pgy_mir_bb_ProbeHeader_0:
    return "=== PERGYRA LOGISTICS INTENT PROBE ===";
}

char* ProbeSubtitle(void)
{
    /* emitted-from-mir */
    goto _pgy_mir_bb_ProbeSubtitle_0;
    /* mir block=0 hir=0 (ProbeSubtitle) src=0:0 ast=0x60848ac859b0 */
    _pgy_mir_bb_ProbeSubtitle_0:
    return "DIR validates domain edges; RIR tracks resources; MIR shows merge and cleanup.";
}

int32_t MergeRouteScore(bool flag, int32_t base)
{
    int32_t _pgy_ssa_score_1 = 0;
    int32_t _pgy_ssa_score_2 = 0;
    int32_t _pgy_ssa_score_3 = 0;
    int32_t _pgy_ssa_score_6 = 0;
    int32_t _pgy_ssa_score_4 = 0;
    int32_t _pgy_ssa_score_5 = 0;
    /* emitted-from-mir */
    goto _pgy_mir_bb_MergeRouteScore_0;
    /* mir block=0 hir=0 (MergeRouteScore) src=0:0 ast=0x60848ac865e0 */
    _pgy_mir_bb_MergeRouteScore_0:
    _pgy_ssa_score_1 = base;
    if (flag) {
        goto _pgy_mir_bb_MergeRouteScore_1;
    } else {
        goto _pgy_mir_bb_MergeRouteScore_3;
    }
    /* mir block=1 hir=1 (MergeRouteScore) src=0:0 ast=0x60848ac87220 */
    _pgy_mir_bb_MergeRouteScore_1:
    _pgy_ssa_score_2 = (_pgy_ssa_score_1 + 7);
    _pgy_ssa_score_3 = _pgy_ssa_score_2;
    goto _pgy_mir_bb_MergeRouteScore_2;
    /* mir block=2 hir=2 (MergeRouteScore) src=0:0 ast=0x60848ac87cc0 */
    _pgy_mir_bb_MergeRouteScore_2:
    if ((base > 3)) {
        goto _pgy_mir_bb_MergeRouteScore_4;
    } else {
        _pgy_ssa_score_5 = _pgy_ssa_score_3;
        goto _pgy_mir_bb_MergeRouteScore_5;
    }
    /* mir block=3 hir=3 (MergeRouteScore) src=0:0 ast=0x60848ac87a90 */
    _pgy_mir_bb_MergeRouteScore_3:
    _pgy_ssa_score_6 = (_pgy_ssa_score_1 + 13);
    _pgy_ssa_score_3 = _pgy_ssa_score_6;
    goto _pgy_mir_bb_MergeRouteScore_2;
    /* mir block=4 hir=4 (MergeRouteScore) src=0:0 ast=0x60848ac88810 */
    _pgy_mir_bb_MergeRouteScore_4:
    _pgy_ssa_score_4 = (_pgy_ssa_score_3 + 1);
    _pgy_ssa_score_5 = _pgy_ssa_score_4;
    goto _pgy_mir_bb_MergeRouteScore_5;
    /* mir block=5 hir=5 (MergeRouteScore) src=0:0 ast=0x60848ac88a40 */
    _pgy_mir_bb_MergeRouteScore_5:
    return _pgy_ssa_score_5;
}

LoadingZone BuildLoadingZone(void)
{
    Courier courier = (Courier){ .name = "Ivo", .badge = "north-17", .cargo = (CargoState){ .claimed = 0, .delivered = 0, .lane = "" }, .prepared = 0, .delivered = 0, .lastPhase = "idle" };
    Dispatcher dispatcher = (Dispatcher){ .name = "Mara", .ledger = (DispatchLedger){ .approved = 0, .shipped = 0, .rolledBack = 0 }, .lane = "north", .lastPhase = "idle" };
    return (LoadingZone){ .courier = courier, .dispatcher = dispatcher, .courierView = (CourierView){ .name = courier.name, .prepared = courier.prepared, .delivered = courier.delivered, .lastPhase = courier.lastPhase }, .dispatchPacket = (DispatchPacket){ .name = dispatcher.name, .lane = dispatcher.lane, .approved = dispatcher.ledger.approved, .shipped = dispatcher.ledger.shipped }, .stage = "loading", .staged = 0, .routeScore = 0, .__projection_dirty_courierView = true, .__projection_dirty_dispatchPacket = true };
}

DeliveryZone BuildDeliveryZone(void)
{
    Courier courier = (Courier){ .name = "Ivo", .badge = "north-17", .cargo = (CargoState){ .claimed = 0, .delivered = 0, .lane = "" }, .prepared = 0, .delivered = 0, .lastPhase = "idle" };
    Dispatcher dispatcher = (Dispatcher){ .name = "Mara", .ledger = (DispatchLedger){ .approved = 0, .shipped = 0, .rolledBack = 0 }, .lane = "north", .lastPhase = "idle" };
    return (DeliveryZone){ .courier = courier, .dispatcher = dispatcher, .courierView = (CourierView){ .name = courier.name, .prepared = courier.prepared, .delivered = courier.delivered, .lastPhase = courier.lastPhase }, .dispatchPacket = (DispatchPacket){ .name = dispatcher.name, .lane = dispatcher.lane, .approved = dispatcher.ledger.approved, .shipped = dispatcher.ledger.shipped }, .stage = "delivery", .received = 0, .routeScore = 0, .__projection_dirty_courierView = true, .__projection_dirty_dispatchPacket = true };
}

LogisticsWorld OpenLogisticsWorld(void)
{
    LoadingZone loading = BuildLoadingZone();
    DeliveryZone delivery = BuildDeliveryZone();
    delivery.courier = loading.courier;
    delivery.dispatcher = loading.dispatcher;
    return (LogisticsWorld){ .loading = loading, .delivery = delivery, .transcript = "", .completed = 0, .__zone_dirty_loading = true, .__zone_dirty_delivery = true, .__world_derived_dirty = true };
}

char* AuditHandles(LogisticsWorld *world, LoadingZone *loading, RouteLink *route, CargoSeal *seal)
{
    int32_t bias = 0;
    if ((world->completed > 0))
    {
        bias = (bias + 2);
    }
    else
    {
        bias = (bias + 1);
    }
    return StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat(StringConcat("audit loading=", pgy_int_to_string(loading->staged)), " lane="), route->lane), " seal="), pgy_int_to_string(seal->qty)), " bias="), pgy_int_to_string(bias));
}

void Main(void)
{
    LogisticsWorld world = OpenLogisticsWorld();
    LogisticsWorld_Broadcast(&world, ProbeHeader());
    LogisticsWorld_Broadcast(&world, ProbeSubtitle());
    LogisticsWorld_Blank(&world);
    int32_t mergeA = MergeRouteScore(true, 4);
    int32_t mergeB = MergeRouteScore(false, 4);
    LogisticsWorld_Broadcast(&world, StringConcat("merge.true=", pgy_int_to_string(mergeA)));
    LogisticsWorld_Broadcast(&world, StringConcat("merge.false=", pgy_int_to_string(mergeB)));
    bool ok = RouteCargo(&world.loading, &world.delivery, &world.loading.courier, &world.loading.dispatcher);
    world.completed = ok;
    LogisticsWorld_Broadcast(&world, StringConcat("[Intent] RouteCargo ok=", ((ok) ? "true" : "false")));
    LogisticsWorld_Broadcast(&world, StringConcat(StringConcat(StringConcat(StringConcat(StringConcat("  [Runtime] name=", pgy_intent_last_name_export()), " handle="), pgy_int_to_string(pgy_intent_last_handle_export())), " failed="), ((pgy_intent_last_failed_export()) ? "true" : "false")));
    LogisticsWorld_Broadcast(&world, StringConcat("  [Runtime] steps=", pgy_int_to_string(pgy_intent_last_step_count_export())));
    LogisticsWorld_Broadcast(&world, StringConcat("  [Trace] ", pgy_intent_last_trace_export()));
    LogisticsWorld_Broadcast(&world, StringConcat("  [HistoryCount] ", pgy_int_to_string(pgy_intent_history_count_export())));
    LogisticsWorld_Blank(&world);
    LogisticsWorld_Broadcast(&world, AuditHandles(&world, &world.loading, &world.delivery.route, &world.delivery.seal));
    LogisticsWorld_FinalSnapshot(&world);
    LogisticsWorld_Blank(&world);
    LogisticsWorld_Broadcast(&world, "saving examples/logistics_intent_probe/results.txt");
    pgy_write_file("examples/logistics_intent_probe/results.txt", StringConcat(world.transcript, "\n"));
}

bool
RouteCargo(LoadingZone *loading, DeliveryZone *delivery, Courier *courier, Dispatcher *dispatcher)
{
    bool __intent_result = false;
    bool __intent_failed = false;
    (void)__intent_failed;
    int32_t __intent_handle = 0;
    bool __intent_step_completed[2] = { false };
    void *__intent_subjects[2];
    __intent_subjects[0] = (void *)courier;
    __intent_subjects[1] = (void *)dispatcher;
    __intent_handle = pgy_intent_enter_export("RouteCargo", __intent_subjects, 2, false, 11);
    if (__intent_handle == 0) {
        __intent_failed = true;
        __intent_result = false;
        goto __intent_cleanup;
    }
    /* intent step: stage */
    pgy_intent_trace_step_export(__intent_handle, "stage", "LoadingZone");
    pgy_intent_trace_bind_export(__intent_handle, "courier", "courier");
    loading->courier = *courier;
    pgy_intent_trace_materialize_export(__intent_handle, "courier", "courier", "LoadingZone");
    LoadingZone_sync(loading);
    Courier *__intent_saved_0_courier = courier;
    courier = &loading->courier;
    if (!((courier->prepared == 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "pre:stage"); __intent_result = false; goto __intent_cleanup; }
    if (!((courier->cargo.claimed >= 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "invariant-pre:stage"); __intent_result = false; goto __intent_cleanup; }
    LoadingZone_Stage(loading, 5);
    LoadingZone_sync(loading);
    *__intent_saved_0_courier = *courier;
    courier = __intent_saved_0_courier;
    __intent_step_completed[0] = true;
    if (!((loading->staged > 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "guard:stage"); __intent_result = false; goto __intent_cleanup; }
    if (!((loading->staged > 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "post:stage"); __intent_result = false; goto __intent_cleanup; }
    if (!((courier->cargo.claimed >= 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "invariant-post:stage"); __intent_result = false; goto __intent_cleanup; }
    pgy_intent_trace_step_ok_export(__intent_handle, "stage");
    /* intent step: handoff */
    pgy_intent_trace_step_export(__intent_handle, "handoff", "DeliveryZone");
    pgy_intent_trace_bind_export(__intent_handle, "courier", "courier");
    loading->courier = *courier;
    pgy_intent_trace_materialize_export(__intent_handle, "courier", "courier", "LoadingZone");
    delivery->courier = *courier;
    pgy_intent_trace_transfer_export(__intent_handle, "courier", "LoadingZone", "courier", "DeliveryZone", "courier");
    LoadingZone_sync(loading);
    DeliveryZone_sync(delivery);
    Courier *__intent_saved_1_courier = courier;
    courier = &delivery->courier;
    if (!((loading->staged > 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "pre:handoff"); __intent_result = false; goto __intent_cleanup; }
    if (!((courier->delivered >= 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "invariant-pre:handoff"); __intent_result = false; goto __intent_cleanup; }
    DeliveryZone_Receive(delivery, 3);
    DeliveryZone_sync(delivery);
    *__intent_saved_1_courier = *courier;
    courier = __intent_saved_1_courier;
    __intent_step_completed[1] = true;
    if (!((delivery->received > 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "guard:handoff"); __intent_result = false; goto __intent_cleanup; }
    if (!((delivery->received > 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "post:handoff"); __intent_result = false; goto __intent_cleanup; }
    if (!((courier->delivered >= 0))) { __intent_failed = true; pgy_intent_trace_fail_export(__intent_handle, "invariant-post:handoff"); __intent_result = false; goto __intent_cleanup; }
    pgy_intent_trace_step_ok_export(__intent_handle, "handoff");
    __intent_result = (delivery->received > 0);
    goto __intent_cleanup;
    __intent_cleanup:
        if (__intent_failed) {
            if (__intent_step_completed[1]) {
                Courier_RollbackDelivery(courier);
                loading->courier = *courier;
                pgy_intent_trace_materialize_export(__intent_handle, "courier", "courier", "LoadingZone");
                delivery->courier = *courier;
                pgy_intent_trace_transfer_export(__intent_handle, "courier", "LoadingZone", "courier", "DeliveryZone", "courier");
                LoadingZone_sync(loading);
                DeliveryZone_sync(delivery);
            }
            if (__intent_step_completed[0]) {
                Courier_RollbackPrepare(courier);
                loading->courier = *courier;
                pgy_intent_trace_materialize_export(__intent_handle, "courier", "courier", "LoadingZone");
                LoadingZone_sync(loading);
            }
        }
        if (__intent_handle != 0) pgy_intent_exit_export(__intent_handle);
        return __intent_result;
}

int
main(void)
{
    Main();
    return 0;
}
