/*
 * Copyright (c) 2026 Pergyra Language Project
 * LLVM runtime core/log/intent/authority declaration owner.
 */

#ifdef PGY_LLVM_ENABLED

#include "llvm_internal.h"
#include "llvm_runtime_internal.h"

void
llvm_declare_runtime_core_builtins(LLVMGenCtx *ctx)
{
    struct { const char *name; LLVMTypeRef param; } log_fns[] = {
        { "pgy_log_int",    ctx->type_i32 },
        { "pgy_log_long",   ctx->type_i64 },
        { "pgy_log_float",  ctx->type_f32 },
        { "pgy_log_double", ctx->type_f64 },
        { "pgy_log_bool",   ctx->type_i1  },
        { "pgy_log_string", ctx->type_i8ptr },
        { "pgy_log_banner", ctx->type_i8ptr },
    };

    for (size_t i = 0; i < sizeof(log_fns) / sizeof(log_fns[0]); i++) {
        LLVMTypeRef params[] = { log_fns[i].param };
        LLVMTypeRef ft = LLVMFunctionType(ctx->type_void, params, 1, 0);
        LLVMValueRef fn = LLVMAddFunction(ctx->module, log_fns[i].name, ft);
        llvm_register_function(ctx, log_fns[i].name, fn, ft, ctx->type_void);
    }

    {
        LLVMTypeRef params[] = { ctx->type_i8ptr };
        LLVMTypeRef ft = LLVMFunctionType(ctx->type_i32, params, 1, 1);
        LLVMValueRef fn = LLVMAddFunction(ctx->module, "printf", ft);
        llvm_register_function(ctx, "printf", fn, ft, ctx->type_i32);
    }

    {
        struct {
            const char *name;
            LLVMTypeRef ret;
            LLVMTypeRef params[6];
            unsigned param_count;
        } builtins[] = {
            { "StringContains", ctx->type_i1,
              { ctx->type_i8ptr, ctx->type_i8ptr }, 2 },
            { "StringReplace", ctx->type_i8ptr,
              { ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr }, 3 },
            { "Substring", ctx->type_i8ptr,
              { ctx->type_i8ptr, ctx->type_i32, ctx->type_i32 }, 3 },
            { "StringTrim", ctx->type_i8ptr,
              { ctx->type_i8ptr }, 1 },
            { "ToUpper", ctx->type_i8ptr,
              { ctx->type_i8ptr }, 1 },
            { "ToLower", ctx->type_i8ptr,
              { ctx->type_i8ptr }, 1 },
            { "StringConcat", ctx->type_i8ptr,
              { ctx->type_i8ptr, ctx->type_i8ptr }, 2 },
            { "StringSplit", ctx->array_type_String,
              { ctx->type_i8ptr, ctx->type_i8ptr }, 2 },
            { "pgy_string_equals", ctx->type_i1,
              { ctx->type_i8ptr, ctx->type_i8ptr }, 2 },
            { "pgy_runtime_panic_internal_invariant_export", ctx->type_void,
              { ctx->type_i8ptr }, 1 },
            { "pgy_checked_div_i32_export", ctx->type_i32,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_checked_div_i64_export", ctx->type_i64,
              { ctx->type_i64, ctx->type_i64 }, 2 },
            { "pgy_checked_mod_i32_export", ctx->type_i32,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_checked_mod_i64_export", ctx->type_i64,
              { ctx->type_i64, ctx->type_i64 }, 2 },
            { "ToInt", ctx->type_i32,
              { ctx->type_i8ptr }, 1 },
            { "ToFloat", ctx->type_f32,
              { ctx->type_i8ptr }, 1 },
            { "Random", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_int_to_string", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_float_to_string", ctx->type_i8ptr,
              { ctx->type_f32 }, 1 },
            { "pgy_intent_enter_export", ctx->type_i32,
              { ctx->type_i8ptr, LLVMPointerType(ctx->type_i8ptr, 0), ctx->type_i32, ctx->type_i1, ctx->type_i32 }, 5 },
            { "pgy_intent_exit_export", ctx->type_void,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_trace_step_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr, ctx->type_i8ptr }, 3 },
            { "pgy_intent_trace_bind_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr, ctx->type_i8ptr }, 3 },
            { "pgy_intent_trace_step_ok_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr }, 2 },
            { "pgy_intent_trace_fail_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr }, 2 },
            { "pgy_intent_last_trace_export", ctx->type_i8ptr,
              { }, 0 },
            { "pgy_intent_last_failure_export", ctx->type_i8ptr,
              { }, 0 },
            { "pgy_intent_last_name_export", ctx->type_i8ptr,
              { }, 0 },
            { "pgy_intent_last_handle_export", ctx->type_i32,
              { }, 0 },
            { "pgy_intent_last_trace_id_export", ctx->type_i32,
              { }, 0 },
            { "pgy_intent_last_step_count_export", ctx->type_i32,
              { }, 0 },
            { "pgy_intent_last_failed_export", ctx->type_i1,
              { }, 0 },
            { "pgy_intent_history_count_export", ctx->type_i32,
              { }, 0 },
            { "pgy_intent_history_step_name_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_zone_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_phase_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_participant_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_slot_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_from_zone_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_from_slot_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_to_zone_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_to_slot_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_ok_export", ctx->type_i1,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_history_step_failure_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_count_export", ctx->type_i32,
              { }, 0 },
            { "pgy_intent_active_name_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_handle_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_trace_id_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_priority_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_concurrent_export", ctx->type_i1,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_trace_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_parent_handle_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_subject_count_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_step_count_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_failed_export", ctx->type_i1,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_failure_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_active_step_name_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_zone_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_phase_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_participant_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_slot_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_from_zone_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_from_slot_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_to_zone_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_to_slot_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_ok_export", ctx->type_i1,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_active_step_failure_export", ctx->type_i8ptr,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "pgy_intent_current_handle_export", ctx->type_i32,
              { }, 0 },
            { "pgy_intent_recent_count_export", ctx->type_i32,
              { }, 0 },
            { "pgy_intent_recent_handle_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_recent_trace_id_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_recent_name_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_recent_trace_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_recent_failure_export", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_recent_step_count_export", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_recent_failed_export", ctx->type_i1,
              { ctx->type_i32 }, 1 },
            { "pgy_intent_trace_materialize_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr }, 4 },
            { "pgy_intent_trace_transfer_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr }, 6 },
            { "pgy_mir_resource_op_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr }, 4 },
            { "pgy_mir_cleanup_op_export", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr }, 4 },
            { "pgy_zone_authority_check_export", ctx->type_void,
              { ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i8ptr }, 4 },
            { "pgy_zone_authority_check_token_export", ctx->type_void,
              { ctx->type_i8ptr, ctx->type_i8ptr, ctx->type_i64, ctx->type_i64, ctx->type_i8ptr, ctx->type_i8ptr }, 6 },
            { "pgy_zone_authority_validate_flags_export", ctx->type_i1,
              { ctx->type_i1, ctx->type_i1, ctx->type_i8ptr, ctx->type_i8ptr }, 4 },
            { "pgy_zone_authority_validate_token_flags_export", ctx->type_i1,
              { ctx->type_i1, ctx->type_i1, ctx->type_i64, ctx->type_i64, ctx->type_i8ptr, ctx->type_i8ptr }, 6 },
            { "pgy_zone_authority_last_ok_rt_export", ctx->type_i1,
              { 0 }, 0 },
            { "pgy_zone_authority_last_zone_rt_export", ctx->type_i8ptr,
              { 0 }, 0 },
            { "pgy_zone_authority_last_participant_rt_export", ctx->type_i8ptr,
              { 0 }, 0 },
            { "pgy_zone_authority_last_code_rt_export", ctx->type_i8ptr,
              { 0 }, 0 },
            { "pgy_zone_authority_last_reason_rt_export", ctx->type_i8ptr,
              { 0 }, 0 },
            { "pgy_read_file", ctx->type_i8ptr,
              { ctx->type_i8ptr }, 1 },
            { "pgy_write_file", ctx->type_void,
              { ctx->type_i8ptr, ctx->type_i8ptr }, 2 },
            { "pgy_input", ctx->type_i8ptr,
              { ctx->type_i8ptr }, 1 },
            { "pgy_now_ms", ctx->type_i32,
              { 0 }, 0 },
            { "pgy_sleep_ms", ctx->type_void,
              { ctx->type_i32 }, 1 },
            { "SeedRandom", ctx->type_void,
              { ctx->type_i32 }, 1 },
            { "pgy_file_open", ctx->type_i32,
              { ctx->type_i8ptr, ctx->type_i8ptr }, 2 },
            { "pgy_file_read", ctx->type_i8ptr,
              { ctx->type_i32 }, 1 },
            { "pgy_file_write", ctx->type_void,
              { ctx->type_i32, ctx->type_i8ptr }, 2 },
            { "pgy_file_close", ctx->type_void,
              { ctx->type_i32 }, 1 },
            { "ClaimQubit", ctx->type_i32,
              { 0 }, 0 },
            { "Measure", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "Entangle", ctx->type_void,
              { ctx->type_i32, ctx->type_i32 }, 2 },
            { "QubitState", ctx->type_i32,
              { ctx->type_i32 }, 1 },
            { "IsCollapsed", ctx->type_i1,
              { ctx->type_i32 }, 1 },
            { "ReleaseQubit", ctx->type_void,
              { ctx->type_i32 }, 1 },
            { "H", ctx->type_void,
              { ctx->type_i32 }, 1 },
            { "IntoClassical", ctx->type_i1,
              { ctx->type_i32 }, 1 },
        };

        for (size_t i = 0; i < sizeof(builtins) / sizeof(builtins[0]); i++) {
            LLVMTypeRef ft = LLVMFunctionType(
                builtins[i].ret, builtins[i].params,
                builtins[i].param_count, 0);
            LLVMValueRef fn = LLVMAddFunction(ctx->module, builtins[i].name, ft);
            llvm_register_function(ctx, builtins[i].name, fn, ft, builtins[i].ret);
        }
    }
}

#endif
