#ifndef PGY_SRC_CODEGEN_TRANSPILER_TYPE_RENDER_HELPERS_H
#define PGY_SRC_CODEGEN_TRANSPILER_TYPE_RENDER_HELPERS_H

#include "transpiler_type_render.h"

#endif /* PGY_SRC_CODEGEN_TRANSPILER_TYPE_RENDER_HELPERS_H */
