#ifndef PGY_TRANSPILER_EXPR_TYPE_INFER_CALL_POLICY_H
#define PGY_TRANSPILER_EXPR_TYPE_INFER_CALL_POLICY_H

#include <stdbool.h>

typedef enum TranspilerInferCallOp
{
    TRANS_INFER_CALL_NONE = 0,
    TRANS_INFER_CALL_ABS,
    TRANS_INFER_CALL_CLAMP,
    TRANS_INFER_CALL_CLONE,
    TRANS_INFER_CALL_DEVICE_READ,
    TRANS_INFER_CALL_IS_NONE,
    TRANS_INFER_CALL_IS_SOME,
    TRANS_INFER_CALL_LIST_GET,
    TRANS_INFER_CALL_MAP_GET,
    TRANS_INFER_CALL_MAP_KEYS,
    TRANS_INFER_CALL_MAX,
    TRANS_INFER_CALL_MIN,
    TRANS_INFER_CALL_NONE_CTOR,
    TRANS_INFER_CALL_RECV_TIMEOUT,
    TRANS_INFER_CALL_SEND_TIMEOUT_STATUS,
    TRANS_INFER_CALL_SOME,
    TRANS_INFER_CALL_SUBMIT_DEVICE_READ,
    TRANS_INFER_CALL_TO_OBJECT,
    TRANS_INFER_CALL_TO_TOBJECT,
    TRANS_INFER_CALL_TRY_RECV,
    TRANS_INFER_CALL_TRY_SEND_STATUS,
    TRANS_INFER_CALL_UNWRAP_OPTION,
    TRANS_INFER_CALL_VIEW_READ,
    TRANS_INFER_CALL_VIEW_WRITE,
} TranspilerInferCallOp;

TranspilerInferCallOp transpiler_infer_call_lookup(const char *name);
bool transpiler_infer_call_is_numeric_passthrough(TranspilerInferCallOp op);
bool transpiler_infer_call_returns_channel_status(TranspilerInferCallOp op);
bool transpiler_infer_call_returns_channel_option(TranspilerInferCallOp op);

#endif /* PGY_TRANSPILER_EXPR_TYPE_INFER_CALL_POLICY_H */
