# CI Linux step list. Sourced by scripts/ci_step_runner.sh.
#
# Each `run` line is labeled by the runner and aborts the whole CI on first
# failure with a final `[ci-linux FAILED at step N: <cmd>]` message. Required
# env vars: CI_LINUX_CC, CI_LINUX_BUILD_DIR, CI_LINUX_BIN_DIR,
# CI_BACKEND_COMPARE_SHARD_TOTAL, CI_BACKEND_COMPARE_SHARD_INDEX. The Makefile
# `ci-linux` recipe exports these before invoking the runner.

run 'make check-build-tools CC="$CI_LINUX_CC"'
run 'make check-linux-toolchain'
run 'make build-source-inventory-test-smoke'
run 'make source-utf8-test-smoke'
run 'make backend-fail-closed-test-smoke'
run 'make worker-boundary-ub-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" clean'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" test-all'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" llvm-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" fmt-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" tooling-conformance-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" stdlib-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" stage4-determinism-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" filesystem-directory-walk-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" module-test-smoke'
run 'make module-taxonomy-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" package-module-resolver-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" unicode-policy-test-smoke'
run 'make beta-test-suite-freeze-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" observability-schema-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" memory-concurrency-model-test-smoke'
run 'make documentation-quality-test-smoke'
run 'make self-host-preparation-test-smoke'
run 'make debug-hygiene-test-smoke'
run 'make memory-string-safety-test-smoke'
run 'make security-portability-contract-test-smoke'
run 'make beta-readiness-checklist-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" dogfood-webgl-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" runtime-none-contract-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" raw-escape-contract-test-smoke'
run 'make formal-semantics-test-smoke'
run 'make abstraction-loss-contract-test-smoke'
run 'make air-drift-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" air-json-schema-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" air-backend-nonimpact-full-test-smoke'
run 'make semantic-inc-size-test-smoke'
run 'make semantic-tu-size-test-smoke'
run 'make production-header-size-test-smoke'
run 'make backend-inc-size-test-smoke'
run 'make test-inc-size-test-smoke'
run 'make CC="$CI_LINUX_CC" source-test-harness-compile-test-smoke'
run 'make transpile-strict-source-test-smoke'
run 'make inc-sentinel-test-smoke'
run 'make semantic-core-shape-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" type-resolution-dag-test-smoke'
run 'make type-resolution-resolver-inventory-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" semantic-fixture-isolation-test-smoke'
run 'make diagnostic-registry-test-smoke'
run 'make layered-diagnostics-contract-test-smoke'
run 'make intent-compression-contract-test-smoke'
run 'make runtime-authority-contract-test-smoke'
run 'make runtime-panic-contract-test-smoke'
run 'make CC="$CI_LINUX_CC" runtime-panic-abi-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" runtime-panic-codegen-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" slot-contract-test-smoke'
run 'make projection-diagnostic-contract-test-smoke'
run 'make runtime-abi-lifetime-test-smoke'
run 'make abi-ownership-shape-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" runtime-frontier-contract-test-smoke'
run 'make CC="$CI_LINUX_CC" runtime-frontier-policy-test-smoke'
run 'make runtime-intent-observability-contract-test-smoke'
run 'make parallel-core-contract-test-smoke'
run 'make perf-contract-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" perf-c-baseline-test-smoke'
run 'make parser-lexer-diagnostic-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" diagnostics-json-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" ir-pipeline-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" cfg-body-dataflow-test-smoke'
run 'make ast-dispatch-test-smoke'
run 'make mir-declaration-inventory-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" example-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" llvm-test-abi-same-process'
run 'PGY_BACKEND_COMPARE_SHARD_TOTAL="$CI_BACKEND_COMPARE_SHARD_TOTAL" PGY_BACKEND_COMPARE_SHARD_INDEX="$CI_BACKEND_COMPARE_SHARD_INDEX" PGY_BACKEND_COMPARE_PRECHECK=0 make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" llvm-test-backend-compare'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" llvm-campaign-projection-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" llvm-dnd-campaign-test-smoke'
run 'PGY_BACKEND_COMPARE_SHARD_TOTAL="$CI_BACKEND_COMPARE_SHARD_TOTAL" PGY_BACKEND_COMPARE_SHARD_INDEX="$CI_BACKEND_COMPARE_SHARD_INDEX" PGY_BACKEND_COMPARE_PRECHECK=0 make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" air-strict-backend-compare-test-smoke'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" clean'
run 'make CC="$CI_LINUX_CC" BUILD_DIR="$CI_LINUX_BUILD_DIR" BIN_DIR="$CI_LINUX_BIN_DIR" test-all'
