# CI macOS step list. Sourced by scripts/ci_step_runner.sh.
# Required env vars: CI_MACOS_CC, CI_MACOS_BUILD_DIR, CI_MACOS_BIN_DIR.

run 'make check-build-tools CC="$CI_MACOS_CC" LLVM_ENABLED=0'
run 'make check-macos-toolchain'
run 'make build-source-inventory-test-smoke'
run 'make grammar-cheatsheet-contract-test-smoke'
run 'make source-utf8-test-smoke'
run 'make backend-fail-closed-test-smoke'
run 'make worker-boundary-ub-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" clean'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" test-all'
run 'PGY_STDLIB_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" fmt-test-smoke'
run 'PGY_STDLIB_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" tooling-conformance-test-smoke'
run 'PGY_STDLIB_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" stdlib-test-smoke'
run 'PGY_STAGE4_DETERMINISM_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" stage4-determinism-test-smoke'
run 'PGY_FILESYSTEM_WALK_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" filesystem-directory-walk-test-smoke'
run 'make module-taxonomy-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" package-module-resolver-test-smoke'
run 'PGY_UNICODE_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" unicode-policy-test-smoke'
run 'make beta-test-suite-freeze-test-smoke'
run 'make language-contract-golden-test-smoke'
run 'PGY_OBSERVABILITY_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" observability-schema-test-smoke'
run 'PGY_MEMORY_CONCURRENCY_BACKENDS=c make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" memory-concurrency-model-test-smoke'
run 'make documentation-quality-test-smoke'
run 'PGY_AIR_GRAPH_JSON_SKIP_DRIFT=1 make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" self-host-preparation-test-smoke'
run 'make debug-hygiene-test-smoke'
run 'make memory-string-safety-test-smoke'
run 'make security-portability-contract-test-smoke'
run 'make beta-readiness-checklist-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" dogfood-webgl-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" runtime-none-contract-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" slot-contract-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" raw-escape-contract-test-smoke'
run 'make formal-semantics-test-smoke'
run 'make abstraction-loss-contract-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" air-drift-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" air-json-schema-test-smoke'
run 'make perf-contract-test-smoke'
run 'make test-inc-size-test-smoke'
run 'make CC="$CI_MACOS_CC" source-test-harness-compile-test-smoke'
run 'make transpile-strict-source-test-smoke'
run 'make mir-declaration-inventory-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" diagnostics-json-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" cfg-body-dataflow-test-smoke'
run 'make CC="$CI_MACOS_CC" LLVM_ENABLED=0 BUILD_DIR="$CI_MACOS_BUILD_DIR" BIN_DIR="$CI_MACOS_BIN_DIR" semantic-fixture-isolation-test-smoke'
run 'make layered-diagnostics-contract-test-smoke'
run 'make intent-compression-contract-test-smoke'
run 'make parser-lexer-diagnostic-test-smoke'
