#!/usr/bin/env python3
"""Validate builtin argument-retention rows and render the self-host view."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re


ROW_MACRO = "PGY_BUILTIN_ARGUMENT_RETENTION"
BORROWED = "PGY_REGION_RETENTION_BORROWED_FOR_CALL"
ANY = "PGY_RETENTION_ARGUMENT_ANY"


@dataclass(frozen=True)
class RetentionRow:
    identity: str
    source_name: str
    argument_ordinal: int | None


def _strip_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    return re.sub(r"//.*?$", "", source, flags=re.MULTILINE)


def load_rows(path: Path) -> list[RetentionRow]:
    source = _strip_comments(path.read_text(encoding="utf-8"))
    row_pattern = re.compile(rf"\s*{ROW_MACRO}\(([^()]*)\)")
    bodies: list[str] = []
    offset = 0
    while offset < len(source):
        match = row_pattern.match(source, offset)
        if match is None:
            if source[offset:].strip():
                line = source.count("\n", 0, offset) + 1
                raise ValueError(
                    f"unexpected builtin argument-retention registry text at line {line}"
                )
            break
        bodies.append(match.group(1))
        offset = match.end()
    rows: list[RetentionRow] = []
    for row_number, body in enumerate(bodies, start=1):
        fields = [field.strip() for field in body.split(",")]
        if len(fields) != 4:
            raise ValueError(f"retention row {row_number} expected 4 fields")
        identity, source, ordinal, kind = fields
        if re.fullmatch(r"[A-Z][A-Z0-9_]*", identity) is None:
            raise ValueError(f"retention row {row_number} has invalid builtin identity")
        source_match = re.fullmatch(r'"([A-Za-z][A-Za-z0-9_]*)"', source)
        if source_match is None:
            raise ValueError(f"retention row {row_number} has invalid source name")
        if ordinal == ANY:
            argument_ordinal = None
        elif re.fullmatch(r"0|[1-9][0-9]*", ordinal):
            argument_ordinal = int(ordinal)
        else:
            raise ValueError(f"retention row {row_number} has invalid argument ordinal")
        if kind != BORROWED:
            raise ValueError(f"retention row {row_number} has unknown retention kind")
        rows.append(RetentionRow(identity, source_match.group(1), argument_ordinal))
    if not rows:
        raise ValueError("builtin argument-retention registry is empty")
    if len({row.identity for row in rows}) != len(rows):
        raise ValueError("builtin argument-retention identities must be unique")
    if len({row.source_name for row in rows}) != len(rows):
        raise ValueError("builtin argument-retention names must be unique")
    return rows


def render(rows: list[RetentionRow]) -> str:
    lines = [
        "// Generated by scripts/render_builtin_argument_retention_registry.py.",
        "// Source: builtin_argument_retention_registry.def. Do not edit by hand.",
        "",
        "struct SemanticBuiltinArgumentRetentionRow {",
        "    valid: Bool;",
        "    builtin_identity: String;",
        "    source_name: String;",
        "    argument_ordinal: Int;",
        "    any_argument: Bool;",
        "}",
        "",
        f"func SemanticBuiltinArgumentRetentionCount() -> Int {{ return {len(rows)}; }}",
        "",
        "func SemanticBuiltinArgumentRetentionRowAt(index: Int) -> SemanticBuiltinArgumentRetentionRow {",
    ]
    for index, row in enumerate(rows):
        ordinal = -1 if row.argument_ordinal is None else row.argument_ordinal
        any_argument = "true" if row.argument_ordinal is None else "false"
        lines.append(
            f'    if index == {index} {{ return SemanticBuiltinArgumentRetentionRow('
            f'true, "{row.identity}", "{row.source_name}", '
            f'{ordinal}, {any_argument}); }}'
        )
    lines.extend([
        '    return SemanticBuiltinArgumentRetentionRow(false, "", "", -1, false);',
        "}",
        "",
        "func SemanticBuiltinArgumentRetentionIdentityForSourceName(source_name: String) -> Option<String> {",
        "    if source_name == \"\" { return None; }",
        "    let row_index: Int = 0;",
        "    while row_index < SemanticBuiltinArgumentRetentionCount() {",
        "        let row: SemanticBuiltinArgumentRetentionRow = SemanticBuiltinArgumentRetentionRowAt(row_index);",
        "        if row.valid && row.source_name == source_name {",
        "            return Some(row.builtin_identity);",
        "        }",
        "        row_index = row_index + 1;",
        "    }",
        "    return None;",
        "}",
        "",
        "func SemanticBuiltinArgumentBorrowedForIdentity(builtin_identity: String, argument_ordinal: Int) -> Bool {",
        "    if builtin_identity == \"\" || argument_ordinal < 0 { return false; }",
        "    let row_index: Int = 0;",
        "    while row_index < SemanticBuiltinArgumentRetentionCount() {",
        "        let row: SemanticBuiltinArgumentRetentionRow = SemanticBuiltinArgumentRetentionRowAt(row_index);",
        "        if row.valid && row.builtin_identity == builtin_identity &&",
        "            (row.any_argument || row.argument_ordinal == argument_ordinal) { return true; }",
        "        row_index = row_index + 1;",
        "    }",
        "    return false;",
        "}",
        "",
        "func SemanticBuiltinArgumentBorrowedForCall(source_name: String, argument_ordinal: Int) -> Bool {",
        "    let identity: Option<String> =",
        "        SemanticBuiltinArgumentRetentionIdentityForSourceName(source_name);",
        "    return IsSome(identity) && SemanticBuiltinArgumentBorrowedForIdentity(",
        "        UnwrapOption(identity), argument_ordinal);",
        "}",
        "",
        "func SemanticBuiltinArgumentRetentionProjectionReady() -> Bool {",
        "    let seen_identities: HashMap<String, Int> = MapNew();",
        "    let seen_names: HashMap<String, Int> = MapNew();",
        "    let row_index: Int = 0;",
        "    while row_index < SemanticBuiltinArgumentRetentionCount() {",
        "        let row: SemanticBuiltinArgumentRetentionRow = SemanticBuiltinArgumentRetentionRowAt(row_index);",
        "        if !row.valid || row.builtin_identity == \"\" || row.source_name == \"\" ||",
        "            (row.any_argument && row.argument_ordinal != -1) ||",
        "            (!row.any_argument && row.argument_ordinal < 0) ||",
        "            MapHas(seen_identities, row.builtin_identity) ||",
        "            MapHas(seen_names, row.source_name) { return false; }",
        "        MapSet(seen_identities, row.builtin_identity, 1);",
        "        MapSet(seen_names, row.source_name, 1);",
        "        row_index = row_index + 1;",
        "    }",
        "    let string_length: Option<String> =",
        "        SemanticBuiltinArgumentRetentionIdentityForSourceName(\"StringLength\");",
        "    let unknown: Option<String> =",
        "        SemanticBuiltinArgumentRetentionIdentityForSourceName(\"UserCompilerArtifactWrite\");",
        "    return IsSome(string_length) &&",
        "        UnwrapOption(string_length) == \"STRING_LENGTH\" && !IsSome(unknown) &&",
        "        SemanticBuiltinArgumentBorrowedForIdentity(\"COMPILER_ARTIFACT_WRITE\", 1) &&",
        "        !SemanticBuiltinArgumentBorrowedForIdentity(\"COMPILER_ARTIFACT_WRITE\", 0) &&",
        "        SemanticBuiltinArgumentBorrowedForIdentity(\"LOG\", 7) &&",
        "        SemanticBuiltinArgumentBorrowedForIdentity(\"STRING_LENGTH\", 0) &&",
        "        !SemanticBuiltinArgumentBorrowedForIdentity(\"STRING_LENGTH\", 1) &&",
        "        SemanticBuiltinArgumentBorrowedForIdentity(\"CHAR_CODE\", 0) &&",
        "        !SemanticBuiltinArgumentBorrowedForIdentity(\"CHAR_CODE\", 1) &&",
        "        SemanticBuiltinArgumentBorrowedForIdentity(\"CONCAT\", 0) &&",
        "        SemanticBuiltinArgumentBorrowedForIdentity(\"CONCAT\", 1) &&",
        "        !SemanticBuiltinArgumentBorrowedForIdentity(\"StringLength\", 0) &&",
        "        SemanticBuiltinArgumentBorrowedForCall(\"CompilerArtifactWrite\", 1) &&",
        "        !SemanticBuiltinArgumentBorrowedForCall(\"CompilerArtifactWrite\", 0) &&",
        "        SemanticBuiltinArgumentBorrowedForCall(\"StringLength\", 0) &&",
        "        !SemanticBuiltinArgumentBorrowedForCall(\"UserCompilerArtifactWrite\", 1);",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("registry", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(load_rows(args.registry))
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit("builtin argument-retention projection is stale")
    else:
        args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
