"""Project native primitive identity, not an independent ownership policy."""
from __future__ import annotations

import argparse
from pathlib import Path
import re


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    source = (root / "src/semantic/type_system.c").read_text(encoding="utf-8")
    names = re.findall(r'TYPE_[A-Z_]+\s*=\s*type_create_primitive\("([^"\n]+)"', source)
    if not names or len(names) != len(set(names)):
        raise SystemExit("native primitive identity inventory is empty or duplicated")
    text = "\n".join([
        "// Generated by scripts/render_native_primitive_type_projection.py; do not edit.",
        "// Primitive kind identity owner: src/semantic/type_system.c.",
        "// This is not a copyability or cancellation policy.",
        "func SemanticNativePrimitiveTypeName(name: String) -> Bool {",
        *[f'    if name == "{name}" {{ return true; }}' for name in names],
        "    return false;", "}", "",
    ])
    output = root / "src/self_hosted/semantic/native_primitive_type_projection_owner.pgy"
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != text:
            raise SystemExit("native primitive projection drifted; run --write")
    else:
        output.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
