#!/usr/bin/env python3
"""Project the native stable-scalar-key predicate without owning its policy."""
from __future__ import annotations

import argparse
from pathlib import Path
import re


def render(root: Path) -> str:
    source = (root / "src/semantic/type_checker_collection_policy.c").read_text(encoding="utf-8")
    match = re.search(r"type_checker_stable_scalar_key_supported\(const Type \*key_type\)\s*\{([^}]+)\}", source)
    if match is None:
        raise ValueError("stable scalar key owner is missing")
    body = match.group(1).strip()
    row = r"type_equals\(key_type, TYPE_([A-Z]+)\)"
    if not re.fullmatch(r"return\s+" + row + r"(?:\s*\|\|\s*" + row + r")*;", body):
        raise ValueError("stable scalar key policy is not a literal type predicate")
    symbols = re.findall(row, body)
    if not symbols or len(set(symbols)) != len(symbols):
        raise ValueError("empty or duplicated stable scalar key policy")
    spellings = {"STRING": "String", "INT": "Int", "LONG": "Long", "BOOL": "Bool", "FLOAT": "Float"}
    if any(symbol not in spellings for symbol in symbols):
        raise ValueError("unknown canonical scalar type symbol")
    conditions = [f'type_name == "{spellings[symbol]}"' for symbol in symbols]
    return "\n".join([
        "// Generated by scripts/render_collection_key_policy.py; do not edit.",
        "// Policy owner: src/semantic/type_checker_collection_policy.c.",
        "func SemanticCollectionStableKeySupported(type_name: String) -> Bool {",
        "    return " + " ||\n        ".join(conditions) + ";",
        "}", "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    output = root / "src/self_hosted/semantic/collection_key_policy_projection_owner.pgy"
    expected = render(root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit("collection key projection drifted; run --write")
    else:
        output.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
