#!/usr/bin/env python3
"""Project explicit fixed effects; absent operations retain unknown provenance."""
from __future__ import annotations

import argparse
from pathlib import Path
import re

import render_callable_contract_vocabulary as vocabulary


def render(root: Path) -> str:
    words = vocabulary.load_rows(root / "src/semantic/callable_contract_vocabulary.def")
    effects = {row.mask_symbol: row.spelling for row in words if row.axis == "effect"}
    path = root / "src/semantic/builtin_effect_registry.def"
    source = re.sub(r"/\*.*?\*/", "", path.read_text(encoding="utf-8"), flags=re.S)
    lines = [
        "// Generated by scripts/render_builtin_effect_registry.py; do not edit.",
        "// Source: src/semantic/builtin_effect_registry.def.",
        'import "effect_mask_owner.pgy";',
        "",
        "func SemanticBuiltinFixedEffectMask(name: String) -> Int {",
    ]
    seen: set[str] = set()
    for line in source.splitlines():
        if not line.strip():
            continue
        match = re.fullmatch(r'PGY_BUILTIN_EFFECT\("([A-Za-z][A-Za-z0-9_]*)", ([A-Z_]+(?: \| [A-Z_]+)*)\)', line)
        if match is None:
            raise ValueError(f"malformed fixed effect row: {line}")
        name, expression = match.groups()
        symbols = expression.split(" | ")
        if name in seen or len(set(symbols)) != len(symbols) or any(s not in effects for s in symbols):
            raise ValueError(f"duplicate identity or unknown effect on {name}")
        if "EFFECT_NONE" in symbols and len(symbols) != 1:
            raise ValueError(f"local cannot mix with nonlocal effects on {name}")
        seen.add(name)
        value = f'SemanticEffectMaskForWord("{effects[symbols[0]]}")'
        for symbol in symbols[1:]:
            value = f'SemanticEffectMaskJoin({value}, SemanticEffectMaskForWord("{effects[symbol]}"))'
        lines.append(f'    if name == "{name}" {{ return {value}; }}')
    if not seen:
        raise ValueError("fixed effect registry is empty")
    lines.extend(["    return -1;", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    output = root / "src/self_hosted/semantic/builtin_effect_projection_owner.pgy"
    expected = render(root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit("fixed builtin effect projection drifted; run --write")
    else:
        output.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
