#!/usr/bin/env python3
"""Validate and render the self-host intent observability ABI projection."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re


ROW = re.compile(
    r"PGY_INTENT_OBSERVABILITY_ABI\(\s*([0-9]+)\s*,\s*"
    r'"(Intent[A-Za-z0-9_]*)"\s*,\s*'
    r'"(pgy_intent_[a-z0-9_]+_export)"\s*,\s*'
    r"(PGY_INTENT_OBSERVABILITY_PARAMS_(?:NONE|INT|INT_INT))\s*,\s*"
    r"(PGY_INTENT_OBSERVABILITY_RETURN_(?:INT|BOOL|STRING))\s*\)"
)

RETURN_TYPES = {
    "PGY_INTENT_OBSERVABILITY_RETURN_INT": "Int",
    "PGY_INTENT_OBSERVABILITY_RETURN_BOOL": "Bool",
    "PGY_INTENT_OBSERVABILITY_RETURN_STRING": "String",
}

PARAMETER_SHAPES = {
    "PGY_INTENT_OBSERVABILITY_PARAMS_NONE": (0, ""),
    "PGY_INTENT_OBSERVABILITY_PARAMS_INT": (1, "Int"),
    "PGY_INTENT_OBSERVABILITY_PARAMS_INT_INT": (2, "Int|Int"),
}


@dataclass(frozen=True)
class IntentObservabilityAbiRow:
    stable_id: int
    source_name: str
    runtime_name: str
    parameter_shape: str
    return_kind: str

    @property
    def return_type(self) -> str:
        return RETURN_TYPES[self.return_kind]

    @property
    def argument_count(self) -> int:
        return PARAMETER_SHAPES[self.parameter_shape][0]

    @property
    def parameter_types(self) -> str:
        return PARAMETER_SHAPES[self.parameter_shape][1]


def load_rows(registry: Path) -> list[IntentObservabilityAbiRow]:
    source = re.sub(
        r"/\*.*?\*/", "", registry.read_text(encoding="utf-8"),
        flags=re.DOTALL,
    )
    rows = [
        IntentObservabilityAbiRow(
            int(match.group(1)), match.group(2), match.group(3),
            match.group(4), match.group(5),
        )
        for match in ROW.finditer(source)
    ]
    if not rows:
        raise ValueError("intent observability ABI registry has no rows")
    stable_ids = [row.stable_id for row in rows]
    if any(stable_id <= 0 for stable_id in stable_ids):
        raise ValueError("intent observability ABI IDs must be positive")
    if len(set(stable_ids)) != len(stable_ids):
        raise ValueError("intent observability ABI contains duplicate stable IDs")
    if [row.source_name for row in rows] != sorted(
        row.source_name for row in rows
    ):
        raise ValueError("intent observability ABI rows must be source-name sorted")
    for label, values in (
        ("source names", [row.source_name for row in rows]),
        ("runtime names", [row.runtime_name for row in rows]),
    ):
        if len(set(values)) != len(values):
            raise ValueError(f"intent observability ABI contains duplicate {label}")
    return rows


def render_projection(rows: list[IntentObservabilityAbiRow]) -> str:
    lines = [
        "// Generated by scripts/render_intent_observability_abi.py.",
        "// Source: src/common/intent_observability_abi.def. Do not edit by hand.",
        "// Responsibility: complete intent-observability runtime-call ABI row.",
        "",
        "struct IntentObservabilityAbiRow {",
        "    let valid: Bool;",
        "    let runtime_call_abi_id: Int;",
        "    let source_name: String;",
        "    let runtime_name: String;",
        "    let argument_count: Int;",
        "    let return_type: String;",
        "    let parameter_types: String;",
        "}",
        "",
        f"func IntentObservabilityAbiCount() -> Int {{ return {len(rows)}; }}",
        "",
        "func IntentObservabilityAbiRowAt(index: Int) -> IntentObservabilityAbiRow {",
    ]
    for index, row in enumerate(rows):
        lines.append(
            f"    if index == {index} {{ return IntentObservabilityAbiRow("
            f'true, {row.stable_id}, "{row.source_name}", '
            f'"{row.runtime_name}", {row.argument_count}, '
            f'"{row.return_type}", "{row.parameter_types}"); }}'
        )
    lines.extend([
        "    return IntentObservabilityAbiRow(false, 0, \"\", \"\", -1, \"\", \"\");",
        "}",
        "",
        "func IntentObservabilityAbiRowForSource(",
        "    source_name: String",
        ") -> IntentObservabilityAbiRow {",
        "    let i: Int = 0;",
        "    while i < IntentObservabilityAbiCount() {",
        "        let row: IntentObservabilityAbiRow = IntentObservabilityAbiRowAt(i);",
        "        if row.source_name == source_name { return row; }",
        "        i = i + 1;",
        "    }",
        "    return IntentObservabilityAbiRow(false, 0, \"\", \"\", -1, \"\", \"\");",
        "}",
        "",
        "func IntentObservabilityAbiRowForId(",
        "    runtime_call_abi_id: Int",
        ") -> IntentObservabilityAbiRow {",
        "    let i: Int = 0;",
        "    while i < IntentObservabilityAbiCount() {",
        "        let row: IntentObservabilityAbiRow = IntentObservabilityAbiRowAt(i);",
        "        if row.runtime_call_abi_id == runtime_call_abi_id { return row; }",
        "        i = i + 1;",
        "    }",
        "    return IntentObservabilityAbiRow(false, 0, \"\", \"\", -1, \"\", \"\");",
        "}",
        "",
        "func IntentObservabilityAbiRowForCarriedIdentity(",
        "    runtime_call_abi_id: Int, source_name: String",
        ") -> IntentObservabilityAbiRow {",
        "    let row: IntentObservabilityAbiRow =",
        "        IntentObservabilityAbiRowForId(runtime_call_abi_id);",
        "    if !row.valid || row.source_name != source_name {",
        "        return IntentObservabilityAbiRow(false, 0, \"\", \"\", -1, \"\", \"\");",
        "    }",
        "    return row;",
        "}",
        "",
    ])
    lines.extend([
        "func IntentObservabilityAbiSignatureRows() -> Array<String> {",
        "    let rows: Array<String> = [];",
        "    let i: Int = 0;",
        "    while i < IntentObservabilityAbiCount() {",
        "        let row: IntentObservabilityAbiRow =",
        "            IntentObservabilityAbiRowAt(i);",
        "        let params: String = row.parameter_types;",
        "        if params == \"\" { params = \"none\"; }",
        "        ArrayPush(rows, row.source_name + \"^\" +",
        "            row.return_type + \"^\" + params);",
        "        i = i + 1;",
        "    }",
        "    return rows;",
        "}",
        "",
        "func IntentObservabilityAbiReady() -> Bool {",
        "    if IntentObservabilityAbiRowAt(-1).valid ||",
        "        IntentObservabilityAbiRowAt(IntentObservabilityAbiCount()).valid {",
        "        return false;",
        "    }",
        "    let i: Int = 0;",
        "    while i < IntentObservabilityAbiCount() {",
        "        let row: IntentObservabilityAbiRow =",
        "            IntentObservabilityAbiRowAt(i);",
        "        if !row.valid || row.runtime_call_abi_id <= 0 ||",
        "            row.source_name == \"\" || row.runtime_name == \"\" ||",
        "            row.return_type == \"\" ||",
        "            (row.argument_count == 0 && row.parameter_types != \"\") ||",
        "            (row.argument_count == 1 && row.parameter_types != \"Int\") ||",
        "            (row.argument_count == 2 && row.parameter_types != \"Int|Int\") ||",
        "            row.argument_count < 0 || row.argument_count > 2 {",
        "            return false;",
        "        }",
        "        i = i + 1;",
        "    }",
        "    return ArrayLength(IntentObservabilityAbiSignatureRows()) ==",
        "        IntentObservabilityAbiCount();",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("registry", type=Path)
    parser.add_argument("projection", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_projection(load_rows(args.registry))
    if args.check:
        if not args.projection.exists() or args.projection.read_text(
            encoding="utf-8"
        ) != rendered:
            raise SystemExit(f"generated projection is stale: {args.projection}")
        return 0
    args.projection.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
