#!/usr/bin/env python3
"""Render and verify the self-host keyword projection from the C registry."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re


MACRO = "PGY_LANGUAGE_KEYWORD"
EXPECTED_ROW_COUNT = 71


@dataclass(frozen=True)
class KeywordRow:
    spelling: str
    debug_identity: str


def _macro_bodies(source: str) -> list[str]:
    bodies: list[str] = []
    cursor = 0
    while True:
        start = source.find(MACRO, cursor)
        if start < 0:
            return bodies
        opening = source.find("(", start + len(MACRO))
        if opening < 0:
            raise ValueError(f"{MACRO} without an opening parenthesis")

        depth = 1
        quoted = False
        escaped = False
        index = opening + 1
        while index < len(source) and depth > 0:
            char = source[index]
            if quoted:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    quoted = False
            elif char == '"':
                quoted = True
            elif char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            index += 1
        if depth != 0:
            raise ValueError(f"unterminated {MACRO} row")
        bodies.append(source[opening + 1 : index - 1])
        cursor = index


def _split_fields(body: str) -> list[str]:
    fields: list[str] = []
    start = 0
    depth = 0
    quoted = False
    escaped = False
    for index, char in enumerate(body):
        if quoted:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                quoted = False
            continue
        if char == '"':
            quoted = True
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == "," and depth == 0:
            fields.append(body[start:index].strip())
            start = index + 1
    fields.append(body[start:].strip())
    return fields


def _plain_c_string(field: str, label: str) -> str:
    match = re.fullmatch(r'"([A-Za-z0-9_]+)"', field)
    if match is None:
        raise ValueError(f"{label} must be one plain C string, got: {field!r}")
    return match.group(1)


def load_rows(registry: Path) -> list[KeywordRow]:
    source = registry.read_text(encoding="utf-8")
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    source = re.sub(r"//.*?$", "", source, flags=re.MULTILINE)
    rows: list[KeywordRow] = []
    for row_number, body in enumerate(_macro_bodies(source), start=1):
        fields = _split_fields(body)
        if len(fields) != 8:
            raise ValueError(
                f"registry row {row_number} has {len(fields)} fields; expected 8"
            )
        spelling = _plain_c_string(fields[0], f"row {row_number} spelling")
        debug_identity = _plain_c_string(
            fields[3], f"row {row_number} debug identity"
        )
        if fields[1] != "PGY_KEYWORD_CLASS_RESERVED":
            raise ValueError(f"row {row_number} is not a reserved keyword")
        if "PGY_KEYWORD_SUPPORT_SELF_HOST" not in fields[6]:
            raise ValueError(f"row {row_number} is not marked self-host supported")
        rows.append(KeywordRow(spelling, debug_identity))

    if len(rows) != EXPECTED_ROW_COUNT:
        raise ValueError(
            f"registry has {len(rows)} rows; expected {EXPECTED_ROW_COUNT}"
        )
    spellings = [row.spelling for row in rows]
    if spellings != sorted(spellings):
        raise ValueError("registry spellings are not bytewise sorted")
    if len(spellings) != len(set(spellings)):
        raise ValueError("registry contains duplicate spellings")
    identities = [row.debug_identity for row in rows]
    if any(re.fullmatch(r"[A-Z][A-Z0-9_]*", value) is None for value in identities):
        raise ValueError("registry contains a non-canonical debug identity")
    return rows


def render(rows: list[KeywordRow]) -> str:
    lines = [
        "// Generated by scripts/render_language_keyword_registry.py.",
        "// Source: src/lexer/language_keyword_registry.def. Do not edit by hand.",
        "// This checked-in projection gives the self-host lexer the same 71-word",
        "// spelling -> canonical debug-identity map as the native lexer.",
        "",
        "func LanguageKeywordRegistryCount() -> Int {",
        f"    return {len(rows)};",
        "}",
        "",
        "func LanguageKeywordSpellingAt(index: Int) -> String {",
    ]
    for index, row in enumerate(rows):
        lines.append(f'    if index == {index} {{ return "{row.spelling}"; }}')
    lines.extend([
        '    return "";',
        "}",
        "",
        "func LanguageKeywordDebugIdentityAt(index: Int) -> String {",
    ])
    for index, row in enumerate(rows):
        lines.append(f'    if index == {index} {{ return "{row.debug_identity}"; }}')
    lines.extend([
        '    return "";',
        "}",
        "",
        "func LanguageKeywordDebugIdentity(text: String) -> String {",
    ])
    for row in rows:
        lines.append(
            f'    if text == "{row.spelling}" {{ return "{row.debug_identity}"; }}'
        )
    lines.extend([
        '    return "IDENTIFIER";',
        "}",
        "",
        "func LanguageKeywordRegistryProjectionReady() -> Bool {",
        "    let index: Int = 0;",
        "    while index < LanguageKeywordRegistryCount() {",
        "        let spelling: String = LanguageKeywordSpellingAt(index);",
        "        let identity: String = LanguageKeywordDebugIdentityAt(index);",
        "        if StringLength(spelling) == 0 || StringLength(identity) == 0 {",
        "            return false;",
        "        }",
        "        if LanguageKeywordDebugIdentity(spelling) != identity {",
        "            return false;",
        "        }",
        "        index = index + 1;",
        "    }",
        '    return LanguageKeywordDebugIdentity("projection") == "IDENTIFIER";',
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("registry", type=Path)
    parser.add_argument("projection", type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    expected = render(load_rows(args.registry))
    if args.check:
        if not args.projection.is_file():
            raise SystemExit(f"missing generated projection: {args.projection}")
        actual = args.projection.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(
                "self-host keyword projection drifted; regenerate with "
                f"{Path(__file__).as_posix()} {args.registry.as_posix()} "
                f"{args.projection.as_posix()} --write"
            )
        return 0

    args.projection.parent.mkdir(parents=True, exist_ok=True)
    args.projection.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
