#!/usr/bin/env python3
"""Checked Pergyra projection of the native HashMap key ABI table."""
from __future__ import annotations

import argparse
from pathlib import Path
import re


def render(root: Path) -> str:
    source = (root / "src/codegen/codegen_hashmap_key_policy.c").read_text(encoding="utf-8")
    table = re.search(r"pgy_hashmap_key_specs\[\]\s*=\s*\{(.*?)\};", source, re.S)
    if table is None:
        raise ValueError("native HashMap key ABI table missing")
    row = r'\{\s*"([A-Za-z]+)"\s*,\s*PGY_HASHMAP_KEY_[A-Z]+\s*,\s*"([_a-z0-9]*)"\s*\},'
    rows = re.findall(row, table.group(1))
    if not rows or re.sub(row, "", table.group(1)).strip():
        raise ValueError("native HashMap key ABI table is not a literal table")
    if len({name for name, _ in rows}) != len(rows) or len({infix for _, infix in rows}) != len(rows):
        raise ValueError("duplicated HashMap key ABI name or infix")
    llvm = (root / "src/codegen/llvm_runtime_raw_collections.c").read_text(encoding="utf-8")
    declarations = re.findall(
        r'\{\s*LLVMTypeRef params\[\]\s*=\s*\{([^}]+)\};\s*'
        r'LLVMTypeRef ft = LLVMFunctionType\(ctx->type_void, params, \d+, 0\);\s*'
        r'LLVMValueRef fn = LLVMAddFunction\(ctx->module,\s*"([^"]+)", ft\);', llvm)
    key_types = []
    llvm_types = {"ctx->type_i8ptr": "ptr", "ctx->type_i32": "i32",
                  "ctx->type_i64": "i64", "ctx->type_i1": "i1"}
    for name, infix in rows:
        matches = [params for params, symbol in declarations
                   if symbol == f"pgy_map_set_raw{infix}_export"]
        if len(matches) != 1:
            raise ValueError(f"native raw HashMap key declaration missing/duplicated: {name}")
        parameters = [part.strip() for part in matches[0].split(",")]
        if len(parameters) != 4 or parameters[1] not in llvm_types:
            raise ValueError(f"native raw HashMap key declaration is not concrete: {name}")
        key_types.append((name, llvm_types[parameters[1]]))
    raw = (root / "src/runtime/pgy_runtime_lib_raw_map_exports.h").read_text(encoding="utf-8")
    shape = re.search(r"typedef struct\s*\{([^}]+)\}\s*PgyHashMapRaw;", raw)
    if shape is None:
        raise ValueError("native raw HashMap storage declaration missing")
    field = r"(char\s*\*\s*\*|void\s*\*|uint8_t\s*\*|size_t)\s*(\w+)\s*;"
    fields = re.findall(field, shape.group(1))
    if re.sub(field, "", shape.group(1)).strip() or [name for _, name in fields] != [
            "keys", "values", "occupied", "count", "capacity"]:
        raise ValueError("native raw HashMap field contract changed; migrate consumers")
    # The reached native target contract is 64-bit, as checked by the ABI gate.
    storage = ", ".join("ptr" if "*" in kind else "i64" for kind, _ in fields)
    return "\n".join([
        "// Generated by scripts/render_hashmap_key_abi.py; do not edit.",
        "// ABI owner: src/codegen/codegen_hashmap_key_policy.c.",
        "func CollectionHashMapKeyCInfix(type_name: String) -> Option<String> {",
        *[f'    if type_name == "{name}" {{ return Some("{infix}"); }}' for name, infix in rows],
        "    return None;", "}", "",
        "// Native LLVM raw-call declarations own the key parameter representation.",
        "func CollectionHashMapKeyLlvmType(type_name: String) -> Option<String> {",
        *[f'    if type_name == "{name}" {{ return Some("{kind}"); }}' for name, kind in key_types],
        "    return None;", "}", "",
        "// Storage owner: src/runtime/pgy_runtime_lib_raw_map_exports.h.",
        "func CollectionHashMapRawLlvmStorageType() -> String {",
        f'    return "{{ {storage} }}";', "}", "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    output = root / "src/self_hosted/codegen/runtime_abi/hashmap_key_abi_projection_owner.pgy"
    expected = render(root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit("HashMap key ABI projection drifted; run --write")
    else:
        output.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
