#!/usr/bin/env python3
"""Validate and render the self-host intent observability ABI projection."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re


ROW = re.compile(
    r"PGY_INTENT_OBSERVABILITY_ABI\(\s*([0-9]+)\s*,\s*"
    r'"(Intent[A-Za-z0-9_]*)"\s*,\s*'
    r'"(pgy_intent_[a-z0-9_]+_export)"\s*,\s*([0-9]+)\s*,\s*'
    r"(PGY_INTENT_OBSERVABILITY_RETURN_(?:INT|BOOL|STRING))\s*\)"
)

RETURN_TYPES = {
    "PGY_INTENT_OBSERVABILITY_RETURN_INT": "Int",
    "PGY_INTENT_OBSERVABILITY_RETURN_BOOL": "Bool",
    "PGY_INTENT_OBSERVABILITY_RETURN_STRING": "String",
}


@dataclass(frozen=True)
class IntentObservabilityAbiRow:
    stable_id: int
    source_name: str
    runtime_name: str
    arg_count: int
    return_kind: str

    @property
    def return_type(self) -> str:
        return RETURN_TYPES[self.return_kind]

    @property
    def parameter_types(self) -> str:
        return "|".join("Int" for _ in range(self.arg_count))


def load_rows(registry: Path) -> list[IntentObservabilityAbiRow]:
    source = re.sub(
        r"/\*.*?\*/", "", registry.read_text(encoding="utf-8"),
        flags=re.DOTALL,
    )
    rows = [
        IntentObservabilityAbiRow(
            int(match.group(1)), match.group(2), match.group(3),
            int(match.group(4)), match.group(5),
        )
        for match in ROW.finditer(source)
    ]
    if not rows:
        raise ValueError("intent observability ABI registry has no rows")
    if [row.stable_id for row in rows] != list(range(1, len(rows) + 1)):
        raise ValueError("intent observability ABI IDs must be contiguous from one")
    if [row.source_name for row in rows] != sorted(
        row.source_name for row in rows
    ):
        raise ValueError("intent observability ABI rows must be source-name sorted")
    for label, values in (
        ("source names", [row.source_name for row in rows]),
        ("runtime names", [row.runtime_name for row in rows]),
    ):
        if len(set(values)) != len(values):
            raise ValueError(f"intent observability ABI contains duplicate {label}")
    if any(row.arg_count < 0 or row.arg_count > 2 for row in rows):
        raise ValueError("intent observability ABI argument count exceeds bounded ABI")
    return rows


def _render_indexed_function(
    name: str, return_type: str, rows: list[IntentObservabilityAbiRow],
    value, fallback: str,
) -> list[str]:
    lines = [f"func {name}(index: Int) -> {return_type} {{"]
    for index, row in enumerate(rows):
        lines.append(f"    if index == {index} {{ return {value(row)}; }}")
    lines.extend([f"    return {fallback};", "}"])
    return lines


def render_projection(rows: list[IntentObservabilityAbiRow]) -> str:
    lines = [
        "// Generated by scripts/render_intent_observability_abi.py.",
        "// Source: src/common/intent_observability_abi.def. Do not edit by hand.",
        "// Responsibility: append-only runtime-call ABI projection for self-host semantics.",
        "",
        f"func IntentObservabilityAbiCount() -> Int {{ return {len(rows)}; }}",
        "",
    ]
    functions = [
        ("IntentObservabilityAbiStableIdAt", "Int", lambda row: str(row.stable_id), "0"),
        ("IntentObservabilityAbiSourceNameAt", "String", lambda row: f'"{row.source_name}"', '""'),
        ("IntentObservabilityAbiRuntimeNameAt", "String", lambda row: f'"{row.runtime_name}"', '""'),
        ("IntentObservabilityAbiArgumentCountAt", "Int", lambda row: str(row.arg_count), "-1"),
        ("IntentObservabilityAbiReturnTypeAt", "String", lambda row: f'"{row.return_type}"', '""'),
        ("IntentObservabilityAbiParameterTypesAt", "String", lambda row: f'"{row.parameter_types}"', '""'),
    ]
    for name, return_type, value, fallback in functions:
        lines.extend(_render_indexed_function(
            name, return_type, rows, value, fallback
        ))
        lines.append("")
    lines.extend([
        "func IntentObservabilityAbiSignatureRows() -> Array<String> {",
        "    let rows: Array<String> = [];",
        "    let i: Int = 0;",
        "    while i < IntentObservabilityAbiCount() {",
        "        let params: String = IntentObservabilityAbiParameterTypesAt(i);",
        "        if params == \"\" { params = \"none\"; }",
        "        ArrayPush(rows, IntentObservabilityAbiSourceNameAt(i) + \"^\" +",
        "            IntentObservabilityAbiReturnTypeAt(i) + \"^\" + params);",
        "        i = i + 1;",
        "    }",
        "    return rows;",
        "}",
        "",
        "func IntentObservabilityAbiReady() -> Bool {",
        "    let i: Int = 0;",
        "    while i < IntentObservabilityAbiCount() {",
        "        if IntentObservabilityAbiStableIdAt(i) != i + 1 ||",
        "            IntentObservabilityAbiSourceNameAt(i) == \"\" ||",
        "            IntentObservabilityAbiRuntimeNameAt(i) == \"\" ||",
        "            IntentObservabilityAbiArgumentCountAt(i) < 0 ||",
        "            IntentObservabilityAbiArgumentCountAt(i) > 2 ||",
        "            IntentObservabilityAbiReturnTypeAt(i) == \"\" {",
        "            return false;",
        "        }",
        "        i = i + 1;",
        "    }",
        "    return ArrayLength(IntentObservabilityAbiSignatureRows()) ==",
        "        IntentObservabilityAbiCount();",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("registry", type=Path)
    parser.add_argument("projection", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_projection(load_rows(args.registry))
    if args.check:
        if not args.projection.exists() or args.projection.read_text(
            encoding="utf-8"
        ) != rendered:
            raise SystemExit(f"generated projection is stale: {args.projection}")
        return 0
    args.projection.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
