#!/usr/bin/env python3
"""Validate and render the self-host compiler-internal caller projection."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re


ROW = re.compile(
    r'PGY_COMPILER_INTERNAL_BUILTIN_CALLER\(\s*"([A-Za-z0-9_]+)"\s*,\s*'
    r'"([A-Za-z0-9_./]+)"\s*,\s*"([A-Za-z0-9_]+)"\s*,\s*'
    r'(PGY_COMPILER_INTERNAL_PARAM_OWN)\s*,\s*'
    r'"([A-Za-z0-9_<>]+)"\s*,\s*"([A-Za-z0-9_<>]+)"\s*\)'
)


@dataclass(frozen=True)
class CallerRow:
    builtin_name: str
    module_path: str
    function_name: str
    parameter_mode: str
    parameter_type: str
    return_type: str


def load_rows(registry: Path) -> list[CallerRow]:
    source = re.sub(
        r"/\*.*?\*/", "", registry.read_text(encoding="utf-8"),
        flags=re.DOTALL,
    )
    rows = [CallerRow(*match.groups()) for match in ROW.finditer(source)]
    if not rows:
        raise ValueError("compiler-internal caller registry has no rows")
    identities = [
        (row.builtin_name, row.module_path, row.function_name)
        for row in rows
    ]
    if len(set(identities)) != len(identities):
        raise ValueError("compiler-internal caller registry has duplicate identities")
    if identities != sorted(identities):
        raise ValueError("compiler-internal caller registry must be identity sorted")
    for row in rows:
        if not row.module_path.startswith("src/self_hosted/"):
            raise ValueError("compiler-internal caller path must be self-host owned")
    return rows


def render(rows: list[CallerRow]) -> str:
    lines = [
        "// Generated by scripts/render_compiler_internal_builtin_caller_registry.py.",
        "// Source: src/common/compiler_internal_builtin_caller_registry.def.",
        "// Responsibility: complete compiler-internal builtin caller identity.",
        "",
        "struct SemanticCompilerInternalBuiltinCallerRow {",
        "    valid: Bool;",
        "    builtin_name: String;",
        "    module_path: String;",
        "    function_name: String;",
        "    parameter_type: String;",
        "    return_type: String;",
        "}",
        "",
        f"func SemanticCompilerInternalBuiltinCallerCount() -> Int {{ return {len(rows)}; }}",
        "",
        "func SemanticCompilerInternalBuiltinCallerRowAt(",
        "    index: Int",
        ") -> SemanticCompilerInternalBuiltinCallerRow {",
    ]
    for index, row in enumerate(rows):
        lines.extend([
            f"    if index == {index} {{",
            "        return SemanticCompilerInternalBuiltinCallerRow(",
            f'            true, "{row.builtin_name}", "{row.module_path}",',
            f'            "{row.function_name}", "{row.parameter_type}",',
            f'            "{row.return_type}"',
            "        );",
            "    }",
        ])
    lines.extend([
        "    return SemanticCompilerInternalBuiltinCallerRow(",
        '        false, "", "", "", "", ""',
        "    );",
        "}",
        "",
        "func SemanticCompilerInternalBuiltinModulePathMatches(",
        "    source_path: String, suffix: String",
        ") -> Bool {",
        "    let path_length: Int = StringLength(source_path);",
        "    let suffix_length: Int = StringLength(suffix);",
        "    if path_length < suffix_length { return false; }",
        "    let i: Int = 0;",
        "    while i < suffix_length {",
        "        let actual: Int = CharCode(",
        "            source_path, path_length, path_length - suffix_length + i",
        "        );",
        "        let expected: Int = CharCode(suffix, suffix_length, i);",
        "        if actual == 92 { actual = 47; }",
        "        if actual != expected { return false; }",
        "        i = i + 1;",
        "    }",
        "    if path_length == suffix_length { return true; }",
        "    let boundary: Int = CharCode(",
        "        source_path, path_length, path_length - suffix_length - 1",
        "    );",
        "    return boundary == 47 || boundary == 92;",
        "}",
        "",
        "func SemanticCompilerInternalBuiltinCallerReady(",
        "    source_path: String, builtin_name: String, function_name: String,",
        "    return_type: String, param_count: Int, param_type: String,",
        "    own_parameter: Bool",
        ") -> Bool {",
        "    if source_path == \"\" || !own_parameter || param_count != 1 {",
        "        return false;",
        "    }",
        "    let i: Int = 0;",
        "    while i < SemanticCompilerInternalBuiltinCallerCount() {",
        "        let row: SemanticCompilerInternalBuiltinCallerRow =",
        "            SemanticCompilerInternalBuiltinCallerRowAt(i);",
        "        if row.valid && row.builtin_name == builtin_name &&",
        "            row.function_name == function_name &&",
        "            row.return_type == return_type &&",
        "            row.parameter_type == param_type &&",
        "            SemanticCompilerInternalBuiltinModulePathMatches(",
        "                source_path, row.module_path",
        "            ) { return true; }",
        "        i = i + 1;",
        "    }",
        "    return false;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("registry", type=Path)
    parser.add_argument("projection", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(load_rows(args.registry))
    if args.check:
        if not args.projection.exists() or args.projection.read_text(
            encoding="utf-8"
        ) != rendered:
            raise SystemExit(f"generated projection is stale: {args.projection}")
        return 0
    args.projection.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
