#!/usr/bin/env python3
"""Validate and render the MIR declaration-field vocabulary projection."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re


ROW = re.compile(
    r"PGY_MIR_DECL_FIELD_KIND\(\s*([A-Z][A-Z0-9_]*)\s*,\s*"
    r"([0-9]+)\s*,\s*\"([a-z][a-z0-9_]*)\"\s*,\s*"
    r'\"([A-Za-z]*)\"\s*\)'
)


@dataclass(frozen=True)
class FieldKind:
    identity: str
    stable_id: int
    spelling: str
    ast_label: str


def load_rows(registry: Path) -> list[FieldKind]:
    source = re.sub(r"/\*.*?\*/", "", registry.read_text(encoding="utf-8"),
                    flags=re.DOTALL)
    rows = [FieldKind(m.group(1), int(m.group(2)), m.group(3), m.group(4))
            for m in ROW.finditer(source)]
    if not rows:
        raise ValueError("field-kind registry has no rows")
    if [row.stable_id for row in rows] != list(range(len(rows))):
        raise ValueError("field-kind stable ids must be contiguous registry order")
    if len({row.identity for row in rows}) != len(rows):
        raise ValueError("field-kind registry contains duplicate identities")
    if len({row.spelling for row in rows}) != len(rows):
        raise ValueError("field-kind registry contains duplicate spellings")
    labels = [row.ast_label for row in rows if row.ast_label]
    if len(set(labels)) != len(labels):
        raise ValueError("field-kind registry contains duplicate AST labels")
    return rows


def _func_suffix(identity: str) -> str:
    return "".join(part.title() for part in identity.lower().split("_"))


def render_projection(rows: list[FieldKind]) -> str:
    lines = [
        "// Generated by scripts/render_mir_decl_field_kind_vocabulary.py.",
        "// Source: src/compiler/mir_decl_field_kind_vocabulary.def. Do not edit by hand.",
        "// Responsibility: stable declaration-field wire vocabulary projection.",
        "",
        f"func MirDeclFieldKindCount() -> Int {{ return {len(rows)}; }}",
        "",
        "func MirDeclFieldKindSpellingAt(index: Int) -> String {",
    ]
    for row in rows:
        lines.append(
            f'    if index == {row.stable_id} {{ return "{row.spelling}"; }}'
        )
    lines.extend(['    return "";', "}", "", "func MirDeclFieldKindAstLabelAt(index: Int) -> String {"])
    for row in rows:
        lines.append(
            f'    if index == {row.stable_id} {{ return "{row.ast_label}"; }}'
        )
    lines.extend(['    return "";', "}", "", "func MirDeclFieldKindFindIndex(kind: String) -> Int {"])
    for row in rows:
        lines.append(
            f'    if kind == "{row.spelling}" {{ return {row.stable_id}; }}'
        )
    lines.extend(["    return -1;", "}", "", "func MirDeclFieldKindKnown(kind: String) -> Bool {",
                  "    return MirDeclFieldKindFindIndex(kind) >= 0;", "}"])
    for row in rows:
        lines.extend([
            "",
            f"func MirDeclFieldKind{_func_suffix(row.identity)}() -> String {{",
            f"    return MirDeclFieldKindSpellingAt({row.stable_id});",
            "}",
        ])
    lines.extend([
        "",
        "func MirDeclFieldKindAstLabel(kind: String) -> String {",
        "    return MirDeclFieldKindAstLabelAt(MirDeclFieldKindFindIndex(kind));",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("registry", type=Path)
    parser.add_argument("projection", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_projection(load_rows(args.registry))
    if args.check:
        if not args.projection.exists() or args.projection.read_text(
            encoding="utf-8"
        ) != rendered:
            raise SystemExit(f"generated projection is stale: {args.projection}")
        return 0
    args.projection.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
