    static const char *intent_authority_snapshot_source =
        "extern \"C\" {\n"
        "    func pgy_zone_authority_last_ok_rt_export() -> Bool;\n"
        "    func pgy_zone_authority_last_zone_rt_export() -> String;\n"
        "    func pgy_zone_authority_last_participant_rt_export() -> String;\n"
        "    func pgy_zone_authority_last_reason_rt_export() -> String;\n"
        "}\n"
        "within PaymentZone {\n"
        "    subject Buyer {\n"
        "        let hp: Int;\n"
        "        action Approve(self) -> Void\n"
        "            authorized by self\n"
        "            causes Charged\n"
        "        {\n"
        "            hp = hp + 1;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "effect Charged for bearer: Buyer { }\n"
        "zone CartZone {\n"
        "    subject slot buyer: Buyer\n"
        "    authority buyer\n"
        "}\n"
        "zone PaymentZone {\n"
        "    subject slot buyer: Buyer\n"
        "    effect slot charged: Charged\n"
        "    authority buyer\n"
        "    state chargedState: effect charged on buyer\n"
        "}\n"
        "intent Checkout(cart: CartZone, payment: PaymentZone, buyer: Buyer) {\n"
        "    step Charge {\n"
        "        where: PaymentZone;\n"
        "        using: payment;\n"
        "        transfer: cart -> payment;\n"
        "        who: buyer;\n"
        "        authorized by: buyer;\n"
        "        on: buyer.Approve();\n"
        "        expect: payment.buyer.hp == 8;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let cart = CartZone(Buyer(7));\n"
        "    let payment = PaymentZone(Buyer(0));\n"
        "    let ok = Checkout(cart, payment, cart.buyer);\n"
        "    Log(ok);\n"
        "    Log(pgy_zone_authority_last_ok_rt_export());\n"
        "    Log(pgy_zone_authority_last_zone_rt_export());\n"
        "    Log(pgy_zone_authority_last_participant_rt_export());\n"
        "    Log(pgy_zone_authority_last_reason_rt_export());\n"
        "}\n";
    static const char *intent_authority_snapshot_expected =
        "true\n"
        "true\n"
        "PaymentZone\n"
        "buyer\n"
        "\n";
    static const char *relation_effect_zone_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "}\n"
        "object PlayerView {\n"
        "    hp: Int;\n"
        "}\n"
        "effect Poisoned for bearer: Player { }\n"
        "relation Allied for source: Player, target: Player { }\n"
        "zone ArenaZone {\n"
        "    subject slot player: Player\n"
        "    subject slot ally: Player\n"
        "    object slot playerView: PlayerView\n"
        "    effect slot poison: Poisoned\n"
        "    relation slot alliance: Allied\n"
        "    authority player\n"
        "    state poisoned: effect poison on player\n"
        "    state allied: relation alliance between player, ally\n"
        "    refresh playerView from player by player\n"
        "    maintain poisoned by player\n"
        "    maintain allied by player\n"
        "    func Snapshot(self) -> Void {\n"
        "        Log(HasLayer(poison));\n"
        "        Log(HasLayer(alliance));\n"
        "        Log(HasState(poisoned));\n"
        "        Log(HasState(poisoned, player));\n"
        "        Log(HasState(allied, player, ally));\n"
        "        Log(playerView.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let arena = ArenaZone(Player(42), Player(7));\n"
        "    arena.Snapshot();\n"
        "}\n";
    static const char *relation_effect_zone_expected =
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "42\n";
    static const char *world_handoff_mutation_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "}\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    shared hp: Int = 0\n"
        "    authority player\n"
        "    func BumpBy(amount: Int) -> Void {\n"
        "        hp = hp + amount;\n"
        "    }\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    func Advance(self) -> Void {\n"
        "        battle.BumpBy(5);\n"
        "        Log(battle.hp);\n"
        "    }\n"
        "    func Read(self) -> Void {\n"
        "        Log(battle.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let battle = BattleZone(Player(10));\n"
        "    let world = GameWorld(Clone(battle));\n"
        "    world.Advance();\n"
        "    battle.BumpBy(1);\n"
        "    world.Read();\n"
        "    Log(battle.hp);\n"
        "}\n";
    static const char *world_handoff_mutation_expected =
        "5\n"
        "5\n"
        "1\n";
    static const char *handoff_projection_frontier_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Promote(self) -> Void {\n"
        "        hp = hp + 2;\n"
        "    }\n"
        "}\n"
        "object BuyerView {\n"
        "    hp: Int;\n"
        "}\n"
        "zone CartZone {\n"
        "    subject slot buyer: Buyer\n"
        "    object slot mirror: BuyerView = BuyerView(0)\n"
        "    authority buyer\n"
        "    bind mirror from buyer by buyer\n"
        "    func Ready(self) -> Bool {\n"
        "        return HasProjection(mirror);\n"
        "    }\n"
        "    func MirrorHp(self) -> Int {\n"
        "        return mirror.hp;\n"
        "    }\n"
        "}\n"
        "zone PaymentZone {\n"
        "    subject slot buyer: Buyer\n"
        "    object slot receipt: BuyerView = BuyerView(0)\n"
        "    authority buyer\n"
        "    bind receipt from buyer by buyer\n"
        "    func Ready(self) -> Bool {\n"
        "        return HasProjection(receipt);\n"
        "    }\n"
        "    func ReceiptHp(self) -> Int {\n"
        "        return receipt.hp;\n"
        "    }\n"
        "}\n"
        "intent Checkout(cart: CartZone, payment: PaymentZone, buyer: Buyer) {\n"
        "    step Handoff {\n"
        "        where: PaymentZone;\n"
        "        using: payment;\n"
        "        transfer: cart -> payment;\n"
        "        who: buyer;\n"
        "        authorized by: buyer;\n"
        "        on: buyer.Promote();\n"
        "        expect: payment.Ready() && payment.receipt.hp == 7;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let cart = CartZone(Buyer(5), BuyerView(0));\n"
        "    let payment = PaymentZone(Buyer(0), BuyerView(0));\n"
        "    Log(cart.Ready());\n"
        "    Log(cart.MirrorHp());\n"
        "    Log(payment.Ready());\n"
        "    Log(payment.ReceiptHp());\n"
        "    let ok = Checkout(cart, payment, cart.buyer);\n"
        "    Log(ok);\n"
        "    Log(cart.Ready());\n"
        "    Log(cart.MirrorHp());\n"
        "    Log(payment.Ready());\n"
        "    Log(payment.ReceiptHp());\n"
        "}\n";
    static const char *handoff_projection_frontier_expected =
        "true\n"
        "5\n"
        "true\n"
        "0\n"
        "true\n"
        "true\n"
        "5\n"
        "true\n"
        "7\n";
    static const char *handoff_world_state_frontier_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Promote(self) -> Void {\n"
        "        hp = hp + 2;\n"
        "    }\n"
        "}\n"
        "object BuyerView {\n"
        "    hp: Int;\n"
        "}\n"
        "zone CartZone {\n"
        "    subject slot buyer: Buyer\n"
        "    object slot mirror: BuyerView = BuyerView(0)\n"
        "    authority buyer\n"
        "    bind mirror from buyer by buyer\n"
        "}\n"
        "zone PaymentZone {\n"
        "    subject slot buyer: Buyer\n"
        "    object slot receipt: BuyerView = BuyerView(0)\n"
        "    authority buyer\n"
        "    bind receipt from buyer by buyer\n"
        "}\n"
        "world CheckoutWorld {\n"
        "    zone cart: CartZone\n"
        "    zone payment: PaymentZone\n"
        "    state cartReady: zone cart projection mirror\n"
        "    state paymentReady: zone payment projection receipt\n"
        "    state bothReady: all cartReady, paymentReady\n"
        "    activate cart\n"
        "    activate payment\n"
        "    func Report(self) -> Void {\n"
        "        Log(HasZone(cartReady));\n"
        "        Log(HasZone(paymentReady));\n"
        "        Log(HasZone(bothReady));\n"
        "        Log(HasZoneProjection(payment, receipt));\n"
        "        Log(payment.receipt.hp);\n"
        "    }\n"
        "}\n"
        "intent Checkout(cart: CartZone, payment: PaymentZone, buyer: Buyer) {\n"
        "    step Handoff {\n"
        "        where: PaymentZone;\n"
        "        using: payment;\n"
        "        transfer: cart -> payment;\n"
        "        who: buyer;\n"
        "        authorized by: buyer;\n"
        "        on: buyer.Promote();\n"
        "        expect: payment.receipt.hp == 7;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = CheckoutWorld(\n"
        "        CartZone(Buyer(5), BuyerView(0)),\n"
        "        PaymentZone(Buyer(0), BuyerView(0)));\n"
        "    world.Report();\n"
        "    let ok = Checkout(world.cart, world.payment, world.cart.buyer);\n"
        "    Log(ok);\n"
        "    world.Report();\n"
        "}\n";
    static const char *handoff_world_state_frontier_expected =
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "0\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "7\n";
    static const char *handoff_layer_state_frontier_source =
        "within PaymentZone {\n"
        "    subject Buyer {\n"
        "        let hp: Int;\n"
        "        action Promote(self) -> Void\n"
        "            authorized by self\n"
        "            causes Charged\n"
        "        {\n"
        "            hp = hp + 2;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "effect Charged for bearer: Buyer { }\n"
        "zone CartZone {\n"
        "    subject slot buyer: Buyer\n"
        "    authority buyer\n"
        "}\n"
        "zone PaymentZone {\n"
        "    subject slot buyer: Buyer\n"
        "    effect slot charged: Charged\n"
        "    authority buyer\n"
        "    state chargedState: effect charged on buyer\n"
        "    func Report(self) -> Void {\n"
        "        Log(HasLayer(charged));\n"
        "        Log(HasState(chargedState, buyer));\n"
        "    }\n"
        "}\n"
        "world CheckoutWorld {\n"
        "    zone cart: CartZone\n"
        "    zone payment: PaymentZone\n"
        "    state paymentLayer: zone payment layer charged\n"
        "    state paymentCharged: zone payment state chargedState\n"
        "    state ready: all paymentLayer, paymentCharged\n"
        "    activate payment\n"
        "    func Report(self) -> Void {\n"
        "        Log(HasZoneLayer(payment, charged));\n"
        "        Log(HasZoneState(payment, chargedState));\n"
        "        Log(HasZone(paymentLayer));\n"
        "        Log(HasZone(paymentCharged));\n"
        "        Log(HasZone(ready));\n"
        "        Log(payment.buyer.hp);\n"
        "    }\n"
        "}\n"
        "intent Checkout(cart: CartZone, payment: PaymentZone, buyer: Buyer) {\n"
        "    step Handoff {\n"
        "        where: PaymentZone;\n"
        "        using: payment;\n"
        "        transfer: cart -> payment;\n"
        "        who: buyer;\n"
        "        authorized by: buyer;\n"
        "        on: buyer.Promote();\n"
        "        expect: payment.buyer.hp == 7;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = CheckoutWorld(CartZone(Buyer(5)), PaymentZone(Buyer(0)));\n"
        "    world.Report();\n"
        "    let ok = Checkout(world.cart, world.payment, world.cart.buyer);\n"
        "    Log(ok);\n"
        "    world.payment.Report();\n"
        "    world.Report();\n"
        "}\n";
    static const char *handoff_layer_state_frontier_expected =
        "false\n"
        "false\n"
        "false\n"
        "false\n"
        "false\n"
        "0\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "7\n";
    static const char *relation_effect_propagation_source =
        "subject Player {\n"
        "    let mut hp: Int;\n"
        "}\n"
        "object PlayerView {\n"
        "    hp: Int;\n"
        "}\n"
        "effect Poisoned for bearer: Player { }\n"
        "relation Allied for source: Player, target: Player { }\n"
        "zone ArenaZone {\n"
        "    subject slot player: Player\n"
        "    subject slot ally: Player\n"
        "    object slot playerView: PlayerView\n"
        "    effect slot poison: Poisoned\n"
        "    relation slot alliance: Allied\n"
        "    authority player\n"
        "    state poisoned: effect poison on player\n"
        "    state allied: relation alliance between player, ally\n"
        "    refresh playerView from player by player\n"
        "    maintain poisoned by player\n"
        "    maintain allied by player\n"
        "    func Pulse() -> Void {\n"
        "        player.hp = player.hp + 3;\n"
        "    }\n"
        "    func Report() -> Void {\n"
        "        Log(HasLayer(poison));\n"
        "        Log(HasState(poisoned, player));\n"
        "        Log(HasState(allied, player, ally));\n"
        "        Log(playerView.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let arena = ArenaZone(Player(40), Player(7));\n"
        "    arena.Pulse();\n"
        "    arena.Report();\n"
        "}\n";
    static const char *relation_effect_propagation_expected =
        "true\n"
        "true\n"
        "true\n"
        "43\n";
    static const char *loop_source =
        "func Spin(limit: Int) -> Int {\n"
        "    let i: Int = 0;\n"
        "    let acc: Int = 0;\n"
        "    while i < limit {\n"
        "        acc = acc + 1;\n"
        "        i = i + 1;\n"
        "    }\n"
        "    return acc;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    Log(Spin(2000000));\n"
        "}\n";
    static const char *loop_expected = "2000000\n";
    static const char *projection_medium_source =
        "object PlayerViewA { hp: Int; mp: Int; ready: Bool; x: Int; y: Int; }\n"
        "object PlayerViewB { hp: Int; mp: Int; ready: Bool; x: Int; y: Int; }\n"
        "tobject PlayerPacketA { hp: Int; mp: Int; x: Int; y: Int; }\n"
        "tobject PlayerPacketB { hp: Int; mp: Int; x: Int; y: Int; }\n"
        "subject Player {\n"
        "    let hp: Int;\n"
        "    let mp: Int;\n"
        "    let ready: Bool;\n"
        "    let x: Int;\n"
        "    let y: Int;\n"
        "}\n"
        "zone ArenaZone {\n"
        "    subject slot player: Player\n"
        "    object slot viewA: PlayerViewA\n"
        "    object slot viewB: PlayerViewB\n"
        "    tobject slot packetA: PlayerPacketA\n"
        "    tobject slot packetB: PlayerPacketB\n"
        "    authority player\n"
        "    bind viewA from player by player\n"
        "    bind viewB from player by player\n"
        "    bind packetA from player by player\n"
        "    bind packetB from player by player\n"
        "    func Snapshot() -> Void {\n"
        "        Log(viewA.hp);\n"
        "        Log(viewB.ready);\n"
        "        Log(packetA.mp);\n"
        "        Log(packetB.y);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let zone: ArenaZone = ArenaZone(Player(42, 7, true, 9, 11));\n"
        "    zone.Snapshot();\n"
        "}\n";
    static const char *projection_medium_expected =
        "42\n"
        "true\n"
        "7\n"
        "11\n";
    static const char *intent_medium_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Verify(self) -> Void { }\n"
        "    action Reserve(self) -> Void { }\n"
        "    action Confirm(self) -> Void { }\n"
        "}\n"
        "zone CheckoutZone {\n"
        "    subject slot buyer: Buyer\n"
        "}\n"
        "intent Checkout(checkout: CheckoutZone, buyer: Buyer) {\n"
        "    step verify {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Verify();\n"
        "        expect: true;\n"
        "    }\n"
        "    step reserve {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Reserve();\n"
        "        expect: true;\n"
        "    }\n"
        "    step confirm {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Confirm();\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let buyer: Buyer = Buyer(1);\n"
        "    let checkout: CheckoutZone = CheckoutZone(buyer);\n"
        "    let ok: Bool = Checkout(checkout, buyer);\n"
        "    Log(ok);\n"
        "    Log(ToString(IntentLastStepCount()));\n"
        "    Log(ToString(IntentHistoryCount()));\n"
        "}\n";
    static const char *intent_medium_expected =
        "true\n"
        "3\n"
        "3\n";
    static const char *rollback_medium_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Reserve(self) -> Void { }\n"
        "    action Charge(self) -> Void { }\n"
        "    action RollbackReserve(self) -> Void { }\n"
        "    action RollbackCharge(self) -> Void { }\n"
        "}\n"
        "zone CheckoutZone {\n"
        "    subject slot buyer: Buyer\n"
        "}\n"
        "intent Purchase(checkout: CheckoutZone, buyer: Buyer) {\n"
        "    rollback: full;\n"
        "    step reserve {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Reserve();\n"
        "        compensate: buyer.RollbackReserve();\n"
        "        expect: true;\n"
        "    }\n"
        "    step charge {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Charge();\n"
        "        compensate: buyer.RollbackCharge();\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let buyer: Buyer = Buyer(1);\n"
        "    let checkout: CheckoutZone = CheckoutZone(buyer);\n"
        "    let ok: Bool = Purchase(checkout, buyer);\n"
        "    Log(ok);\n"
        "    Log(ToString(IntentLastStepCount()));\n"
        "    Log(ToString(IntentHistoryCount()));\n"
        "}\n";
    static const char *rollback_medium_expected =
        "true\n"
        "2\n"
        "2\n";
    static const char *transfer_medium_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Promote(self) -> Void { }\n"
        "    action Finalize(self) -> Void { }\n"
        "}\n"
        "zone CartZone {\n"
        "    subject slot buyer: Buyer\n"
        "}\n"
        "zone PaymentZone {\n"
        "    subject slot buyer: Buyer\n"
        "}\n"
        "intent Checkout(cart: CartZone, payment: PaymentZone, buyer: Buyer) {\n"
        "    step promote {\n"
        "        where: PaymentZone;\n"
        "        using: payment;\n"
        "        transfer: cart -> payment;\n"
        "        who: buyer;\n"
        "        on: buyer.Promote();\n"
        "        expect: true;\n"
        "    }\n"
        "    step finalize {\n"
        "        where: PaymentZone;\n"
        "        using: payment;\n"
        "        who: buyer;\n"
        "        on: buyer.Finalize();\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let buyer: Buyer = Buyer(1);\n"
        "    let cart: CartZone = CartZone(buyer);\n"
        "    let payment: PaymentZone = PaymentZone(buyer);\n"
        "    let ok: Bool = Checkout(cart, payment, buyer);\n"
        "    Log(ok);\n"
        "    Log(ToString(IntentLastStepCount()));\n"
        "    Log(ToString(IntentHistoryCount()));\n"
        "}\n";
    static const char *transfer_medium_expected =
        "true\n"
        "2\n"
        "2\n";

    printf("=== Pergyra ABI Pipeline Integration ===\n");
    printf("This test validates end-to-end compiler output, runtime values,\n");
    printf("and a minimal runtime performance floor.\n\n");
    if (perf_mode)
        printf("Benchmark mode: hard upper bounds disabled, medium workloads enabled.\n\n");
