    static const char *projection_source =
        "object PlayerView {\n"
        "    hp: Int;\n"
        "    ready: Bool;\n"
        "}\n"
        "tobject PlayerPacket {\n"
        "    hp: Int;\n"
        "    mp: Int;\n"
        "}\n"
        "subject Player {\n"
        "    let hp: Int;\n"
        "    let mp: Int;\n"
        "    let ready: Bool;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let player: Player = Player(42, 7, true);\n"
        "    let view: PlayerView = ToObject(PlayerView, player);\n"
        "    let packet: PlayerPacket = ToTObject(PlayerPacket, player);\n"
        "    let maybe: Option<Int> = Some(packet.hp + packet.mp);\n"
        "    Log(view.hp);\n"
        "    Log(view.ready);\n"
        "    Log(packet.hp);\n"
        "    Log(packet.mp);\n"
        "    match maybe {\n"
        "        case .Some(v):\n"
        "            Log(v);\n"
        "        case .None:\n"
        "            Log(-1);\n"
        "    }\n"
        "}\n";
    static const char *projection_expected =
        "42\n"
        "true\n"
        "42\n"
        "7\n"
        "49\n";
    static const char *zone_projection_expected =
        "42\n"
        "true\n"
        "42\n"
        "7\n";
    static const char *zone_projection_source =
        "object PlayerView {\n"
        "    hp: Int;\n"
        "    ready: Bool;\n"
        "}\n"
        "tobject PlayerPacket {\n"
        "    hp: Int;\n"
        "    mp: Int;\n"
        "}\n"
        "subject Player {\n"
        "    let hp: Int;\n"
        "    let mp: Int;\n"
        "    let ready: Bool;\n"
        "}\n"
        "zone ArenaZone {\n"
        "    subject slot player: Player\n"
        "    object slot view: PlayerView\n"
        "    tobject slot packet: PlayerPacket\n"
        "    authority player\n"
        "    bind view from player by player\n"
        "    bind packet from player by player\n"
        "    func Snapshot() -> Void {\n"
        "        Log(view.hp);\n"
        "        Log(view.ready);\n"
        "        Log(packet.hp);\n"
        "        Log(packet.mp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let zone: ArenaZone = ArenaZone(Player(42, 7, true));\n"
        "    zone.Snapshot();\n"
        "}\n";
    static const char *intent_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Verify(self) -> Void { }\n"
        "}\n"
        "zone CheckoutZone {\n"
        "    subject slot buyer: Buyer\n"
        "}\n"
        "intent Charge(checkout: CheckoutZone, buyer: Buyer) {\n"
        "    step verify {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Verify();\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let buyer: Buyer = Buyer(1);\n"
        "    let checkout: CheckoutZone = CheckoutZone(buyer);\n"
        "    let ok: Bool = Charge(checkout, buyer);\n"
        "    Log(ok);\n"
        "    Log(ToString(IntentLastStepCount()));\n"
        "    Log(ToString(IntentHistoryCount()));\n"
        "    Log(ToString(IntentLastFailed()));\n"
        "    Log(ToString(IntentRecentCount()));\n"
        "    Log(IntentRecentName(0));\n"
        "    Log(ToString(IntentRecentStepCount(0)));\n"
        "    Log(ToString(IntentRecentFailed(0)));\n"
        "}\n";
    static const char *intent_expected =
        "true\n"
        "1\n"
        "1\n"
        "false\n"
        "1\n"
        "Charge\n"
        "1\n"
        "false\n";
    static const char *intent_recent_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Verify(self) -> Void { }\n"
        "    action Confirm(self) -> Void { }\n"
        "}\n"
        "zone CheckoutZone {\n"
        "    subject slot buyer: Buyer\n"
        "}\n"
        "intent Charge(checkout: CheckoutZone, buyer: Buyer) {\n"
        "    step verify {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Verify();\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "intent Confirm(checkout: CheckoutZone, buyer: Buyer) {\n"
        "    step confirm {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Confirm();\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let buyer: Buyer = Buyer(1);\n"
        "    let checkout: CheckoutZone = CheckoutZone(buyer);\n"
        "    Log(Charge(checkout, buyer));\n"
        "    Log(Confirm(checkout, buyer));\n"
        "    Log(ToString(IntentRecentCount()));\n"
        "    Log(IntentRecentName(0));\n"
        "    Log(ToString(StringLength(IntentRecentTrace(0)) > 0));\n"
        "    Log(ToString(StringLength(IntentRecentFailure(0)) == 0));\n"
        "    Log(ToString(IntentRecentStepCount(0)));\n"
        "    Log(ToString(IntentRecentFailed(0)));\n"
        "    Log(IntentRecentName(1));\n"
        "    Log(ToString(StringLength(IntentRecentTrace(1)) > 0));\n"
        "    Log(ToString(StringLength(IntentRecentFailure(1)) == 0));\n"
        "    Log(ToString(IntentRecentStepCount(1)));\n"
        "    Log(ToString(IntentRecentFailed(1)));\n"
        "}\n";
    static const char *intent_recent_expected =
        "true\n"
        "true\n"
        "2\n"
        "Confirm\n"
        "true\n"
        "true\n"
        "1\n"
        "false\n"
        "Charge\n"
        "true\n"
        "true\n"
        "1\n"
        "false\n";
    static const char *intent_active_source =
        "subject Buyer {\n"
        "    let hp: Int;\n"
        "    action Verify(self) -> Void {\n"
        "        let current: Int = IntentCurrentHandle();\n"
        "        Log(ToString(current >= 0));\n"
        "        Log(IntentActiveStepName(current, 0));\n"
        "        Log(IntentActiveStepZone(current, 0));\n"
        "        Log(IntentActiveStepParticipant(current, 0));\n"
        "        Log(ToString(StringLength(IntentActiveStepPhase(current, 0)) > 0));\n"
        "        Log(ToString(StringLength(IntentActiveStepFailure(current, 0)) == 0));\n"
        "        return;\n"
        "    }\n"
        "}\n"
        "zone CheckoutZone {\n"
        "    subject slot buyer: Buyer\n"
        "}\n"
        "intent Charge(checkout: CheckoutZone, buyer: Buyer) {\n"
        "    step verify {\n"
        "        where: CheckoutZone;\n"
        "        using: checkout;\n"
        "        who: buyer;\n"
        "        on: buyer.Verify();\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let buyer: Buyer = Buyer(1);\n"
        "    let checkout: CheckoutZone = CheckoutZone(buyer);\n"
        "    Log(Charge(checkout, buyer));\n"
        "    Log(ToString(IntentHistoryCount()));\n"
        "}\n";
    static const char *intent_active_expected =
        "true\n"
        "verify\n"
        "CheckoutZone\n"
        "buyer\n"
        "true\n"
        "true\n"
        "true\n"
        "1\n";
    static const char *intent_failure_source =
        "subject Driver {\n"
        "    let started: Bool;\n"
        "    action Ignite(self) -> Void { self.started = true; }\n"
        "    action RollbackIgnite(self) -> Void { self.started = false; }\n"
        "}\n"
        "zone CockpitZone {\n"
        "    subject slot driver: Driver\n"
        "}\n"
        "intent DriveCar(cockpit: CockpitZone, driver: Driver) {\n"
        "    rollback: current;\n"
        "    step Ignite {\n"
        "        where: CockpitZone;\n"
        "        using: cockpit;\n"
        "        on: driver.Ignite();\n"
        "        compensate: driver.RollbackIgnite();\n"
        "        pre: true;\n"
        "        guard: false;\n"
        "        post: driver.started;\n"
        "        expect: true;\n"
        "    }\n"
        "    success: true;\n"
        "    failure: false;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let driver = Driver(false);\n"
        "    let cockpit = CockpitZone(driver);\n"
        "    Log(DriveCar(cockpit, driver));\n"
        "    Log(ToString(StringLength(IntentLastTrace()) > 0));\n"
        "    Log(ToString(StringLength(IntentLastFailure()) > 0));\n"
        "    Log(ToString(IntentLastFailed()));\n"
        "    Log(ToString(IntentHistoryCount()));\n"
        "    Log(IntentHistoryStepPhase(0));\n"
        "    Log(ToString(IntentHistoryStepOk(0)));\n"
        "    Log(ToString(IntentRecentCount()));\n"
        "    Log(ToString(StringLength(IntentRecentTrace(0)) > 0));\n"
        "    Log(ToString(StringLength(IntentRecentFailure(0)) > 0));\n"
        "    Log(ToString(IntentRecentFailed(0)));\n"
        "}\n";
    static const char *intent_failure_expected =
        "false\n"
        "true\n"
        "true\n"
        "true\n"
        "1\n"
        "materialize\n"
        "false\n"
        "1\n"
        "true\n"
        "true\n"
        "true\n";
    static const char *world_clone_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "}\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    shared hp: Int = 0\n"
        "    func Hurt() -> Void { hp = hp + 1; }\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    func ReadHp() -> Int { return battle.hp; }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let battle = BattleZone(Player(10));\n"
        "    let world = GameWorld(Clone(battle));\n"
        "    battle.hp = 3;\n"
        "    battle.Hurt();\n"
        "    Log(world.ReadHp());\n"
        "    Log(battle.hp);\n"
        "}\n";
    static const char *world_clone_expected =
        "0\n"
        "4\n";
    static const char *world_zone_query_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "}\n"
        "object PlayerView {\n"
        "    hp: Int;\n"
        "}\n"
        "effect Poisoned for bearer: Player { }\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    object slot playerView: PlayerView\n"
        "    effect slot poison: Poisoned\n"
        "    authority player\n"
        "    state poisoned: effect poison on player\n"
        "    refresh playerView from player by player\n"
        "    maintain poisoned by player\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    func Show(self) -> Void {\n"
        "        Log(HasZoneProjection(battle, playerView));\n"
        "        Log(HasZoneLayer(battle, poison));\n"
        "        Log(HasZoneState(battle, poisoned));\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = GameWorld(BattleZone(Player(7)));\n"
        "    world.Show();\n"
        "}\n";
    static const char *world_zone_query_expected =
        "true\n"
        "true\n"
        "true\n";
    static const char *world_fixpoint_source =
        "zone BattleZone { }\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    state inner: zone battle\n"
        "    state outer: any inner\n"
        "    activate battle\n"
        "    func Show(self) -> Void {\n"
        "        Log(HasZone(outer));\n"
        "        Log(HasZone(inner));\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = GameWorld(BattleZone());\n"
        "    world.Show();\n"
        "}\n";
    static const char *world_fixpoint_expected =
        "true\n"
        "true\n";
    static const char *projection_chain_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "}\n"
        "object PlayerView {\n"
        "    hp: Int;\n"
        "}\n"
        "object ScoreBoard {\n"
        "    hp: Int;\n"
        "}\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    object slot playerView: PlayerView\n"
        "    object slot board: ScoreBoard\n"
        "    authority player\n"
        "    refresh board from playerView by player\n"
        "    refresh playerView from player by player\n"
        "    func Pulse(self) -> Void {\n"
        "        player.hp = player.hp + 5;\n"
        "    }\n"
        "    func Report(self) -> Void {\n"
        "        Log(board.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let battle = BattleZone(Player(7));\n"
        "    battle.Pulse();\n"
        "    battle.Report();\n"
        "}\n";
    static const char *projection_chain_expected =
        "12\n";
    static const char *zone_frontier_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "}\n"
        "effect Poisoned for bearer: Player {\n"
        "}\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    effect slot poison: Poisoned\n"
        "    authority player\n"
        "    state poisoned: effect poison on player\n"
        "    apply poison to player by player\n"
        "    func Show(self) -> Void {\n"
        "        Log(HasLayer(poison));\n"
        "        Log(HasState(poisoned));\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let player: Player = Player(5);\n"
        "    let battle: BattleZone = BattleZone(player);\n"
        "    battle.Show();\n"
        "    battle.Show();\n"
        "}\n";
    static const char *zone_frontier_expected =
        "true\n"
        "true\n"
        "true\n"
        "true\n";
    static const char *world_embedded_projection_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "}\n"
        "object PlayerView {\n"
        "    hp: Int;\n"
        "}\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    object slot playerView: PlayerView\n"
        "    authority player\n"
        "    refresh playerView from player by player\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    func Mutate(self) -> Void {\n"
        "        battle.player.hp = battle.player.hp + 2;\n"
        "    }\n"
        "    func Read(self) -> Void {\n"
        "        Log(HasZoneProjection(battle, playerView));\n"
        "        Log(battle.playerView.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = GameWorld(BattleZone(Player(5)));\n"
        "    world.Read();\n"
        "    world.Mutate();\n"
        "    world.Read();\n"
        "}\n";
    static const char *world_embedded_projection_expected =
        "true\n"
        "5\n"
        "true\n"
        "7\n";
    static const char *world_embedded_method_projection_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "    func Heal(self, amount: Int) -> Void {\n"
        "        hp = hp + amount;\n"
        "    }\n"
        "}\n"
        "object PlayerView {\n"
        "    hp: Int;\n"
        "}\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    object slot playerView: PlayerView\n"
        "    authority player\n"
        "    refresh playerView from player by player\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    func HealAndRead(self) -> Void {\n"
        "        battle.player.Heal(2);\n"
        "        Log(HasZoneProjection(battle, playerView));\n"
        "        Log(battle.playerView.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = GameWorld(BattleZone(Player(5)));\n"
        "    world.HealAndRead();\n"
        "}\n";
    static const char *world_embedded_method_projection_expected =
        "true\n"
        "7\n";
    static const char *world_embedded_branch_projection_source =
        "subject Player {\n"
        "    let hp: Int;\n"
        "    func Heal(self, amount: Int) -> Void {\n"
        "        hp = hp + amount;\n"
        "    }\n"
        "}\n"
        "object PlayerView {\n"
        "    hp: Int;\n"
        "}\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    object slot playerView: PlayerView\n"
        "    authority player\n"
        "    refresh playerView from player by player\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    func Mutate(self, healFirst: Bool) -> Void {\n"
        "        if healFirst {\n"
        "            battle.player.Heal(2);\n"
        "        } else {\n"
        "            battle.player.hp = battle.player.hp + 3;\n"
        "        }\n"
        "        Log(HasZoneProjection(battle, playerView));\n"
        "        Log(battle.playerView.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = GameWorld(BattleZone(Player(5)));\n"
        "    world.Mutate(true);\n"
        "    world.Mutate(false);\n"
        "}\n";
    static const char *world_embedded_branch_projection_expected =
        "true\n"
        "7\n"
        "true\n"
        "10\n";
    static const char *world_embedded_action_frontier_source =
        "within BattleZone {\n"
        "    subject Player {\n"
        "        let hp: Int;\n"
        "        action Attack(self) -> Void\n"
        "            authorized by self\n"
        "            causes Poisoned\n"
        "        {\n"
        "            hp = hp - 1;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "effect Poisoned for bearer: Player { }\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    effect slot poison: Poisoned\n"
        "    authority player\n"
        "    state poisoned: effect poison on player\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    state battleLayer: zone battle layer poison\n"
        "    state battlePoisoned: zone battle state poisoned\n"
        "    state ready: all battleLayer, battlePoisoned\n"
        "    activate battle\n"
        "    func AttackAndReport(self) -> Void {\n"
        "        Log(HasZoneLayer(battle, poison));\n"
        "        Log(HasZone(battleLayer));\n"
        "        battle.player.Attack();\n"
        "        Log(HasZoneLayer(battle, poison));\n"
        "        Log(HasZoneState(battle, poisoned));\n"
        "        Log(HasZone(battleLayer));\n"
        "        Log(HasZone(battlePoisoned));\n"
        "        Log(HasZone(ready));\n"
        "        Log(battle.player.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = GameWorld(BattleZone(Player(9)));\n"
        "    world.AttackAndReport();\n"
        "}\n";
    static const char *world_embedded_action_frontier_expected =
        "false\n"
        "false\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "8\n";
    static const char *world_embedded_action_pool_frontier_source =
        "within BattleZone {\n"
        "    subject Player {\n"
        "        let hp: Int;\n"
        "        action Attack(self) -> Void\n"
        "            authorized by self\n"
        "            causes Poisoned\n"
        "        {\n"
        "            hp = hp - 1;\n"
        "        }\n"
        "    }\n"
        "}\n"
        "effect Poisoned for bearer: Player { }\n"
        "zone BattleZone {\n"
        "    subject slot player: Player\n"
        "    effect pool poison: Poisoned capacity 4\n"
        "    authority player\n"
        "    state poisoned: effect poison on player\n"
        "}\n"
        "world GameWorld {\n"
        "    zone battle: BattleZone\n"
        "    state battleLayer: zone battle layer poison\n"
        "    state battlePoisoned: zone battle state poisoned\n"
        "    state ready: all battleLayer, battlePoisoned\n"
        "    activate battle\n"
        "    func AttackAndReport(self) -> Void {\n"
        "        Log(HasZoneLayer(battle, poison));\n"
        "        Log(HasZone(battleLayer));\n"
        "        battle.player.Attack();\n"
        "        Log(HasZoneLayer(battle, poison));\n"
        "        Log(HasZoneState(battle, poisoned));\n"
        "        Log(HasZone(battleLayer));\n"
        "        Log(HasZone(battlePoisoned));\n"
        "        Log(HasZone(ready));\n"
        "        Log(battle.player.hp);\n"
        "    }\n"
        "}\n"
        "func Main() -> Void {\n"
        "    let world = GameWorld(BattleZone(Player(9)));\n"
        "    world.AttackAndReport();\n"
        "}\n";
    static const char *world_embedded_action_pool_frontier_expected =
        "false\n"
        "false\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "true\n"
        "8\n";
    static const char *authority_failure_source =
        "extern \"C\" {\n"
        "    func pgy_zone_authority_validate_flags_export(hasZone: Bool, hasParticipant: Bool, zone: String, participant: String) -> Bool;\n"
        "    func pgy_zone_authority_validate_token_flags_export(hasZone: Bool, hasParticipant: Bool, expectedToken: Long, providedToken: Long, zone: String, participant: String) -> Bool;\n"
        "    func pgy_zone_authority_last_ok_rt_export() -> Bool;\n"
        "    func pgy_zone_authority_last_zone_rt_export() -> String;\n"
        "    func pgy_zone_authority_last_participant_rt_export() -> String;\n"
        "    func pgy_zone_authority_last_code_rt_export() -> String;\n"
        "    func pgy_zone_authority_last_reason_rt_export() -> String;\n"
        "}\n"
        "func Main() -> Void {\n"
        "    Log(pgy_zone_authority_validate_flags_export(true, true, \"BattleZone\", \"owner\"));\n"
        "    Log(pgy_zone_authority_last_ok_rt_export());\n"
        "    Log(pgy_zone_authority_last_zone_rt_export());\n"
        "    Log(pgy_zone_authority_last_participant_rt_export());\n"
        "    Log(pgy_zone_authority_last_code_rt_export());\n"
        "    Log(pgy_zone_authority_validate_flags_export(false, true, \"BattleZone\", \"owner\"));\n"
        "    Log(pgy_zone_authority_last_ok_rt_export());\n"
        "    Log(pgy_zone_authority_last_code_rt_export());\n"
        "    Log(pgy_zone_authority_last_reason_rt_export());\n"
        "    Log(pgy_zone_authority_validate_flags_export(true, false, \"BattleZone\", \"owner\"));\n"
        "    Log(pgy_zone_authority_last_ok_rt_export());\n"
        "    Log(pgy_zone_authority_last_code_rt_export());\n"
        "    Log(pgy_zone_authority_last_reason_rt_export());\n"
        "    Log(pgy_zone_authority_validate_token_flags_export(true, true, 777L, 777L, \"BattleZone\", \"owner\"));\n"
        "    Log(pgy_zone_authority_last_code_rt_export());\n"
        "    Log(pgy_zone_authority_validate_token_flags_export(true, true, 777L, 888L, \"BattleZone\", \"owner\"));\n"
        "    Log(pgy_zone_authority_last_ok_rt_export());\n"
        "    Log(pgy_zone_authority_last_code_rt_export());\n"
        "    Log(pgy_zone_authority_last_reason_rt_export());\n"
        "}\n";
    static const char *authority_failure_expected =
        "true\n"
        "true\n"
        "BattleZone\n"
        "owner\n"
        "ok\n"
        "false\n"
        "false\n"
        "missing-zone\n"
        "zone authority validation failed: null zone self\n"
        "false\n"
        "false\n"
        "missing-participant\n"
        "zone authority validation failed: null authority participant\n"
        "true\n"
        "ok\n"
        "false\n"
        "false\n"
        "authority-token-mismatch\n"
        "zone authority validation failed: authority token mismatch\n";
